### ISSUE TITLE
Error when Using DisassemblyDiagnoser

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1021]
I'm using version 0.11.3.933 of BenchmarkDotNet. If I add the following to my benchmark class:

[DisassemblyDiagnoser(printIL: true, printSource: true, printDiff: true)]

I get the error below at the end of a run:

System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (0, 0).
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at BenchmarkDotNet.Diagnosers.WindowsDisassembler.Disassemble(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.DisassemblyDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Extensions.CommonExtensions.ForEach[T](IList`1 source, Action`1 command)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, BenchmarkCase benchmarkCase, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver, IConfig config)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunner.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ReadOnlyConfig config, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at dotNetTips.CodePerf.Example.App.Program.Main() in S:\src\VSTS\Rock Your Code - Perf and App Performance\dotNetTips.CodePerf.Example.App\dotNetTips.CodePerf.Example.App\Program.cs:line 47

Inner Exception 1:
XmlException: Root element is missing.

**Comment by adamsitnik** [comment]
Hi @RealDotNetDave 

how can I reproduce this issue? could you provide a repro?

**Comment by adamsitnik** [comment]
@RealDotNetDave ping

**Comment by RealDotNetDave** [comment]
I'm still having an issue. Cleaning up code now since Microsoft wants to see it too.

**Comment by YohDeadfall** [comment]
Looks like to reproduce the problem you should get an exception in the diagnoser, so no data will be written to the temporary file. @adamsitnik, could you provide me instructions on how to debug BenchmarkDotNet itself using modified source code?

**Comment by adamsitnik** [comment]
> could you provide me instructions on how to debug BenchmarkDotNet itself using modified source code?

@YohDeadfall Sure! https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/contributing/disassembler.md (but the doc has not been updated for a long time, so you might need to remove|reorder some of the arguments)

**Comment by YohDeadfall** [comment]
Opened #1673 which was a reason in mine case. The fix will be soon.
