### ISSUE TITLE
NullReferenceException in BenchmarkDotNet.Reports.SummaryTable after iteration failure

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/BenchmarkDotNet#1046]
## BDN Version
`Benchmarks 0.1.1-preview2-190203-1`

## Repro 
```c#
using System;
using Microsoft.Collections.Extensions.Benchmarks;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace Foo
{
    [WarmupCount(0)]
    [IterationCount(1)]
    [InvocationCount(1)]
    public class Bar
    {
        [Benchmark(Baseline = true)]
        public void Bar1() {}
        [Benchmark]
        public void Bar2() => throw new Exception();
    }

        public static void Main(string[] args)
            => BenchmarkRunner.Run(typeof(Foo));
}
```
## Expected
Not to crash

## Actual
After the callstack for the test failure,
```
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Mathematics.Statistics.Divide(Statistics x, Statistics y)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.GetRatioStatistics(Statistics current, Statistics baseline)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.<>c__DisplayClass12_0.<IsNonBaselinesPrecise>b__0(BenchmarkCase x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.IsNonBaselinesPrecise(Summary summary, Statistics baselineStat, BenchmarkCase benchmarkCase)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase, Statistics baseline, Statistics current, Boolean isBaseline)
   at BenchmarkDotNet.Columns.BaselineCustomColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase)
   at BenchmarkDotNet.Columns.BaselineCustomColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase, ISummaryStyle style)
   at BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass33_2.<.ctor>b__9(IColumn c)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass33_1.<.ctor>b__4(BenchmarkReport r)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary.GetTable(ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at Benchmarks.Program.Main(String[] args) in /home/dan/git/corefxlab/tests/Benchmarks/Program.cs:line 16
```

**Comment by danmosemsft** [comment]
Same callstack as in https://github.com/dotnet/BenchmarkDotNet/issues/953 but that issue seems to be focused on what led to the problem. I opened this issue because perhaps the report generation should protect itself against upstream failure.

**Comment by adamsitnik** [comment]
It looks that I have fixed this bug in my big refactor form last week #912

Anyway, I added tests to make sure it never comes back.

@danmosemsft big thanks for  great bug reports!

**Comment by danmosemsft** [comment]
Thanks @adamsitnik!
