### ISSUE TITLE
Running the example throws NullReference

### ISSUE THREAD

**Issue by j-dc** [dotnet/BenchmarkDotNet#1049]
I ran the example shown in the quickstart on beckmarkdotnet.org. And it throws a nullreference exception :'(  

My  code:
```
using System;
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace MyBenchmarks {
    [ClrJob(baseline: true), CoreJob, MonoJob, CoreRtJob]
    [RPlotExporter, RankColumn]
    public class Md5VsSha256 {
        private SHA256 sha256 = SHA256.Create();
        private MD5 md5 = MD5.Create();
        private byte[] data;

        [Params(1000, 10000)]
        public int N;

        [GlobalSetup]
        public void Setup() {
            data = new byte[N];
            new Random(42).NextBytes(data);
        }

        [Benchmark]
        public byte[] Sha256() => sha256.ComputeHash(data);

        [Benchmark]
        public byte[] Md5() => md5.ComputeHash(data);
    }

    public class Program {
        public static void Main(string[] args) {
            var summary = BenchmarkRunner.Run<Md5VsSha256>();
        }
    }
}
```

The exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=BenchmarkDotNet
  StackTrace:
   at BenchmarkDotNet.Mathematics.Statistics.Divide(Statistics x, Statistics y)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.GetRatioStatistics(Statistics current, Statistics baseline)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.<>c__DisplayClass12_0.<IsNonBaselinesPrecise>b__0(BenchmarkCase x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.IsNonBaselinesPrecise(Summary summary, Statistics baselineStat, BenchmarkCase benchmarkCase)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase, Statistics baseline, Statistics current, Boolean isBaseline)
   at BenchmarkDotNet.Columns.BaselineCustomColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase)
   at BenchmarkDotNet.Columns.BaselineCustomColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase, ISummaryStyle style)
   at BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass33_2.<.ctor>b__9(IColumn c)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass33_1.<.ctor>b__4(BenchmarkReport r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at MyBenchmarks.Program.Main(String[] args)
```
Bechmarkdotnet version: 0.11.3
.net framework 4.6.2

**Comment by adamsitnik** [comment]
Hi @j-dc 

Thank you for the bug report. This is a duplicate of #1046 which has been solved in #912 and will be published to NuGet.org as part of 0.11.4 this week.
