### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element after 0.11.4

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/BenchmarkDotNet#1070]
Using 0.11.4, benchmarks fail after they have completed running for this small sample application https://github.com/stevejgordon/BenchmarkAndSpanExample. Switching back to 0.11.3 these benchmarks seem to run without an issue.

In fact the error only occurs if I include the Orderer attribute:

[Orderer(SummaryOrderPolicy.FastestToSlowest)]

```
// AfterAll

Mean = 22.3183 ns, StdErr = 0.1006 ns (0.45%); N = 15, StdDev = 0.3894 ns
Min = 21.9206 ns, Q1 = 22.0534 ns, Median = 22.1235 ns, Q3 = 22.7455 ns, Max = 23.0723 ns
IQR = 0.6922 ns, LowerFence = 21.0151 ns, UpperFence = 23.7838 ns
ConfidenceInterval = [21.9020 ns; 22.7346 ns] (CI 99.9%), Margin = 0.4163 ns (1.87% of Mean)
Skewness = 0.88, Kurtosis = 2.12, MValue = 2

Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Reports.Summary.GetConfiguredOrdererOrDefaultOne(IEnumerable`1 configs)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, ImmutableArray`1 reports, HostEnvironmentInfo hostEnvironmentInfo, String resultsDirectoryPath, TimeSpan totalTime, ImmutableArray`1 validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at BenchmarkAndSpanExample.Program.Main(String[] args) in C:\Projects\Other\BenchmarkAndSpanExample\BenchmarkAndSpanExample\Program.cs:line 10

**Comment by rikimaru0345** [comment]
I just came here to report the exact same thing! :smile: 

```
class CerasGlobalBenchmarkConfig : ManualConfig
{
	public CerasGlobalBenchmarkConfig()
	{
		Orderer = new DefaultOrderer(SummaryOrderPolicy.FastestToSlowest);

...
```

There is no more Set() method now, so I was setting the orderer that way, I hope thats correct.

**Comment by AndreyAkinshin** [comment]
@stevejgordon, @rikimaru0345 thanks for the report!

**Comment by rikimaru0345** [comment]
Are there any estimates when 11.5 will be released? Should we downgrade to 11.4 in the meantime?

**Comment by AndreyAkinshin** [comment]
@rikimaru0345,

> Are there any estimates when 11.5 will be released?

I want to release it soon, but I don't have any estimates for now.
Meanwhile, you can use 0.11.4.1015 from our [nightly feed](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly) (it should be available as soon as [this build](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/22453568) is finished).

**Comment by juniormayhe** [comment]
Just updated to 0.11.5. Ordering tests are working fine and _Sequence contains..._ message is gone
```
[RankColumn]
[Orderer(SummaryOrderPolicy.FastestToSlowest, MethodOrderPolicy.Declared)]
[MemoryDiagnoser]
public class YourBenchmarkClass { ... }
```
![](https://media.giphy.com/media/RboT0ZctPyjMk/giphy.gif)
