### ISSUE TITLE
Crash when BenchmarkDotNet.Diagnostics.Windows.Session.GetFilePath throws NRE

### ISSUE THREAD

**Issue by AArnott** [dotnet/BenchmarkDotNet#1156]
### Repro

```
git clone https://github.com/aarnott/vs-streamjsonrpc.git
cd vs-streamjsonrpc\src
git checkout benchmarks
cd Benchmarks
dotnet run -f netcoreapp2.2 -c release -- --runtimes clr core --filter *Invoke* -p etw
```

### Results

```
PS D:\git\streamjsonrpc\src\Benchmarks> dotnet run -f netcoreapp2.2 -c release -- --runtimes clr core --filter *Invoke* -p etw
D:\git\streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj(60,5): warning : StreamJsonRpc.csproj is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensure that toolkit is properly installed.
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 2 benchmark(s) in total *****
// ***** Building 2 exe(s) in Parallel: Start   *****
// ***** Done, took 00:00:52 (52.47 sec)   *****
// Found 2 benchmarks:
//   InvokeBenchmarks.InvokeAsync_NoArgs: Job-EGKSHN(Runtime=Clr)
//   InvokeBenchmarks.InvokeAsync_NoArgs: Job-YZVARH(Runtime=Core, Toolchain=.NET Core 2.2)

// **************************
// Benchmark: InvokeBenchmarks.InvokeAsync_NoArgs: Job-EGKSHN(Runtime=Clr)
// *** Execute ***
// Launch: 1 / 1

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Diagnostics.Windows.Session.GetFilePath(DiagnoserActionParameters details, DateTime creationTime)
   at BenchmarkDotNet.Diagnostics.Windows.Session..ctor(String sessionName, DiagnoserActionParameters details, EtwProfilerConfig config, DateTime creationTime)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at Benchmarks.Program.Main(String[] args) in D:\git\streamjsonrpc\src\Benchmarks\Program.cs:line 14
PS D:\git\streamjsonrpc\src\Benchmarks>
```

**Comment by adamsitnik** [comment]
Hi @AArnott 

I am able to reproduce it. I am going to fix it, for now you can workaround it by providing full tfms to the runtime switch.

```cmd
--runtimes net472 netcoreapp2.2
```

Instead of

```cmd
--runtimes clr core
```
