### ISSUE TITLE
LatestCoreRtVersionIsSupported fails on Mac Os

### ISSUE THREAD

**Issue by wojtpl2** [dotnet/BenchmarkDotNet#1195]
`LatestCoreRtVersionIsSupported` test doesn't work on Mac OS.

There is a link to build https://travis-ci.org/dotnet/BenchmarkDotNet/jobs/552834005

This test uses the new version of Core RT:
https://github.com/dotnet/BenchmarkDotNet/blob/0b83c934e5f983ff2aa43c82e63d242216d330bf/tests/BenchmarkDotNet.IntegrationTests/CoreRtTests.cs#L27

Error occurs from the `1.0.0-alpha-27901-01` version of `microsoft.dotnet.ilcompiler`.

I think this is a mistake rather in CoreRT or something in BDN requires changes.

```
[xUnit.net 00:10:23.07] BenchmarkDotNet.IntegrationTests: [Long Running Test] 'LatestCoreRtVersionIsSupported', Elapsed: 00:01:03
[xUnit.net 00:10:35.61]     LatestCoreRtVersionIsSupported [FAIL]
Failed   LatestCoreRtVersionIsSupported
Error Message:
 The following benchmarks are failed to build: CoreRtBenchmark.Check: Dry(Runtime=CoreRT, Toolchain=Core RT 1.0.0-alpha-*, IterationCount=1, LaunchCount=1, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=1)
Expected: True
Actual:   False
Stack Trace:
   at BenchmarkDotNet.IntegrationTests.BenchmarkTestExecutor.CanExecute(Type type, IConfig config, Boolean fullValidation) in /Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/BenchmarkTestExecutor.cs:line 71
   at BenchmarkDotNet.IntegrationTests.CoreRtTests.LatestCoreRtVersionIsSupported() in /Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/CoreRtTests.cs:line 31
Standard Output Messages:
 // Validating benchmarks:
 No exporters defined, results will not be persisted.
 Assembly BenchmarkDotNet.IntegrationTests which defines benchmarks references non-optimized BenchmarkDotNet.IntegrationTests.DisabledOptimizations
 // ***** BenchmarkRunner: Start   *****
 // ***** Found 1 benchmark(s) in total *****
 // ***** Building 1 exe(s) in Parallel: Start   *****
 // start dotnet restore -r osx-x64 /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in /Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6
 // command took 29.87s and exited with 0
 // start dotnet build -c Release -r osx-x64 --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in /Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6
 // command took 12.34s and exited with 0
 // start dotnet publish -c Release -r osx-x64 --no-build --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in /Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6
 // command took 33.86s and exited with 1
 // ***** Done, took 00:01:16 (76.09 sec)   *****
 // Found 1 benchmarks:
 //   CoreRtBenchmark.Check: Dry(Runtime=CoreRT, Toolchain=Core RT 1.0.0-alpha-*, IterationCount=1, LaunchCount=1, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=1)
 
 // Build Error: Standard output: 
   
  Standard error: 
  /Users/travis/.nuget/packages/microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/build/Microsoft.NETCore.Native.targets(338,5): error MSB3073: The command "clang "obj/Release/netcoreapp2.1/osx-x64/native/d10727c8-effe-4827-b18a-4582c4204db6.o" -o "bin/Release/netcoreapp2.1/osx-x64/native/d10727c8-effe-4827-b18a-4582c4204db6" /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/sdk/libbootstrapper.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/sdk/libRuntime.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/sdk/libSystem.Private.CoreLib.Native.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/sdk/libSystem.Private.TypeLoader.Native.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Globalization.Native.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.IO.Compression.Native.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Net.Security.Native.a /Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Security.Cryptography.Native.Apple.a -g -Wl,-rpath,'$ORIGIN' -lstdc++ -ldl -lm -lz -licucore -framework CoreFoundation -framework Security -framework GSS" exited with code 1. [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
   ld: symbol(s) not found for architecture x86_64
         _SystemNative_UTimensat in System.Native.a(pal_time.c.o)
     "_utimensat", referenced from:
         _SystemNative_SysLog in System.Native.a(pal_process.c.o)
     "_syslog$DARWIN_EXTSN", referenced from:
   Undefined symbols for architecture x86_64:
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_string.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_signal.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_datetime.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_runtimeinformation.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_random.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_networking.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_uid.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_time.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_process.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_errno.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_console.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : object file (/Users/travis/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27901-01/framework/System.Native.a(pal_io.c.o)) was built for newer OSX version (10.14) than being linked (10.12) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 ld : warning : can't parse dwarf compilation unit info in obj/Release/netcoreapp2.1/osx-x64/native/d10727c8-effe-4827-b18a-4582c4204db6.o [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
 EXEC : warning : RD.XML processing will change before release (https://github.com/dotnet/corert/issues/5001) [/Users/travis/build/dotnet/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp2.1/d10727c8-effe-4827-b18a-4582c4204db6/BenchmarkDotNet.Autogenerated.csproj]
   Generating native code
   /usr/bin/clang
 Copyright (C) Microsoft Corporation. All rights reserved.
 Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
```

**Comment by adamsitnik** [comment]
@MichalStrehovsky could you help us with this one?

**Comment by MichalStrehovsky** [comment]
```
   ld: symbol(s) not found for architecture x86_64
         _SystemNative_UTimensat in System.Native.a(pal_time.c.o)
     "_utimensat", referenced from:
         _SystemNative_SysLog in System.Native.a(pal_process.c.o)
```

CoreRT is statically linking against System.Native that was built out of the CoreFX repo. Looks like CoreFX built System.Native on macOS with an SDK that has the `utimensat` API ([HAVE_UTIMENSAT](https://github.com/dotnet/corefx/blob/655be420da4094ffed95ffa661a37225a3d7c6c9/src/Native/Unix/System.Native/pal_time.c#L30-L46) is defined on the CoreFX build machine). This API is new as of macOS 10.13. The Travis instance used in the BenchmarkDotNet repo seems to be running on macOS 10.12 that doesn't have this API.

This kind of looks like a general CoreFX problem. System.Native is also used with CoreCLR, albeit it links dynamically. I think macOS 10.12 would hit an issue with CoreCLR too if we were to call into something that uses `utimensat` (`SetLastAccessTime` or something).

I'll open an issue over in the CoreFX repo.

**Comment by adamsitnik** [comment]
@MichalStrehovsky thank you! it would explain why it works fine on Azure DevOps MacOS CI leg

**Comment by wojtpl2** [comment]
@MichalStrehovsky I have more information, `BenchmarkDotNet` uses always latest version of `microsoft.dotnet.ilcompiler`. The last build which was successful on Mac OS was `June 13, 2019 10:56:45`. There is link: https://travis-ci.org/dotnet/BenchmarkDotNet/jobs/545126062
This build probably used 1.0.0-alpha-27812-02 version and this version should be ok. 

HAVE_UTIMENSAT was merged to master 2 Aug 2018. https://github.com/dotnet/corefx/pull/31522/files
That's why I wrote that probably something in CoreRt has changed.

`BenchmarkDotNet` runs test also on 1.0.0-alpha-27408-02 version which is also good . 
https://github.com/dotnet/BenchmarkDotNet/blob/fc8867585f170c1c9d7b08b4d91ac1924f5c835e/tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs#L41-L45

**Comment by wojtpl2** [comment]
Of course, I can be wrong or not be aware of something 😃

**Comment by MichalStrehovsky** [comment]
It was probably a silent update of the SDK on the build machine.

Looks like .Net Core 3.0 requires macOS 10.13+, so this is now an unsupported OS.

**Comment by wojtpl2** [comment]
I created a PR https://github.com/dotnet/BenchmarkDotNet/pull/1196 that upgrade macOS to 10.14 for Travis CI.  We'll see if it helps.

**Comment by wojtpl2** [comment]
After update macOS build passed.

![image](https://user-images.githubusercontent.com/17333903/61079900-2222e180-a424-11e9-9bb2-55db89c43084.png)

**Comment by MichalStrehovsky** [comment]
Thank you Wojciech!
