### ISSUE TITLE
Support benchmarks with very long string arguments

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1247]
This is a bug that I've hit both on Linux and Windows while working on faster `string.StartsWith` for Linux.

Repro:

```cs
public class Repro
{
    public IEnumerable<object> Arguments()
    {
        yield return new string('a', 200_000);
    }

    [Benchmark]
    [ArgumentsSource(nameof(Arguments))]
    public void Test(string value) { }
}
```

Error:

```log
Unhandled Exception: System.ComponentModel.Win32Exception: The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, BenchmarkCase benchmarkCase, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
```

**Comment by badijm** [comment]
@adamsitnik Hi, Adam, I've try to repro this it's OK now.
