### ISSUE TITLE
FileNotFoundException for System.Management

### ISSUE THREAD

**Issue by SteveSyfuhs** [dotnet/BenchmarkDotNet#1303]
I have a .NET Core 3.0 console app running a benchmark. It was working as expected on 0.11.5 but as soon as I upgraded to the latest package (0.12.0) I get this exception on completion:

```
...
Mean = 498.9599 s, StdErr = 1.6656 s (0.33%); N = 13, StdDev = 6.0055 s
Min = 494.4318 s, Q1 = 495.1242 s, Median = 496.7991 s, Q3 = 500.7228 s, Max = 516.4370 s
IQR = 5.5986 s, LowerFence = 486.7263 s, UpperFence = 509.1207 s
ConfidenceInterval = [491.7681 s; 506.1517 s] (CI 99.9%), Margin = 7.1918 s (1.44% of Mean)
Skewness = 1.84, Kurtosis = 5.65, MValue = 2

// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\Benchmark.Kerberos.NET.Stress-report.csv

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at BenchmarkDotNet.Portability.RuntimeInformation.GetVirtualMachineHypervisor()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at BenchmarkDotNet.Environments.HostEnvironmentInfo.ToFormattedString()+MoveNext()
   at BenchmarkDotNet.Exporters.MarkdownExporter.ExportToLog(Summary summary, ILogger logger)
   at BenchmarkDotNet.Exporters.ExporterBase.ExportToFiles(Summary summary, ILogger consoleLogger)
   at BenchmarkDotNet.Exporters.CompositeExporter.<>c__DisplayClass5_0.<ExportToFiles>b__0(IExporter exporter)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.PrintSummary(ILogger logger, ImmutableConfig config, Summary summary)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at Benchmark.Kerberos.NET.Program.Main(String[] args)
```

The code is here: https://github.com/SteveSyfuhs/Kerberos.NET/blob/master/Benchmark.Kerberos.NET/Stress.cs, BUT I have commented out the `[EtwProfiler]` attribute on the Stress class. If you're looking to try this out I recommend reducing the `AuthenticationAttempts` properties to something lower, otherwise it takes a long time to run (though I haven't attempted repro'ing at lower numbers yet).

Please let me know if there's anything I can provide additionally. I've attached the log of the run.

(Note that there's a bunch of test-specific exceptions in the log somewhere in the middle. I'm investigating that, but I believe that's just my own test code hitting an issue and isn't related to this particular exception).

[Benchmark.Kerberos.NET.Stress-20191030-131551.log](https://github.com/dotnet/BenchmarkDotNet/files/3794890/Benchmark.Kerberos.NET.Stress-20191030-131551.log)

**Comment by adamsitnik** [comment]
hello @SteveSyfuhs 

Have you tried running a clean build (all bin and obj folders deleted) after the update?

**Comment by SteveSyfuhs** [comment]
Well, I thought I had. I retried after deleting bin and obj and it worked. 🤦‍♂️ Thanks. Closing.
