### ISSUE TITLE
use of NugetReference[] causes System.MissingMethodException: No parameterless constructor defined for this object.

### ISSUE THREAD

**Issue by maciejw** [dotnet/BenchmarkDotNet#1318]
in case of someone has this problem 

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.Activator.CreateInstance[T]()
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in C:\Users\....\bin\Release\netcoreapp3.0\fafdba2d-0e1a-4665-9b3b-c6ea6892cf1a\fafdba2d-0e1a-4665-9b3b-c6ea6892cf1a.notcs:line 784
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\....\bin\Release\netcoreapp3.0\fafdba2d-0e1a-4665-9b3b-c6ea6892cf1a\fafdba2d-0e1a-4665-9b3b-c6ea6892cf1a.notcs:line 50
```

I got this with this code

```csharp
.WithNuGet(new [] { new NugetReference(...), ....});
```

this fixes it 

```csharp
.WithNuGet(new NuGetReferenceList { new NugetReference(...), ....});
```

**Comment by adamsitnik** [comment]
@maciejw thank you! I've pushed a fix that requires the user to always provide `NuGetReferenceList`, not `IReadOnlyCollection<NuGetReference>`

**Comment by maciejw** [comment]
thanks, great, this way there is no ambiguity
