### ISSUE TITLE
Bug: Benchmark class with Console.WriteLine(1) fails for DisassemblyDiagnoser with 'Sequence contains no matching element'

### ISSUE THREAD

**Issue by speshuric** [dotnet/BenchmarkDotNet#1364]
Minimized repro:
```c#
using System;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Diagnosers;
using BenchmarkDotNet.Running;

namespace repro
{
    [Config(typeof(JustDisassembly))]
    public class IntroDisassembly
    {
        public class JustDisassembly : ManualConfig
        {
            public JustDisassembly()
            {
                Add(Job.Dry.With(Jit.RyuJit).With(Platform.X64).With(CoreRuntime.Core31));
                Add(DisassemblyDiagnoser.Create(new DisassemblyDiagnoserConfig(printAsm: false, printIL: false, printSource:false, printPrologAndEpilog: false, recursiveDepth: 3)));
            }
        }

        [Benchmark]
        public void BitReverse()
        {
            Console.WriteLine(1); // <<==!!!!!!! Problem is here
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<IntroDisassembly>();
        }
    }
}
```

**Expected**: correct output without exceptions
**Actual**: Benchmark fails with stacktraces

```
[[[[ skipped ]]]]
// Benchmark Process Environment Information:
// Runtime=.NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
// GC=Concurrent Workstation
// Job: Dry(Jit=RyuJit, Platform=X64, IterationCount=1, LaunchCount=1, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=1)

// BeforeActualRun
1
WorkloadActual   1: 1 op, 358100.00 ns, 358.1000 us/op

// AfterActualRun
WorkloadResult   1: 1 op, 358100.00 ns, 358.1000 us/op

// AfterAll
Failed to disassemble with following exception:
Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Disassembler.Program.GetMethod(MethodReference methodReference, ClrType declaringType)
   at BenchmarkDotNet.Disassembler.Program.EnqueueAllCallsFromIL(State state, ICollection`1 ilInstructions, Int32 depth)
   at BenchmarkDotNet.Disassembler.Program.DisassembleMethod(MethodInfo methodInfo, State state, Settings settings)
   at BenchmarkDotNet.Disassembler.Program.Disassemble(Settings settings, ClrRuntime runtime, State state)
   at BenchmarkDotNet.Disassembler.Program.Handle(Settings settings)
   at BenchmarkDotNet.Disassembler.Program.Main(String[] args)
Unhandled exception. System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDisassemblyResult.Read9_DisassemblyResult()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at BenchmarkDotNet.Diagnosers.WindowsDisassembler.Disassemble(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.DisassemblyDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at repro.Program.Main(String[] args) in C:\Users\Саша и Аня\source\repos\benchmark1\repro\Program.cs:line 40
// * Artifacts cleanup *

Process finished with exit code -532,462,766.

```

**Additional notes**
- Initial benchmark where issue was found was much more complex, code above is minimized repro
- Issue not reproduced when `recursiveDepth` less than 3
- Issue not reproduced without `1` in `Console.WriteLine(1)`
- BenchmarkDotNet version 0.12.0
- Seems to be highly related to #612 (and less related to #640, #631
- May be caused by unexpected value of `compiled.Length` in lines 406-409 of `BenchmarkDotNet.Disassembler`, but I didn't check it yet

 https://github.com/dotnet/BenchmarkDotNet/blob/5e7f01ddb91f179916661cbc3885052238c27390/src/BenchmarkDotNet.Disassembler.x64/Program.cs#L406-L409

272e4246

**Comment by adamsitnik** [comment]
Hello @speshuric 

Big thanks for a very detailed bug report!

I've recently rewritten the disassembly diagnoser (see #1332 for full details)

I've tested your repo case using the new one and it works fine. You can also give it a try at https://github.com/adamsitnik/TryNewDisassembler  . The output:

<details>

## .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
```assembly
; TryNewDisassembler.Repro.BitReverse()
       nop       dword ptr [rax+rax]
       mov       ecx,1
       mov       rax,offset System.Console.WriteLine(Int32)
       jmp       rax
; Total bytes of code 23
```
```assembly
; System.Console.WriteLine(Int32)
       push      rsi
       sub       rsp,20
       mov       esi,ecx
       call      qword ptr [7FFDB79013A8]
       mov       rcx,rax
       mov       edx,esi
       lea       r11,[7FFDB7901908]
       cmp       [rcx],ecx
       call      qword ptr [7FFDB7901908]
       nop
       add       rsp,20
       pop       rsi
       ret
; Total bytes of code 40
```
```assembly
; System.Console.get_Out()
       push      rdi
       push      rsi
       push      rbp
       push      rbx
       sub       rsp,28
       call      qword ptr [7FFDB79010C8]
       mov       rsi,rax
       lea       rdi,[rsi+10]
       call      qword ptr [7FFDB79010E0]
       mov       rbx,rax
       mov       r9,[rbx+78]
       test      r9,r9
       je        short M02_L01
M02_L00:
       mov       r8,rsi
       mov       rcx,[7FFDB7901B88]
       mov       rdx,rdi
       call      qword ptr [7FFDB7901300]
       nop
       add       rsp,28
       pop       rbx
       pop       rbp
       pop       rsi
       pop       rdi
       ret
M02_L01:
       call      qword ptr [7FFDB79010F8]
       mov       rbp,rax
       mov       rdx,[rbx+58]
       mov       rcx,rbp
       call      qword ptr [7FFDB7901100]
       lea       rcx,[rbx+78]
       mov       rdx,rbp
       call      qword ptr [7FFDB7901020]
       mov       r9,rbp
       jmp       short M02_L00
; Total bytes of code 108
```
```assembly
; System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
       push      rdi
       push      rsi
       push      rbx
       sub       rsp,30
       mov       [rsp+28],rcx
       mov       rsi,rdx
       mov       rdi,r8
       mov       rbx,r9
       mov       rax,[rsi]
       test      rax,rax
       jne       short M03_L00
       call      qword ptr [7FFD614F4B40]
       mov       rcx,rax
       mov       rdx,rsi
       mov       r8,rdi
       mov       r9,rbx
       call      qword ptr [7FFD614F5758]
M03_L00:
       nop
       add       rsp,30
       pop       rbx
       pop       rsi
       pop       rdi
       ret
; Total bytes of code 62
```

</details>

**Comment by AndreyAkinshin** [comment]
@adamsitnik since #1332 is merged, can we close this issue as fixed?

**Comment by adamsitnik** [comment]
@AndreyAkinshin yes!
