### ISSUE TITLE
System.IO.FileNotFoundException with EtwProfiler

### ISSUE THREAD

**Issue by akovac35** [dotnet/BenchmarkDotNet#1431]
Hello,

I am receiving the following exception when running the EtwProfiler profiler in Windows 10 as administrator:

```
System.IO.FileNotFoundException
  HResult=0x8007007B
  Message=The filename, directory name, or volume label syntax is incorrect. (0x8007007B)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at BenchmarkDotNet.Diagnostics.Windows.KernelSession.EnableProviders()
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at com.github.akovac35.AdapterInterceptor.Benchmarks.Program.Main(String[] args) in C:\tmp\AdapterInterceptor\test\com.github.akovac35.AdapterInterceptor.Benchmarks\Program.cs:line 13

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int)
    Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Microsoft.Diagnostics.Tracing.Parsers.KernelTraceEventParser.Keywords, Microsoft.Diagnostics.Tracing.Parsers.KernelTraceEventParser.Keywords)
    BenchmarkDotNet.Diagnostics.Windows.KernelSession.EnableProviders()
    BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(BenchmarkDotNet.Diagnosers.DiagnoserActionParameters)
    BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(BenchmarkDotNet.Engines.HostSignal, BenchmarkDotNet.Diagnosers.DiagnoserActionParameters)
    BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(BenchmarkDotNet.Engines.HostSignal, BenchmarkDotNet.Diagnosers.DiagnoserActionParameters)
    BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet.Running.BenchmarkId, BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Toolchains.ArtifactsPaths, BenchmarkDotNet.Diagnosers.IDiagnoser, string, BenchmarkDotNet.Characteristics.IResolver)
    BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkDotNet.Toolchains.Parameters.ExecuteParameters)
    BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet.Running.BenchmarkId, BenchmarkDotNet.Toolchains.IToolchain, BenchmarkDotNet.Toolchains.Results.BuildResult, BenchmarkDotNet.Characteristics.IResolver, BenchmarkDotNet.Diagnosers.IDiagnoser, ref bool)
    BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet.Running.BenchmarkId, BenchmarkDotNet.Toolchains.IToolchain, BenchmarkDotNet.Toolchains.Results.BuildResult, BenchmarkDotNet.Characteristics.IResolver)
    ...
    [Call Stack Truncated]
```

Benchmark starts a job but after a while it fails, probably just before a new job is started. Would you happen to know what the problem could be?

Problem can be reproduced by executing problem/test/com.github.akovac35.AdapterInterceptor.Benchmarks/```dotnet run -c Release --filter AdapterInterceptor_Invocation_Benchmark```

[problem.zip](https://github.com/dotnet/BenchmarkDotNet/files/4534726/problem.zip)

Using "BenchmarkDotNet.Diagnostics.Windows" Version="0.12.1".

Regards,
Aleksander

**Comment by adamsitnik** [comment]
Hi @akovac35 

Thanks for a good bug report, I was able to reproduce the problem.

The root cause of the bug is that we are using full benchmark name as an ETW session name:

https://github.com/dotnet/BenchmarkDotNet/blob/ccdf229ca82c1f064ee7e43af2d1f10991f247a5/src/BenchmarkDotNet.Diagnostics.Windows/Sessions.cs#L37

And we are hitting some Windows OS limitation (the name is too long)

A very quick and dirty workaround would  be to override the `ToString` method of `UnknowType` class like this:

```cs
public override string ToString() => $"{Name} {Value}";
```

Then it would change the old name:

```
"com.github.akovac35.AdapterInterceptor.Benchmarks.AdapterInterceptor_Invocation_Benchmark.ReturnUnknownType_MethodUsingFiveArgumentsOfUnknownType_Original(a: com.github.akovac35.AdapterInterceptor.Tests.TestTypes.UnknownType, b: com.github.akovac35.AdapterInterceptor.Tests.TestTypes.UnknownType, c: com.github.akovac35.AdapterInterceptor.Tests.TestTypes.UnknownType, d: com.github.akovac35.AdapterInterceptor.Tests.TestTypes.UnknownType, e: com.github.akovac35.AdapterInterceptor.Tests.TestTypes.UnknownType)"
```

To shorter one:

```
"com.github.akovac35.AdapterInterceptor.Benchmarks.AdapterInterceptor_Invocation_Benchmark.ReturnUnknownType_MethodUsingFiveArgumentsOfUnknownType_Original(a:  0, b:  0, c:  0, d:  0, e:  0)"
```


I have a PR that is going to fix it: https://github.com/dotnet/BenchmarkDotNet/pull/1248

**Comment by akovac35** [comment]
Hi, thanks for a quick reply. I tried your suggestion and it worked for a few jobs, but then a different error was received. Were you able to run the benchmark all the way through the end? Removing the profiler solves the issue, so it is not the benchmark itself.

**Comment by akovac35** [comment]
I also with tried #1248, by cloning the branch on my machine, removing existing NuGet reference and adding BenchmarkDotNet projects to AdapterInterceptor - problem was not solved.

```
System.IO.FileNotFoundException
  HResult=0x8007007B
  Message=The filename, directory name, or volume label syntax is incorrect. (0x8007007B)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at BenchmarkDotNet.Diagnostics.Windows.KernelSession.EnableProviders() in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet.Diagnostics.Windows\Sessions.cs:line 77
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(DiagnoserActionParameters parameters) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet.Diagnostics.Windows\EtwProfiler.cs:line 105
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet.Diagnostics.Windows\EtwProfiler.cs:line 67
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Diagnosers\CompositeDiagnoser.cs:line 37
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Toolchains\DotNetCli\DotNetCliExecutor.cs:line 78
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Toolchains\DotNetCli\DotNetCliExecutor.cs:line 38
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:line 488
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:line 455
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:line 332
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:line 151
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:line 76
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkSwitcher.cs:line 120
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config) in D:\tmp\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkSwitcher.cs:line 67
   at com.github.akovac35.AdapterInterceptor.Benchmarks.Program.Main(String[] args) in D:\tmp\AdapterInterceptor\test\com.github.akovac35.AdapterInterceptor.Benchmarks\Program.cs:line 13

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int)
    Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Microsoft.Diagnostics.Tracing.Parsers.KernelTraceEventParser.Keywords, Microsoft.Diagnostics.Tracing.Parsers.KernelTraceEventParser.Keywords)
    BenchmarkDotNet.Diagnostics.Windows.KernelSession.EnableProviders() in Sessions.cs
    BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(BenchmarkDotNet.Diagnosers.DiagnoserActionParameters) in EtwProfiler.cs
    BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(BenchmarkDotNet.Engines.HostSignal, BenchmarkDotNet.Diagnosers.DiagnoserActionParameters) in EtwProfiler.cs
    BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(BenchmarkDotNet.Engines.HostSignal, BenchmarkDotNet.Diagnosers.DiagnoserActionParameters) in CompositeDiagnoser.cs
    BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet.Running.BenchmarkId, BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Toolchains.ArtifactsPaths, BenchmarkDotNet.Diagnosers.IDiagnoser, string, BenchmarkDotNet.Characteristics.IResolver) in DotNetCliExecutor.cs
    BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkDotNet.Toolchains.Parameters.ExecuteParameters) in DotNetCliExecutor.cs
    BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet.Running.BenchmarkId, BenchmarkDotNet.Toolchains.IToolchain, BenchmarkDotNet.Toolchains.Results.BuildResult, BenchmarkDotNet.Characteristics.IResolver, BenchmarkDotNet.Diagnosers.IDiagnoser, ref bool) in BenchmarkRunnerClean.cs
    BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet.Running.BenchmarkId, BenchmarkDotNet.Toolchains.IToolchain, BenchmarkDotNet.Toolchains.Results.BuildResult, BenchmarkDotNet.Characteristics.IResolver) in BenchmarkRunnerClean.cs
    ...
    [Call Stack Truncated]
```
