### ISSUE TITLE
System.MissingMethodException: Method not found: 'Iced.Intel.MasmFormatter.get_MasmOptions()'.

### ISSUE THREAD

**Issue by Symbai** [dotnet/BenchmarkDotNet#1496]
Using nuget package 0.12.1 adding `[DisassemblyDiagnoser]` to my benchmark class I receive the following exception at the end of the benchmark:

```
// ***** BenchmarkRunner: Finish  *****

// * Export *
Unhandled exception. System.MissingMethodException: Method not found: 'Iced.Intel.MasmFormatterOptions Iced.Intel.MasmFormatter.get_MasmOptions()'.
   at BenchmarkDotNet.Diagnosers.DisassemblyDiagnoserConfig.GetFormatterWithSymbolSolver(IReadOnlyDictionary`2 addressToNameMapping)
   at BenchmarkDotNet.Disassemblers.Exporters.DisassemblyPrettifier.Prettify(DisassembledMethod method, DisassemblyResult disassemblyResult, DisassemblyDiagnoserConfig config, String labelPrefix)
   at BenchmarkDotNet.Disassemblers.Exporters.GithubMarkdownDisassemblyExporter.Export(ILogger logger, DisassemblyResult disassemblyResult, DisassemblyDiagnoserConfig config, Boolean quotingCode)
   at BenchmarkDotNet.Disassemblers.Exporters.GithubMarkdownDisassemblyExporter.ExportToLog(Summary summary, ILogger logger)
   at BenchmarkDotNet.Exporters.ExporterBase.ExportToFiles(Summary summary, ILogger consoleLogger)
   at BenchmarkDotNet.Exporters.CompositeExporter.<>c__DisplayClass5_0.<ExportToFiles>b__0(IExporter exporter)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.PrintSummary(ILogger logger, ImmutableConfig config, Summary summary)   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
```

**Comment by adamsitnik** [comment]
are you referencing a newer version of `Iced` than what BDN uses?

**Comment by Symbai** [comment]
Yes the benchmark project uses Iced 1.7. So I cannot use the benchmark until you updated Iced on your end?

**Comment by adamsitnik** [comment]
> So I cannot use the benchmark until you updated Iced on your end?

Yes. You can send a PR to speedup the process.
