### ISSUE TITLE
Exporter approval tests has recently become unstable

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1607]
In https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/36637918 I can see the following stack trace in the logs:

```log
Failed   Exporters(cultureInfoName: "ru-RU")
Error Message:
 System.ArgumentOutOfRangeException : 'count' must be non-negative.
Parameter name: count
Stack Trace:
   at System.String.CtorCharCount(Char c, Int32 count)
   at SimpleJson.SimpleJson.HandleIndent(Int32 change) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 1254
   at SimpleJson.SimpleJson.SerializeArray(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable anArray, StringBuilder builder) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 1115
   at SimpleJson.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 1034
   at SimpleJson.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 1083
   at SimpleJson.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 1021
   at SimpleJson.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 610
   at SimpleJson.SimpleJson.SerializeObject(Object json) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\SimpleJson.cs:line 616
   at BenchmarkDotNet.Exporters.Json.JsonExporterBase.ExportToLog(Summary summary, ILogger logger) in C:\projects\benchmarkdotnet\src\BenchmarkDotNet\Exporters\Json\JsonExporterBase.cs:line 95
   at BenchmarkDotNet.Tests.Exporters.CommonExporterApprovalTests.Exporters(String cultureInfoName) in C:\projects\benchmarkdotnet\tests\BenchmarkDotNet.Tests\Exporters\CommonExporterApprovalTests.cs:line 59
```

I currently don't have the time to investigate it, but my gut feeling tells me that it  can be related to our recent change in handling `double.NaNs` in #1581 (cc @ marcnet80)

**Comment by marcnet80** [comment]
Hello, @adamsitnik, I removed code which resets **IndentationLevel**. After finishing Serialization **IndentationLevel** becomes zero.
Please review PR.
