### ISSUE TITLE
[EtwProfiler] Merge operation failed return code 0x507

### ISSUE THREAD

**Issue by tomersh26** [dotnet/BenchmarkDotNet#1624]
I'm trying to use the ETWProvider, and I'm getting the following exception when the benchmark execution is about to end:

// AfterAll

Unhandled Exception: System.Exception: Merge operation failed return code 0x507
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Stop(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Type type, IConfig config)
   at Program.Main(String[] args) in D:\Azure-Kusto-Service4\Test\Benchmarks\Program.cs:line 67

It doesn't seem to be a case of a too long file name.
The files under BenchmarkDotNet.Artifacts look a bit suspicious. Their name end with two dots in a raw:
CountCharsBenchmark.Proposed-20201228-142020..etl.new
CountCharsBenchmark.Proposed-20201228-142020..etl
CountCharsBenchmark.Proposed-20201228-142020..kernel.etl

Any idea?

**Comment by tomersh26** [comment]
Suddenly it started to work and that exception wasn't thrown anymore.
I tried to undo few recent changes I did, but I can't find what has fixed that exactly.
