### ISSUE TITLE
Unable to run benchmark when `ParamsSource` refers to string with surrogate pairs

### ISSUE THREAD

**Issue by novak-as** [dotnet/BenchmarkDotNet#1703]
BenchmarkDotNet version: `0.12.1`
DotNet version: `5.0.202`
System: `Win10`

Minimal code to reproduce:
```
    public class PerfTests
    {
        [ParamsSource(nameof(StringValues))]
        public string _utf16String { get; set; }

        [Benchmark]
        public void OldBehavior()
        {
            var cnt = _utf16String.Length;
        }

        #region datasource

        public IEnumerable<string> StringValues
        {
            get
            {
                // works
                //var length = 5;

                //doesn't work
                var length = 100;

                var sbSmall = new StringBuilder("a");
                for (int i = 0; i < length; i++)
                    sbSmall.Append("😀");
                yield return sbSmall.ToString();
            }
        }
        #endregion

    }
```

Output:
```
> dotnet run -p bench.csproj -c Release
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 1 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet restore  /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in C:\Users\onovak\source\repos\test\bench\bin\Release\net5.0\51b9dc91-df38-4e56-ba42-5efd15b00c39
// command took 1.69s and exited with 0
// start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in C:\Users\onovak\source\repos\test\bench\bin\Release\net5.0\51b9dc91-df38-4e56-ba42-5efd15b00c39
// command took 2.86s and exited with 0
// ***** Done, took 00:00:04 (4.77 sec)   *****
// Found 1 benchmarks:
//   PerfTests.OldBehavior: DefaultJob [_utf16String=a???(...)???? [201]]

// **************************
// Benchmark: PerfTests.OldBehavior: DefaultJob [_utf16String=a???(...)???? [201]]
// *** Execute ***
// Launch: 1 / 1
Unhandled exception. System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 772 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at BenchmarkDotNet.Loggers.StreamLogger.WriteLine(LogKind logKind, String text)
   at BenchmarkDotNet.Loggers.CompositeLogger.WriteLine(LogKind logKind, String text)
   at BenchmarkDotNet.Loggers.LoggerExtensions.WriteLineInfo(ILogger logger, String text)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at perf.Program.Main(String[] args) in C:\Users\onovak\source\repos\test\bench\Program.cs:line 14
```

`\uD83D` here is a high surrogate character of a `😀` (`\uD83D\uDE00`).

**Comment by adamsitnik** [comment]
Hi @novak-as 

Is there any chance that you could check if it repros with our latest preview version? You can get it from the following CI NuGet feed:

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by novak-as** [comment]
Hi @adamsitnik,

yes, I am able to reproduce it with `0.12.1.1538`:

```
Unhandled exception. System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 898 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at BenchmarkDotNet.Loggers.StreamLogger.WriteLine(LogKind logKind, String text)
...
```

**Comment by novak-as** [comment]
Okey, this looks interesting. I believe that [this](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs#L583) is root of the problem:

```
new StreamWriter(logFilePath, append: false);
```

According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter?view=net-5.0) this ctor `Initializes a new instance of the StreamWriter class for the specified file by using the default encoding and buffer size`, i.e I'm expecting to see `Encoding.UTF8`/`Encoding.Default` here. I DO see that `utf8` was chosen, but it still crushing. On the other hand, specifying `utf8` manually works, i.e both `return new StreamWriter(logFilePath, append: false, Encoding.Default);` or `return new StreamWriter(logFilePath, append: false, Encoding.UTF8);` fix this problem.

**Comment by adamsitnik** [comment]
@novak-as would you like to send a PR with a fix?

You could create a unit test similar to this one:

https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs#L749-L771

**Comment by novak-as** [comment]
@adamsitnik yeap, I will handle it

Actually, I've found that I wasn't totally precise in my previous message. Specifying `UTF-8` manually will force `StreamWriter` to not throw exception on invalid utf8 bytes, thus allowing to bypass surrogate pairs without corruption.
