### ISSUE TITLE
AwaitingTasksShouldNotInterfereAllocationResults is flaky

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#1714]
Sometimes, `AwaitingTasksShouldNotInterfereAllocationResults` fails with the following message:

```
AwaitingTasksShouldNotInterfereAllocationResults(toolchain: InProcessEmitToolchain) [FAIL]
  Failed AwaitingTasksShouldNotInterfereAllocationResults(toolchain: InProcessEmitToolchain) [11 s]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   100952
  Stack Trace:
     at BenchmarkDotNet.IntegrationTests.MemoryDiagnoserTests.AssertAllocations(IToolchain toolchain, Type benchmarkType, Dictionary`2 benchmarksAllocationsValidators) in D:\a\1\s\tests\BenchmarkDotNet.IntegrationTests\MemoryDiagnoserTests.cs:line 261
   at BenchmarkDotNet.IntegrationTests.MemoryDiagnoserTests.AwaitingTasksShouldNotInterfereAllocationResults(IToolchain toolchain) in D:\a\1\s\tests\BenchmarkDotNet.IntegrationTests\MemoryDiagnoserTests.cs:line 150
```

Failed builds on Appveryor:

* https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/39242480/tests
* https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/39260999/tests

Failed builds on Azure:

* https://dev.azure.com/dotnet/BenchmarkDotNet/_build/results?buildId=52447&view=ms.vss-test-web.build-test-results-tab

**Comment by AndreyAkinshin** [comment]
@adamsitnik could you please take a look?
