### ISSUE TITLE
Error when run benchmark

### ISSUE THREAD

**Issue by REASY** [dotnet/BenchmarkDotNet#1731]
### System info
- OS: MacOS BigSur 11.4
- Runtime: .NET Core 3.1.16 (CoreCLR 4.700.21.26205, CoreFX 4.700.21.26205), X64 RyuJIT

### Error
```
// AfterAll
// The benchmarking process did not quit on time, it's going to get force killed now.
Unhandled exception. System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at benchmarks.Program.Main(String[] args) in <redacted>../benchmarks/Program.cs:line 7
```

It seems like that the code under benchmark is slow (or it doesn't free resources on time) which causes waiting more than 250 ms: https://github.com/dotnet/BenchmarkDotNet/blob/75f63272def862bb223a3e3e040760a71d8994d1/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs#L91

**Comment by cgranade** [comment]
I've encountered this as well (example in CI at https://github.com/microsoft/iqsharp/pull/480). Locally, I get the same output about force killing the process, but that completes before the check of the exit code a few lines later:

https://github.com/dotnet/BenchmarkDotNet/blob/75f63272def862bb223a3e3e040760a71d8994d1/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs#L98

In CI, it looks like killing the process tree doesn't complete before the exit code is used, leading to the exception.

**Comment by adamsitnik** [comment]
@REASY @cgranade would any of you be interested in sending a PR that increases the timeout value?

**Comment by cgranade** [comment]
@adamsitnik: Happy to take a stab at that, sure! Would it be reasonable to also guard accessing `process.ExitCode` on `process.HasExited` being true, so as to avoid the above exception in the case that even a longer timeout fails? My thought would be to make `ExecuteResult.ExitCode` an `int?` and set it to `null` if `HasExited` is `false`. Thanks!
