### ISSUE TITLE
Exception when using ParamsSource with (null) objects

### ISSUE THREAD

**Issue by cincuranet** [dotnet/BenchmarkDotNet#1809]
The code fails with `InvalidOperationException`/`NullReferenceException` (see full error below). Using `net5.0` and BDN 0.13.1.

```csharp
public class FooBenchmark
{
	public static IEnumerable<object> Values()
	{
		yield return null;
		yield return ValueTuple.Create(10);
		yield return ValueTuple.Create(10, 20);
		yield return (10, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
	}

	[ParamsSource(nameof(Values))]
	public object O { get; set; }

	[Benchmark]
	public object FooBar()
	{
		return O;
	}
}
```

<details>
<summary>Exception call stack</summary>
<pre><code>
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Parameters.SmartParameter.get_DisplayText()
   at BenchmarkDotNet.Parameters.ParameterInstance.ToDisplayText(CultureInfo cultureInfo, Int32 maxParameterColumnWidth)
   at BenchmarkDotNet.Parameters.ParameterInstance.ToDisplayText()
   at BenchmarkDotNet.Parameters.ParameterInstances.<>c.<get_DisplayInfo>b__15_0(ParameterInstance p)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at BenchmarkDotNet.Parameters.ParameterInstances.get_DisplayInfo()
   at BenchmarkDotNet.Running.BenchmarkCase.get_DisplayInfo()
   at BenchmarkDotNet.Order.DefaultOrderer.BenchmarkComparer.Compare(BenchmarkCase x, BenchmarkCase y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(IComparer`1 comparer)
   at BenchmarkDotNet.Order.DefaultOrderer.GetExecutionOrder(ImmutableArray`1 benchmarkCases)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config, String[] args)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config, String[] args)
</code></pre>
</details>

**Comment by cincuranet** [comment]
Actually same error even when returning array instead of `yield return`.

```csharp
public class CastingBenchmark
{
	public static IEnumerable<object> Values()
	{
		return new object[]
		{
			null,
			ValueTuple.Create(10),
			ValueTuple.Create(10, 20),
			(10, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
		};
	}

	[ParamsSource(nameof(Values))]
	public object O { get; set; }

	[Benchmark]
	public object FooBar()
	{
		return O;
	}
}
```
