### ISSUE TITLE
Github actions ubuntu-latest "Unable to load shared library 'advapi32.dll' or one of its dependencies" when profiling dotnet 5

### ISSUE THREAD

**Issue by Marvin-Brouwer** [dotnet/BenchmarkDotNet#1857]
I have a GitHub Actions pipeline running pre-compiled binaries on the `ubuntu-latest` runner.
The job looks as follows:
```yml
profile:

    runs-on: ubuntu-latest
    needs: build

    steps:
    ###
    # Checkout repository
    ###
    - name: Checkout repository
      uses: actions/checkout@v2
    ###
    # 🧰 Setup .Net
    #
    # Configure the pipeline to use the correct .Net sdk versions
    ###
    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  | 
          3.1.x
          5.0.x
    ###
    # 🗃 Restore dependencies
    #
    # Fill the NuGet store with necessary libraries
    ###
    - name: 🗃 Restore dependencies
      run: dotnet restore
    ###
    # 🗃 Restore 'library-binaries'
    ###
    - name: 🗃 Restore 'library-binaries'
      uses: actions/download-artifact@v2
      with:
        name: library-binaries
        path: ./src
    ###
    # 🗃 Restore 'profiling-binaries'
    ###
    - name: 🗃 Restore 'profiling-binaries'
      uses: actions/download-artifact@v2
      with:
        name: profiling-binaries
        path: ./src  
    ###
    # ⏱ Profile 1
    ###
    - name: ⏱ Profile 1
      run: |-
        sudo chmod +rwx ./Project.Namespace.One.Profiling
        sudo ./Project.Namespace.One.Profiling
      working-directory: ${{github.workspace}}/src/Project.Namespace.One.Profiling/bin/Release/netcoreapp3.1
    ###
    # ⏱ Profile 2
    ###
    - name: ⏱ Profile 2
      run: |-
        sudo chmod +rwx ./Project.Namespace.Two.Profiling
        sudo ./Project.Namespace.Two.Profiling
      working-directory: ${{github.workspace}}/src/Project.Namespace.Two.Profiling/bin/Release/netcoreapp3.1
    ###
    # 🗃 Publish 'profiling' artifacts
    ###
    - name: 🗃 Publish 'profiling' artifacts
      uses: actions/upload-artifact@v2
      with:
        name: profiling
        path: ./src/Project.Namespace.*.Profiling/bin/Release/netcoreapp3.1/BenchmarkDotNet.Artifacts/results
        retention-days: 1
      if: ${{ always() }}
```
The `./Project.Namespace.Two.Profiling` and `./Project.Namespace.Two.Profiling` are the `dotnet build -c Release` compiled console apps, which are just regular BenchMarkDotNet applications with a preset configuration.

The benchmarkrunner starts off fine, however as soon as it starts the third run of one of the `dotnet5` benchmarks I get the following error:
```text
// Benchmark Process 2761 has exited with code 0.
// Launch: 3 / 3
// Execute: dotnet "4ea6f6f1-f970-4846-bb1f-28711a904083.dll" --benchmarkName "Project.Namespace.Profiling.Profiles.XmlReadProfile.Read(Value: 5.938 MB (500))" --job "BenchmarkDotNet, Version=0.13.1.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4" --benchmarkId 0 in /home/runner/work/Project.Namespace/Project.Namespace/src/Project.Namespace.Profiling/bin/Release/netcoreapp3.1/4ea6f6f1-f970-4846-bb1f-28711a904083/bin/Release/net5.0
// BeforeAnythingElse
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libadvapi32.dll: cannot open shared object file: No such file or directory
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.StartTraceW(UInt64& sessionHandle, String sessionName, EVENT_TRACE_PROPERTIES* properties)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnsureStarted(EVENT_TRACE_PROPERTIES* properties)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(Guid providerGuid, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
   at BenchmarkDotNet.Diagnostics.Windows.EtwDiagnoser`1.EnableProvider()
   at BenchmarkDotNet.Diagnostics.Windows.EtwDiagnoser`1.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.JitDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunAllJoined(IConfig config)
   at Project.Namespace.Core.Profiling.Runner.StaticTestRunner.Run(String[] parameters, Assembly assembly) in /home/runner/work/Project.Namespace/Project.Namespace/src/Project.Namespace.Core.Profiling/Runner/StaticTestRunner.cs:line 73
   at Project.Namespace.Profiling.Program.Main(String[] parameters) in /home/runner/work/Project.Namespace/Project.Namespace/src/Project.Namespace.Profiling/Program.cs:line 17
Unhandled exception. /home/runner/work/_temp/6cf4b5fb-de36-450f-8311-e5a4ad2502e9.sh: line 2:  2049 Aborted                 sudo ./Project.Namespace.Profiling
System.NotSupportedException: Unknown Acknowledgment: 
   at BenchmarkDotNet.Engines.ConsoleHost.SendSignal(HostSignal hostSignal)
   at BenchmarkDotNet.Engines.HostExtensions.BeforeAnythingElse(IHost host)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in /home/runner/work/Project.Namespace/Project.Namespace/src/Project.Namespace.Profiling/bin/Release/netcoreapp3.1/4ea6f6f1-f970-4846-bb1f-28711a904083/4ea6f6f1-f970-4846-bb1f-28711a904083.notcs:line 40
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.Main(String[] args) in /home/runner/work/Project.Namespace/Project.Namespace/src/Project.Namespace.Profiling/bin/Release/netcoreapp3.1/4ea6f6f1-f970-4846-bb1f-28711a904083/4ea6f6f1-f970-4846-bb1f-28711a904083.notcs:line 27
```
The line at `/home/runner/work/Project.Namespace/Project.Namespace/src/Project.Namespace.Core.Profiling/Runner/StaticTestRunner.cs:line 73` is: `BenchmarkSwitcher.FromAssembly(assembly).RunAllJoined(config);`. 

I already did some research on this line: 
"Unable to load shared library 'advapi32.dll' or one of its dependencies." and I found a couple of issues that may seem interesting but are probably unrelated:
- https://github.com/pnp/PnP-PowerShell/issues/2653
- https://developercommunity.visualstudio.com/t/unable-to-load-shared-library-advapi32dll-or-one-o/994437
- https://developercommunity.visualstudio.com/t/publishtestresults-1/988727

It appears to be a Linux specific issue.

What is confusing to me is that this happens on the third run after 2 runs with 3 warmup count and 3 iterations.
The parameter didn't change, it's just another test runt. But something is different.

I hope I've provided you with enough to dive into this. Please let me know if you need more information.

**Comment by mawosoft** [comment]
Looks like you are using a windows-specific Jit diagnoser  (tail call or inlining) which would also explain why it only happens on the last run.

**Comment by Marvin-Brouwer** [comment]
Ah, that must be the inlining one, it's not important for me anyway.
Let me test this.

**Comment by Marvin-Brouwer** [comment]
Yes this seems to have fixed the issue, thanks.

I do have a question and a suggestion though.

**Question:**  
I can imagine something like inlining is a highly os specific thing and might nog even be something linux do. However, I don't really understand why the TailCallDiagnoser is windows specific.  
Is there somewhere where I can read up on this?

**Suggestion:**  
Perhaps it's a good idea to add a property to the diagnosers with a flags enum or a ReadonlyArray of `System.Runtime.InteropServices.OSPlatform`. So the benchmark runner can validate if there are unsupported diagnosers on startup and throw a more human understandable exception?

**Comment by adamsitnik** [comment]
> I can imagine something like inlining is a highly os specific thing and might nog even be something linux do. However, I don't really understand why the TailCallDiagnoser is windows specific.

The Etw, Inlning and TailCall diagnosers are internally using TracEvent to start ETW sessions, which are a Windows-only concept (https://adamsitnik.com/ETW-Profiler/#limitations). This is why they are part of the BenchmarkDotNet.Diagnostics.**Windows** package

Currently the only true cross-platforms diagnosers are MemoryDiagnoser and EventPipeDiagnoser.

@josalem is it possible to get the inlining and tail call events using EventPipe as of today? I mean these ones:

https://github.com/dotnet/BenchmarkDotNet/blob/34817bfdd8909711b4802415808d26849aaed98e/src/BenchmarkDotNet.Diagnostics.Windows/TailCallDiagnoser.cs#L44
https://github.com/dotnet/BenchmarkDotNet/blob/34817bfdd8909711b4802415808d26849aaed98e/src/BenchmarkDotNet.Diagnostics.Windows/InliningDiagnoser.cs#L55

DisassemblyDiagnoser works on both Windows and Linux, but not on macOS (due to lack of ClrMd support for macOS https://github.com/microsoft/clrmd/issues/888)

**Comment by Marvin-Brouwer** [comment]
I see, that's a pity.

I'd still suggest having some checking logic before the profiler starts with a human readable exception.
Perhaps linking to a markdown file in this repo with some more details and links?
