### ISSUE TITLE
how to debug reflection error

### ISSUE THREAD

**Issue by MarshalOfficial** [dotnet/BenchmarkDotNet#1933]
Hi there, I got this error when running my benchmark console application:

```C#
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Unknown Acknowledgment: cknowledgment
   at BenchmarkDotNet.Engines.ConsoleHost.SendSignal(HostSignal hostSignal)
   at BenchmarkDotNet.Engines.HostExtensions.BeforeMainRun(IHost host)
   at BenchmarkDotNet.Engines.Engine.Run()
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in D:\path\path\path\project-name\bin\Release\net5.0\905bb547-33f1-4501-898b-08ad67d64091\905bb547-33f1-4501-898b-08ad67d64091.notcs:line 169
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in D:\path\path\path\project-name\bin\Release\net5.0\905bb547-33f1-4501-898b-08ad67d64091\905bb547-33f1-4501-898b-08ad67d64091.notcs:line 51
```
   
How can I detect the problem?
My code is:
```C#
public class GetAccountBalanceBenchmark
    {
        [Benchmark]
        public async Task RUN() 
        {
            var _ = await Core.Sdk.GetAccountBalance(new SDK.Models.GetAccountBalanceModel { Id = "10", IdType = Codec.IdType.ACCOUNT });            
        }
    }
```

**Comment by adamsitnik** [comment]
Hi @MarshalOfficial 

Is there any chance that your benchmark is printing anything to the console?

Which BDN, .NET and OS versions are you using?

**Comment by adamsitnik** [comment]
@MarshalOfficial Sorry for not making myself clear, is your code (what you are benchmarking, not BenchmarkDotNet itself) printing anything to the console?

Example:

```cs
[GlobalSetup]
public void Print() => Console.WriteLine("Setup!");
```

Which BenchmarkDotNet version are you using?

Are you able to consistently repro this issue?

**Comment by MarshalOfficial** [comment]
> 

@adamsitnik Thank you for following up

Yes, my project itself logs on the console a lot.

BenchmarkDotNet package version was: 0.13.1 Latest Stable

Unfortunately, I was not able to get a benchmark successfully at all, and it gives the same error every time.

**Comment by adamsitnik** [comment]
> Unfortunately, I was not able to get a benchmark successfully at all, and it gives the same error every time.

#2092 should have fixed this error. You can try our preview version from BDN CI feed:

https://benchmarkdotnet.org/articles/guides/nuget.html#nightly
