### ISSUE TITLE
Exception when using System.Text.Json.Nodes.JsonNode

### ISSUE THREAD

**Issue by mwadams** [dotnet/BenchmarkDotNet#2032]
When running a benchmark using v0.13.1 on net6.0, I get an exception when the code-under-inspection attempts to set a property on a JSON node. This is done via code in `JsonPatch.Net` 2.0.2 (available on nuget)

The same benchmark class, when compiled and run in a net60 console app explicitly calling the methods *does not* throw this exception.

The manually-created console application project has been updated to reflect the settings seen in the generated csproj file, to test as close to like-for-like as possible, without the reflection element in the job runner.

If this is not a well-known problem, I can produce a minimal repro project and attach it to this issue.

```
// Benchmark Process Environment Information:
// Runtime=.NET 6.0.5 (6.0.522.21309), X64 RyuJIT
// GC=Concurrent Workstation
// Job: Dry(OutlierMode=RemoveAll, IterationCount=1, LaunchCount=1, RunStrategy=Throughput, UnrollFactor=1, WarmupCount=1)
```

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The node already has a parent.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeAlreadyHasParent()
   at System.Text.Json.Nodes.JsonNode.AssignParent(JsonNode parent)
   at System.Text.Json.Nodes.JsonObject.<>c__DisplayClass9_0.<SetItem>b__0()
   at System.Text.Json.JsonPropertyDictionary`1.SetValue(String propertyName, T value, Action assignParent)
   at System.Text.Json.Nodes.JsonObject.SetItem(String propertyName, JsonNode value)
   at System.Text.Json.Nodes.JsonNode.set_Item(String propertyName, JsonNode value)
   at Json.Patch.AddOperationHandler.Process(PatchContext context, PatchOperation operation)
   at Json.Patch.JsonPatch.Apply(JsonNode source)
   at Benchmarks.GeneratedBenchmark0.PatchJsonEverything() in C:\Users\matth\source\repos\Corvus.JsonSchema\Solutions\Corvus.JsonPatch.Benchmarking\Benchmarks\Generated\GeneratedBenchmark0.cs:line 50
   at BenchmarkDotNet.Autogenerated.Runnable_1.WorkloadActionUnroll(Int64 invokeCount) in C:\Users\matth\source\repos\Corvus.JsonSchema\Solutions\Corvus.JsonPatch.Benchmarking\bin\Release\net6.0\bda76d8b-1bc5-4df5-8893-94a55f871a58\bda76d8b-1bc5-4df5-8893-94a55f871a58.notcs:line 1279
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EnginePilotStage.RunAuto()
   at BenchmarkDotNet.Engines.EnginePilotStage.Run()
   at BenchmarkDotNet.Engines.Engine.Run()
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in C:\Users\matth\source\repos\Corvus.JsonSchema\Solutions\Corvus.JsonPatch.Benchmarking\bin\Release\net6.0\bda76d8b-1bc5-4df5-8893-94a55f871a58\bda76d8b-1bc5-4df5-8893-94a55f871a58.notcs:line 766
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\matth\source\repos\Corvus.JsonSchema\Solutions\Corvus.JsonPatch.Benchmarking\bin\Release\net6.0\bda76d8b-1bc5-4df5-8893-94a55f871a58\bda76d8b-1bc5-4df5-8893-94a55f871a58.notcs:line 54
```
Automatically created csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <AssemblyTitle>4697048a-e3d0-4620-a8af-39b655eb70e0</AssemblyTitle>
    <TargetFramework>net6.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>4697048a-e3d0-4620-a8af-39b655eb70e0</AssemblyName>
    <OutputType>Exe</OutputType>
    <OutputPath>bin\Release</OutputPath>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <UseSharedCompilation>false</UseSharedCompilation>
    <CodeAnalysisRuleSet></CodeAnalysisRuleSet>
    <Deterministic>true</Deterministic>
    <!-- needed for custom build configurations (only "Release" builds are optimized by default) -->
    <Optimize Condition=" '$(Configuration)' != 'Debug' ">true</Optimize>
    
    <!-- we set LangVersion after  which might contain LangVersion copied from the benchmarks project -->
    <LangVersion Condition="'$(LangVersion)' == '' Or ($([System.Char]::IsDigit('$(LangVersion)', 0)) And '$(LangVersion)' &lt; '7.3')">latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="4697048a-e3d0-4620-a8af-39b655eb70e0.notcs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include=".[..snipped...]Corvus.JsonSchema\Solutions\Corvus.JsonPatch.Benchmarking\Corvus.JsonPatch.Benchmarking.csproj" />
  </ItemGroup>
  <PropertyGroup>
<ServerGarbageCollection>false</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
</PropertyGroup>


</Project>

```

Manually created csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
		<ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
		<TargetFramework>net6.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PlatformTarget>x64</PlatformTarget>
		<OutputType>Exe</OutputType>
		<OutputPath>bin\Release</OutputPath>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<DebugType>pdbonly</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<UseSharedCompilation>false</UseSharedCompilation>
		<CodeAnalysisRuleSet></CodeAnalysisRuleSet>
		<Deterministic>true</Deterministic>
		<!-- needed for custom build configurations (only "Release" builds are optimized by default) -->
		<Optimize Condition=" '$(Configuration)' != 'Debug' ">true</Optimize>

		<!-- we set LangVersion after  which might contain LangVersion copied from the benchmarks project -->
		<LangVersion Condition="'$(LangVersion)' == '' Or ($([System.Char]::IsDigit('$(LangVersion)', 0)) And '$(LangVersion)' &lt; '7.3')">latest</LangVersion>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
	</PropertyGroup>


</Project>
```

**Comment by mawosoft** [comment]
Keep in mind that the benchmark method is called multiple times. Most likely (I only took a quick look), the second call operates on a node already modified by the first call.

**Comment by AndreyAkinshin** [comment]
> Keep in mind that the benchmark method is called multiple times. Most likely (I only took a quick look), the second call operates on a node already modified by the first call.

I believe it's the right guess. BenchmarkDotNet assumes that all the benchmark methods don't have any side effects. If this guess is correct, the problem could be workaround using one of the following options:

* Include the initialization logic of your JSON objects to the benchmark method (in this case, BenchmarkDotNet measurements will include the initialization time as well)
* Initialize a new JSON object in `[IterationSetup]` and set `InvocationCount = 1` in the job settings (this approach produces reliable measurements only for benchmarks that take a reasonable about of time, e.g., >1ms)
* Preallocate a list of JSON objects in `[GlobalSetup]` and use the following object from this list in each benchmark invocation

It's hard to provide any other guidance without a stable repro.

**Comment by AndreyAkinshin** [comment]
> What configuration settings makes that reliable (what should the count of the list be)?

It's hard to say in advance because BenchmarkDotNet uses tricky heuristics to determine the optimal number of invocations on the fly based on obtained measurements. I could suggest the following approach:

* Try to guess a sufficient number using the trial and error method (make sure that BenchmarkDotNet correctly perform all the measurements without any exceptions).
* Check you the obtained number of invocations and jit/warmup/target iterations. Fix them using the Job settings.
* Adjust the number of pre-allocated objects according to the obtained settings.

It's not an elegant solution, but it would provide a stable set of benchmarks.
