### ISSUE TITLE
COMException when generating ETW Log for benchmark

### ISSUE THREAD

**Issue by rbanks54** [dotnet/BenchmarkDotNet#2139]
Just posting this here for visibility as it's the same problem as microsoft/perfview#1723. 

I'm seeing COMExceptions when trying to generate an ETW trace for a benchmark.

The exception is
```
Unhandled exception. System.Runtime.InteropServices.COMException (0x800700AA): The requested resource is in use. (0x800700AA)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at BenchmarkDotNet.Diagnostics.Windows.KernelSession.EnableProviders()
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
```

**Comment by adamsitnik** [comment]
Hi @rbanks54 

In such case we need to wait until https://github.com/microsoft/perfview/issues/1723 gets fixed. In the meantime, you can downgrade to previous version which used older TraceEvent.

**Comment by adamsitnik** [comment]
And thank you for digging in and reporting the issue in PerfView repo!

**Comment by ladeak** [comment]
It seems the linked https://github.com/microsoft/perfview/issues/1723 issue is resolved. Shall we bump `Microsoft.Diagnostics.Tracing.TraceEvent` dependency once a new release is available from that nuget package?

**Comment by adamsitnik** [comment]
> It seems the linked https://github.com/microsoft/perfview/issues/1723 issue is resolved.

It turned out to be Windows OS bug and has not been solved yet, only the PerfView issue got closed: https://github.com/microsoft/perfview/issues/1723#issuecomment-1272029634

**Comment by rbanks54** [comment]
@ladeak I mentioned in the perfview issue that I could workaround the problem by disabling realtime virus protection. It's (very) obviously not an ideal approach, but it unblocks me. It might be something that works for you as well.

**Comment by ladeak** [comment]
Thank you for the suggestion, I will give it a try.

**Comment by rbanks54** [comment]
@adamsitnik There's some extra details in this thread https://github.com/microsoft/perfview/issues/1726 you might be interested in :)
