### ISSUE TITLE
Notify about TieredCompilation

### ISSUE THREAD

**Issue by YegorStepanov** [dotnet/BenchmarkDotNet#2190]
> Starting with .NET Core 3.0 Tiered compilation is enabled and you won't get the best ASM when running this code In order to check the assembly, you should disable tiered compilation (that will fallback to best tiered model) by setting the environment variable set COMPlus_TieredCompilation=0

1) Add a **hint** to the `DisassemblyDiagnoser` to indicate whether **tiered compilation** is enabled or disabled.
2) Notify the user here:
2.1) site [page](https://benchmarkdotnet.org/articles/configs/diagnosers.html). Use docFX [block](https://github.com/dotnet/BenchmarkDotNet/blob/master/samples/BenchmarkDotNet.Samples/IntroDisassemblyDry.cs) for it
3.1) Add a comment to the [DiagnosticDry](https://github.com/dotnet/BenchmarkDotNet/tree/master/samples/BenchmarkDotNet.Samples) sample, how to disable it.

P.S. How to disable tired compilation:
```C#
BenchmarkRunner.Run<MyBenchmarks>(
    DefaultConfig.Instance
        .AddJob(Job.Dry.WithEnvironmentVariable("COMPlus_TieredCompilation", "0")));
```

#### Maybe it makes sense to add `ConfigOptions.DisableTieredCompilation`?
Does tier-2 compilation equal to "normal compilation" or it has higher optimization?
Does the following sample **always** produce the same asm code?
```C#
[Dry] // tired compilation is disabled
public class C1
{
    [Benchmark] public void M() { ... }
}

// I assume that this benchmark is always called at least 30 times for recompilation with tier-2 optimizations
// Job.Default with enabled tired compilation
public class C2
{
    [Benchmark] public void M() { ... }
}
```

**Comment by devedse** [comment]
I would very much like this feature as well. The way I've currently setup my benchmarks doesn't seem to allow to set Environment variables:
https://github.com/devedse/DeveMazeGeneratorCore/blob/dotnet7/DeveMazeGeneratorCore.Benchmark/MazeBenchmarkJob.cs

However disabling TieredCompilation (with `<TieredCompilationQuickJitForLoops>false</TieredCompilationQuickJitForLoops>` in the csproj file) does improve my performance by about 10%.

**Comment by YegorStepanov** [comment]
Currently, you can create a new attribute by coping the code from `SimpleJobAttribute` to set environment variables.

**Comment by devedse** [comment]
I'm actually trying that as we speak:

```
namespace DeveMazeGeneratorCore.Benchmark
{
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class, AllowMultiple = true)]
    public class DeveJobAttribute : SimpleJobAttribute
    {
        public DeveJobAttribute(int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string id = null, bool baseline = false)
            : base(launchCount, warmupCount, targetCount, invocationCount, id, baseline)
        {
            ConfigureJob();
        }

        public DeveJobAttribute(RunStrategy runStrategy, int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string id = null, bool baseline = false)
            : base(runStrategy, launchCount, warmupCount, targetCount, invocationCount, id, baseline)
        {
            ConfigureJob();
        }

        public DeveJobAttribute(RuntimeMoniker runtimeMoniker, int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string id = null, bool baseline = false)
            : base(runtimeMoniker, launchCount, warmupCount, targetCount, invocationCount, id, baseline)
        {
            ConfigureJob();
        }

        public DeveJobAttribute(RunStrategy runStrategy, RuntimeMoniker runtimeMoniker, int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string id = null, bool baseline = false)
            : base(runStrategy, runtimeMoniker, launchCount, warmupCount, targetCount, invocationCount, id, baseline)
        {
            ConfigureJob();
        }

        private void ConfigureJob()
        {
            var jobs = Config.GetJobs().ToArray();

            Console.WriteLine($"Job count: {jobs.Length}");

            foreach(var job in jobs)
            {
                Console.WriteLine("Setting Job Tiered Compilation");
                job.Environment.SetEnvironmentVariable(new EnvironmentVariable("COMPlus_TieredCompilation", "0"));
            }
        }
    }
}
```

However I ran into this error:
```
Setting Job Tiered Compilation
Unhandled exception. System.InvalidOperationException: The current object Runtime=.NET 6.0 is frozen. Create a copy to modify.
   at BenchmarkDotNet.Characteristics.CharacteristicObject.AssertNotFrozen()
   at BenchmarkDotNet.Characteristics.CharacteristicObject.SetValue(Characteristic characteristic, Object value)
   at BenchmarkDotNet.Characteristics.CharacteristicObject.SetValue[T](Characteristic`1 characteristic, T value)
   at BenchmarkDotNet.Characteristics.Characteristic`1.set_Item(CharacteristicObject obj
```

**Comment by devedse** [comment]
I also tried copying the code but some methods that are being used are actually internal static (e.g. the `GetRuntime` on the moniker).

I rewrote the code as follows (this works):

```
namespace DeveMazeGeneratorCore.Benchmark
{
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class, AllowMultiple = true)]
    public class DeveJobAttribute : JobConfigBaseAttribute
    {
        private const int DefaultValue = -1;

        public DeveJobAttribute(int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string? id = null, bool baseline = false, Jit jit = Jit.Default, Platform platform = Platform.AnyCpu, bool disableTieredCompilation = true)
            : base(CreateJob(id, launchCount, warmupCount, targetCount, invocationCount, null, baseline, jit, platform, disableTieredCompilation))
        {
        }

        public DeveJobAttribute(RunStrategy runStrategy, int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string? id = null, bool baseline = false, Jit jit = Jit.Default, Platform platform = Platform.AnyCpu, bool disableTieredCompilation = true)
            : base(CreateJob(id, launchCount, warmupCount, targetCount, invocationCount, runStrategy, baseline, jit, platform, disableTieredCompilation))
        {
        }

        public DeveJobAttribute(RuntimeMoniker runtimeMoniker, int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string? id = null, bool baseline = false, Jit jit = Jit.Default, Platform platform = Platform.AnyCpu, bool disableTieredCompilation = true)
            : base(CreateJob(id, launchCount, warmupCount, targetCount, invocationCount, null, baseline, jit, platform, disableTieredCompilation, runtimeMoniker))
        {
        }

        public DeveJobAttribute(RunStrategy runStrategy, RuntimeMoniker runtimeMoniker, int launchCount = -1, int warmupCount = -1, int targetCount = -1, int invocationCount = -1, string? id = null, bool baseline = false, Jit jit = Jit.Default, Platform platform = Platform.AnyCpu, bool disableTieredCompilation = true)
            : base(CreateJob(id, launchCount, warmupCount, targetCount, invocationCount, runStrategy, baseline, jit, platform, disableTieredCompilation, runtimeMoniker))
        {
        }

        private static Job CreateJob(string? id, int launchCount, int warmupCount, int targetCount, int invocationCount, RunStrategy? runStrategy, bool baseline, Jit? jit, Platform? platform, bool disableTieredCompilation, RuntimeMoniker runtimeMoniker = RuntimeMoniker.HostProcess)
        {
            Job job = new Job(id);
            int num = 0;
            if (launchCount != -1)
            {
                job.Run.LaunchCount = launchCount;
                num++;
            }

            if (warmupCount != -1)
            {
                job.Run.WarmupCount = warmupCount;
                num++;
            }

            if (targetCount != -1)
            {
                job.Run.IterationCount = targetCount;
                num++;
            }

            if (invocationCount != -1)
            {
                job.Run.InvocationCount = invocationCount;
                num++;
                int num2 = job.Run.ResolveValue(RunMode.UnrollFactorCharacteristic, EnvironmentResolver.Instance);
                if (invocationCount % num2 != 0)
                {
                    job.Run.UnrollFactor = 1;
                    num++;
                }
            }

            if (runStrategy.HasValue)
            {
                job.Run.RunStrategy = runStrategy.Value;
                num++;
            }

            if (baseline)
            {
                job.Meta.Baseline = true;
            }

            if (disableTieredCompilation)
            {
                job.Environment.SetEnvironmentVariable(new EnvironmentVariable("COMPlus_TieredCompilation", "0"));
            }

            job = GetJob(job, runtimeMoniker, jit, platform);

            return job;
        }
    }
}
```

**Comment by YegorStepanov** [comment]
related issue: https://github.com/dotnet/BenchmarkDotNet/issues/1466
in-depth discussion: https://github.com/dotnet/runtime/issues/13069

`ConfigOptions.DisableTieredCompilation` is not suitable here.

**Comment by YegorStepanov** [comment]
See comments in https://stackoverflow.com/a/61622044 

@AndyAyersMS said that `Tier1 != Tier0+Tier1`

Therefore, `DryJob` cannot always be used to view asm. Okay, then just add information to the documentation about it.

I wonder if there is a guarantee that JIT produces the same asm code on the same machine? For example, an idle PC vs a fully loaded PC. High performance power plan vs power-safer.

**Comment by timcassell** [comment]
The JIT stage now promotes to tier1 by default. Adding env vars to the job is the correct way to configure JIT behavior. https://medium.com/@meriffa/net-core-concepts-tiered-compilation-10f7da3a29c7
