### ISSUE TITLE
Disassembler fails to disassemble some methods on Linux when using recursive mode

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#2223]
[CanDisassembleAllMethodCalls](https://github.com/dotnet/BenchmarkDotNet/blob/61b3c56d94a4f6f014bb58686f2f19f9268f99cb/tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs#L77) test is failing on Linux for both x64 and arm64:

```log
  Failed CanDisassembleAllMethodCalls(jit: RyuJit, platform: Arm64, runtime: .NET 7.0) [22 s]
  Error Message:
   Assert.Contains() Failure
Not found: Benchmark(Int32)
In value:  String[] ["__ForDisassemblyDiagnoser__()"]
  Stack Trace:
     at BenchmarkDotNet.IntegrationTests.DisassemblyDiagnoserTests.AssertDisassembled(DisassemblyDiagnoser diagnoser, String methodSignature) in /home/robox/adsitnik/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs:line 178
   at BenchmarkDotNet.IntegrationTests.DisassemblyDiagnoserTests.CanDisassembleAllMethodCalls(Jit jit, Platform platform, Runtime runtime) in /home/robox/adsitnik/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs:line 92
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

The workaround is to provide an explicit filter for the disassembler via `--disasmFilter`

**Comment by adamsitnik** [comment]
@janvorli is there any chance you could take a look (it seems to be related to .NET 7 runtime changes)? I tried to do my best but got stuck. Here is what I know:

* it works fine with .NET 6, but does not with 7
* it seems that we are unable to translate certain set of calls (near indirect calls?)
* To my suprise it works fine when I attach a debugger to the process!

Good repro case:

```cs
[DisassemblyDiagnoser(printInstructionAddresses: true, syntax: DisassemblySyntax.Masm, maxDepth: 2)]
public class IntroDisassembly
{
    [Benchmark]
    [Arguments(int.MaxValue)]
    public void Benchmark(int someArgument)
    {
        if (someArgument != int.MaxValue)
            throw new InvalidOperationException("Wrong value of the argument!!");

        // we should rather have test per use case
        // but running so many tests for all JITs would take too much time
        // so we have one method that does it all
        Static();
        Instance();
        Recursive();

        Benchmark(true);
    }

    [MethodImpl(MethodImplOptions.NoInlining)] public static void Static() { }

    [MethodImpl(MethodImplOptions.NoInlining)] public void Instance() { }

    [MethodImpl(MethodImplOptions.NoInlining)] // legacy JIT x64 was able to inline this method ;)
    public void Recursive()
    {
        if (new Random(123).Next(0, 10) == 11) // never true, but JIT does not know it
            Recursive();
    }

    [MethodImpl(MethodImplOptions.NoInlining)] public void Benchmark(bool justAnOverload) { } // we need to test overloads (#562)
}
```

**Comment by adamsitnik** [comment]
In the past BDN was asking ClrMD for benchmark type, then the method and using its starting address to disassemble it. But, ClrMD APIs don't support generic types and methods in their APIs so for generic benchmarks it was impossible to get the benchmarked method using ClrMD APIs. So as a workaround, I've added a fake non-generic method `__ForDisassemblyDiagnoser__` that contains a call to the benchmarked method:

https://github.com/dotnet/BenchmarkDotNet/blob/82f03f4d4222dfcf4e19e1f32a47867342a680d1/src/BenchmarkDotNet/Templates/BenchmarkType.txt#L165-L173

It contains a trick: the benchmarked method is never called, as the condition is never true (to not add any overhead). But, thanks to recursive disassembling we were so far able to get the call instruction (from the fake method to the actual benchmark) and get the address of actual benchmark.

@janvorli on my Ubuntu machine the when disassembling the fake `__ForDisassemblyDiagnoser__` method and it's `call` instruction:

1. I am getting address from here:
https://github.com/dotnet/BenchmarkDotNet/blob/82f03f4d4222dfcf4e19e1f32a47867342a680d1/src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs#L120-L121
2. Since `instruction.IsCallNearIndirect` is true, the address is re-read here:
https://github.com/dotnet/BenchmarkDotNet/blob/82f03f4d4222dfcf4e19e1f32a47867342a680d1/src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs#L46
3. Then all the stub related if conditions return false and the address is not modified again: https://github.com/dotnet/BenchmarkDotNet/blob/82f03f4d4222dfcf4e19e1f32a47867342a680d1/src/BenchmarkDotNet/Disassemblers/IntelDisassembler.cs#L54-L80
4. Then `TryTranslateAddressToName`
https://github.com/dotnet/BenchmarkDotNet/blob/82f03f4d4222dfcf4e19e1f32a47867342a680d1/src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs#L242

When I attach a debugger (Rider) it works fine.

**Comment by adamsitnik** [comment]
Repro steps:

```cmd
git clone https://github.com/dotnet/BenchmarkDotNet.git --branch disasmRepro disasmRepro
cd disasmRepro/samples/BenchmarkDotNet.Samples
dotnet run -c Release -f net7.0 --filter '*WithCalls*' --job dry
```

My output:

```log
7F614835CA00 push rbp
7F614835CA01 sub rsp,10h
TryGetReferencedAddress will use GetImmediate(1): 10
7F614835CA05 lea rbp,[rsp+10h]
TryGetReferencedAddress will use MemoryDisplacement64: 10
7F614835CA0A xor eax,eax
7F614835CA0C mov [rbp-0Ch],eax
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF4
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF4 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF4 returned 
7F614835CA0F mov [rbp-8],rdi
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF8
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF8 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF8 returned 
7F614835CA13 mov rdi,[rbp-8]
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF8
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF8 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF8 returned 
7F614835CA17 cmp dword ptr [rdi+3Ch],0Bh
TryGetReferencedAddress will use MemoryDisplacement64: 3C
7F614835CA1B jne short 00007F614835CA34h
TryGetReferencedAddress will use NearBranchTarget: 7F614835CA34
GetMethodByInstructionPointer for IP 7F614835CA34 returned BenchmarkDotNet.Autogenerated.Runnable_0.__ForDisassemblyDiagnoser__()
GetMethodByHandle for IP 7F614835CA34 returned 
7F614835CA1D mov rdi,[rbp-8]
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF8
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF8 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF8 returned 
7F614835CA21 mov edi,[rdi+38h]
TryGetReferencedAddress will use MemoryDisplacement64: 38
7F614835CA24 mov [rbp-0Ch],edi
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF4
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF4 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF4 returned 
7F614835CA27 mov rdi,[rbp-8]
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF8
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF8 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF8 returned 
7F614835CA2B mov esi,[rbp-0Ch]
TryGetReferencedAddress will use MemoryDisplacement64: FFFFFFFFFFFFFFF4
GetMethodByInstructionPointer for IP FFFFFFFFFFFFFFF4 returned 
GetMethodByHandle for IP FFFFFFFFFFFFFFF4 returned 
7F614835CA2E call qword ptr [7F6148709B10h]
TryGetReferencedAddress will use IPRelativeMemoryAddress: 7F6148709B10
ReadPointer returned 7F6148FC2B40 for 7F6148709B10
GetMethodByInstructionPointer for IP 7F6148FC2B40 returned 
GetMethodByHandle for IP 7F6148FC2B40 returned 
7F614835CA34 nop
7F614835CA35 add rsp,10h
TryGetReferencedAddress will use GetImmediate(1): 10
7F614835CA39 pop rbp
7F614835CA3A ret

```

**Comment by adamsitnik** [comment]
@janvorli in my case `GetReadableBytesCount` returns `0` as it does not find any region containing given address

![image](https://user-images.githubusercontent.com/6011991/208707190-77e42617-498d-479a-83b1-05544b3c1a8a.png)

but if I cheat and set the return to 10 anyway then the following sys-call succeeds:

![image](https://user-images.githubusercontent.com/6011991/208707664-cf9e89c1-97b7-4483-8714-ae23142265a0.png)
