### ISSUE TITLE
ppc64le support added in BenchmarkDotNet is not picked in 'performance' repo

### ISSUE THREAD

**Issue by anjiltech** [dotnet/BenchmarkDotNet#2229]
The changes delivered with #2216 are not reflected in the https://github.com/dotnet/performance repo. 

While running the microbenchmarks from within 'performance' repo, it fails as below:

// Validating benchmarks:

Unhandled Exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
at BenchmarkDotNet.Portability.RuntimeInformation.GetCurrentPlatform()
at BenchmarkDotNet.Portability.RuntimeInformation.GetArchitecture()
at BenchmarkDotNet.Environments.BenchmarkEnvironmentInfo..ctor()
at BenchmarkDotNet.Environments.HostEnvironmentInfo..ctor()
at BenchmarkDotNet.Environments.HostEnvironmentInfo.GetCurrent()
at BenchmarkDotNet.Toolchains.Toolchain.Validate(BenchmarkCase benchmarkCase, IResolver resolver)+MoveNext()
at BenchmarkDotNet.Toolchains.Roslyn.RoslynToolchain.Validate(BenchmarkCase benchmarkCase, IResolver resolver)+MoveNext()
at System.Collections.Generic.LargeArrayBuilder1[[BenchmarkDotNet.Validators.ValidationError, BenchmarkDotNet, Version=0.13.2.2009, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].AddRange(IEnumerable1 items)
at System.Collections.Generic.EnumerableHelpers.ToArray[ValidationError](IEnumerable1 source) at System.Linq.Enumerable.ToArray[ValidationError](IEnumerable1 source)
at BenchmarkDotNet.Running.BenchmarkRunnerClean.<>c__DisplayClass12_0.b__2(BenchmarkCase benchmark)
at System.Linq.Enumerable.WhereArrayIterator1[[BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet, Version=0.13.2.2009, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].ToArray() at System.Linq.Enumerable.ToArray[BenchmarkCase](IEnumerable1 source)

Also observed that the BenchmarkDotnet.dll is not built for net7.0 within BenchmarkDotnet repository.

**Comment by adamsitnik** [comment]
Hi @anjiltech 

> The changes delivered with https://github.com/dotnet/BenchmarkDotNet/issues/2216 are not reflected in the https://github.com/dotnet/performance repo.

This is by design. These are two separate repos and usually we update BDN version used by dotnet/performance when we simply need a bug fix or a feature it includes.

I am going to transfer this issue to dotnet/performance.
