### ISSUE TITLE
Running on Android and iOS devices with net6.0

### ISSUE THREAD

**Issue by RcBrgr** [dotnet/BenchmarkDotNet#2242]
Hi there,

with Xamarin it is possible to run Benchmarks directly on the Android or iOS device like also shown in the Xamarin.Forms sample in this repo. Unfortunately that is not possible anymore with dotnet maui with the project targeting net6.0-android and/or net6.0-ios. When running Benchmarks on Android the System.ArgumentOutOfRangeException: "Runtime not supported (Parameter 'runtime')
Actual value was MonoAOTLLVM." will get thrown. Same happens on iOS. Are there any workarounds?

**Comment by adamsitnik** [comment]
Hi @RcBrgr 

Could you please provide a full stack?

BDN is being used in maui repo and I would expect to work fine:

https://github.com/dotnet/maui/blob/main/src/Core/tests/Benchmarks.Droid/MainInstrumentation.cs

**Comment by RcBrgr** [comment]
Hi @adamsitnik, sorry for my late response. First things first providing a custom logger implementation and modifying the config like in the link you have provided, benchmarks are running on the device in a Maui application. However some workarounds are needed like described in the file you have linked.

Coming to the implementation like in the sample for Xamarin Forms. 

```
// BenchmarkComponent.cs
...
IsRunning = true;

            try
            {
                var logger = new AccumulationLogger();
                await Task.Run(() =>
                {
#if DEBUG
                    BenchmarkConfig = new DebugBuildConfig();
#endif
line 57:        var summary = BenchmarkRunner.Run(_benchmarkTypes.FirstOrDefault(t => t.Name == SelectedBenchmarkName), BenchmarkConfig);
                    MarkdownExporter.Console.ExportToLog(summary, logger);
                    ConclusionHelper.Print(
                        logger,
                        summary.BenchmarksCases
                            .SelectMany(benchmark => benchmark.Config.GetCompositeAnalyser().Analyse(summary))
                            .Distinct()
                            .ToList());
                });
                Summary = logger.GetLog();
            }
            catch (Exception exc)
            {
                await Application.Current.MainPage.DisplayAlert("Error", exc.Message, "Ok");
            }
            finally
            {
                IsRunning = false;
            }
```

There is no special config for the Benchmark itself in place or something like that. This is working fine with Xamarin Forms. This is the Stack when running this code in a Maui application:

```
System.ArgumentOutOfRangeException
Runtime not supported (Parameter 'runtime')
Actual value was MonoAOTLLVM.

   at BenchmarkDotNet.Toolchains.ToolchainExtensions.GetToolchain(Runtime runtime, Descriptor descriptor, Boolean preferMsBuildToolchains)
   at BenchmarkDotNet.Toolchains.ToolchainExtensions.GetToolchain(Job job, Descriptor descriptor)
   at BenchmarkDotNet.Toolchains.ToolchainExtensions.GetToolchain(BenchmarkCase benchmarkCase)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.<>c__DisplayClass12_0.<GetSupportedBenchmarks>b__2(BenchmarkCase benchmark)
   at System.Linq.Enumerable.WhereArrayIterator`1[[BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[BenchmarkDotNet.Running.BenchmarkCase, BenchmarkDotNet, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[BenchmarkCase](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[BenchmarkCase](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.<>c__DisplayClass12_0.<GetSupportedBenchmarks>b__0(BenchmarkRunInfo info)
   at System.Linq.Enumerable.SelectArrayIterator`2[[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4],[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1[[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4]].AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[BenchmarkRunInfo](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[BenchmarkRunInfo](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.GetSupportedBenchmarks(BenchmarkRunInfo[] benchmarkRunInfos, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config, String[] args)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass1_0.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Type type, IConfig config, String[] args)
   at BenchmarkMauiTest.BenchmarkComponent.<>c__DisplayClass30_0.<RunBenchmarkCallback>b__0() in /Users/bergere/Projects/BenchmarkMauiTest/BenchmarkMauiTest/BenchmarkComponent.cs:line 57
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

Closed because it is working with the workarounds in the following link:
https://github.com/dotnet/maui/blob/main/src/Core/tests/Benchmarks.Droid/MainInstrumentation.cs

**Comment by adamsitnik** [comment]
> However some workarounds are needed 

Then we should reopen this issue and fix it.

The stack trace that you have provided is very unexpected, as the access to `Console.Title` is guarded with catch block that swallows `PlatformNotSupportedException`:

https://github.com/dotnet/BenchmarkDotNet/blob/0c26996ea685a99068aca71e7ae547b0851d3c64/src/BenchmarkDotNet/Running/ConsoleTitler.cs#L40-L52

@jonathanpeppers is it possible that we can't catch `PlatformNotSupportedException` on Maui? Or that the exception stack points to the Title setter but it's the getter that throws (the call to getter is not catching PNSE)?

**Comment by jonathanpeppers** [comment]
The OP is using .NET 6, but it seems like it should still work:

https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Console/src/System/ConsolePal.Android.cs

You should be able to catch `System.PlatformNotSupportedException`, so I'm not sure why it's not working.

@RcBrgr any different results with .NET 7?

**Comment by RcBrgr** [comment]
@jonathanpeppers with targeting .NET 7 it is working with this code. Thank you very much.

**Comment by themronion** [comment]
Quick question here, is xamarin still supported? Cause i get the same exception when i run the sample

**Comment by jonathanpeppers** [comment]
Xamarin was working for me at one point: https://github.com/jonathanpeppers/BenchmarkDotNet-Android

.NET 6+ and MAUI should for sure work, I believe we have some benchmarks running in a CI pipeline somewhere.

**Comment by themronion** [comment]
Yeap, downgrading helped to launch it on Xamarin

**Comment by jonathanpeppers** [comment]
This project is working in .NET 9:
* https://github.com/dotnet/maui/blob/main/src/Core/tests/Benchmarks.Droid/Benchmarks.Droid.csproj

There might be some hacks in there that make things work, but it's been a while, so not remembering fully.
