### ISSUE TITLE
Incompatible `Microsoft.CodeAnalysis.CSharp` versioning with Razor

### ISSUE THREAD

**Issue by matthid** [dotnet/BenchmarkDotNet#2266]
Because of https://github.com/dotnet/BenchmarkDotNet/issues/2261 we upgraded to latest but our benchmarks broke with:

```
// Build Error: Exception! 
Message: Method not found: 'Void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, Boolean, System.String, System.String, System.String, System.Collections.Generic.IEnumerable`1<System.String>, Micro
soft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String, System.Collections.Immutable.ImmutableArray`1<Byte>, System.Nullable`1<Boolean>, Microsoft.CodeAnalysis.Platform, Microsoft.CodeAnalysis.ReportDiagnostic, Int32
, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>>, Boolean, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceRe
solver, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider, Boolean, Microsoft.CodeAnalysis.MetadataImportOptions, Microsoft.CodeAnalysis.CSharp.NullableCo
ntextOptions)'.,
Stack trace:
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.Build(GenerateResult generateResult, BuildPartition buildPartition, ILogger logger, CancellationToken cancellationToken)
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.Build(GenerateResult generateResult, BuildPartition buildPartition, ILogger logger)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Build(BuildPartition buildPartition, String rootArtifactsFolderPath, ILogger buildLogger)

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in C:\Dev\Q-Bisect\Src\Qplix.Core.CoreBasicQueryPerformance\bin\Release\net48
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
```

In our situation we reference benchmark-dotnet indirectly and because of that `Microsoft.CodeAnalysis.Common` (and therefore `Microsoft.CodeAnalysis.CSharp`) was silently updated to `3.9.0`. For example due to `Microsoft.CodeAnalysis.Razor`.
As a workaround I managed to remove the project reference by removing some benchmarks to follow up on the other issue.

Can we get a release with `CodeAnalysis.Common 3.9.0` or at least one that is compatible with that version (I managed to try with 3.3.1 but that one is already failing).

Best,
 Matthias

**Comment by matthid** [comment]
It is interesting to note that a previous version apparently works fine...
