### ISSUE TITLE
Sample IntroNativeMemory fails to run. Unhandled exception. COMException (0x800700B7): Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by codingdave** [dotnet/BenchmarkDotNet#2270]
Trying to run the IntroNativeMemory I end up with this error:

    // AfterAll
    // Benchmark Process 2372 has exited with code 0
    
    // Run, Diagnostic
    // Execute: dotnet "cfef7ae0-21c5-48d4-9202-c9a4cd627c08.dll" --benchmarkName "Benchmark.IntroNativeMemory.AllocHGlobal" --job "ShortRun" --benchmarkId 0 in E:\Projects\benchmarkIssue\Benchmark\bin\Release\net7.0\cfef7ae0-21c5-48d4-9202-c9a4cd627c08\bin\Release\netcoreapp7.0
    Unhandled exception. System.Runtime.InteropServices.COMException (0x800700B7): Cannot create a file when that file already exists. (0x800700B7)
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
       at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableWindowsHeapProvider(String exeFileName)
       at BenchmarkDotNet.Diagnostics.Windows.HeapSession.EnableProviders()
       at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Diagnostics.Windows.NativeMemoryProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
       at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
       at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
       at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
       at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
       at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
       at Benchmark.Program.Main(String[] args) in E:\Projects\benchmarkIssue\Benchmark\Program.cs:line 11
    
    E:\Projects\benchmarkIssue\Benchmark\bin\Release\net7.0\Benchmark.exe (process 15868) exited with code -1073741819.
    Press any key to close this window . . .
    
I run VS 2022 with admin rights for this [Minimal sample](https://github.com/dotnet/BenchmarkDotNet/files/10743701/BenchmarkIssue.zip)

    # dotnet --version
    7.0.102
    # dotnet --list-sdks
    3.1.426 [C:\Program Files\dotnet\sdk]
    5.0.408 [C:\Program Files\dotnet\sdk]
    5.0.416 [C:\Program Files\dotnet\sdk]
    6.0.202 [C:\Program Files\dotnet\sdk]
    6.0.302 [C:\Program Files\dotnet\sdk]
    6.0.308 [C:\Program Files\dotnet\sdk]
    6.0.405 [C:\Program Files\dotnet\sdk]
    7.0.100 [C:\Program Files\dotnet\sdk]
    7.0.102 [C:\Program Files\dotnet\sdk]
    # dotnet --list-runtimes
    Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

The sample has been created like that:

    # dotnet new -i BenchmarkDotNet.Templates
    Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.
    For more information, run:
       dotnet new install -h
    
    The following template packages will be installed:
       BenchmarkDotNet.Templates
    
    Success: BenchmarkDotNet.Templates::0.13.4 installed the following templates:
    Template Name      Short Name  Language    Tags
    -----------------  ----------  ----------  -----------------
    Benchmark Project  benchmark   [C#],F#,VB  Benchmark/Library
    
    # dotnet new sln
    The template "Solution File" was created successfully.
    
    # dotnet new Benchmark --console-app -o Benchmark
    The template "Benchmark Project" was created successfully.
    
    Processing post-creation actions...
    Restoring E:\Projects\BenchmarkIssue\Benchmark\Benchmark.csproj:
          Determining projects to restore...
    C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive securit
    y updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [E:\Projects\BenchmarkIssue\Benchmark\Benchmark.csproj]
    C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive securit
    y updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [E:\Projects\BenchmarkIssue\Benchmark\Benchmark.csproj]
          Restored E:\Projects\BenchmarkIssue\Benchmark\Benchmark.csproj (in 767 ms).
    Restore succeeded.
    
    # dotnet sln add .\Benchmark\Benchmark.csproj
    Project `Benchmark\Benchmark.csproj` added to the solution.
    
    # cd .\Benchmark\
    # curl -O https://raw.githubusercontent.com/dotnet/BenchmarkDotNet/master/samples/BenchmarkDotNet.Samples/IntroNativeMemory.cs

**Comment by codingdave** [comment]
This is the full dotnet run output:

    # dotnet run --project .\Benchmark\Benchmark.csproj
    // Validating benchmarks:
    // ***** BenchmarkRunner: Start   *****
    // ***** Found 2 benchmark(s) in total *****
    // ***** Building 2 exe(s) in Parallel: Start   *****
    // ***** Done, took 00:00:10 (10.19 sec)   *****
    // Found 2 benchmarks:
    //   IntroNativeMemory.AllocHGlobal: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3)
    //   IntroNativeMemory.AllocHGlobalWithLeaks: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3)
    
    // **************************
    // Benchmark: IntroNativeMemory.AllocHGlobal: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3)
    // *** Execute ***
    // Launch: 1 / 1
    // Execute: dotnet "78fbaa54-bec0-4a0e-86b8-acd186604626.dll" --benchmarkName "Benchmark.IntroNativeMemory.AllocHGlobal" --job "ShortRun" --benchmarkId 0 in E:\Projects\BenchmarkIssue\Benchmark\bin\Release\net7.0\78fbaa54-bec0-4a0e-86b8-acd186604626\bin\Release\netcoreapp7.0
    // BeforeAnythingElse
    
    // Benchmark Process Environment Information:
    // Runtime=.NET Core 7.0.2 (CoreCLR 7.0.222.60605, CoreFX 7.0.222.60605), X64 RyuJIT
    // GC=Concurrent Workstation
    // Job: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3)
    
    OverheadJitting  1: 1 op, 631300.00 ns, 631.3000 us/op
    WorkloadJitting  1: 1 op, 393200.00 ns, 393.2000 us/op
    
    OverheadJitting  2: 16 op, 259100.00 ns, 16.1938 us/op
    WorkloadJitting  2: 16 op, 328000.00 ns, 20.5000 us/op
    
    WorkloadPilot    1: 16 op, 73800.00 ns, 4.6125 us/op
    WorkloadPilot    2: 32 op, 142600.00 ns, 4.4562 us/op
    WorkloadPilot    3: 64 op, 282800.00 ns, 4.4188 us/op
    WorkloadPilot    4: 128 op, 550300.00 ns, 4.2992 us/op
    WorkloadPilot    5: 256 op, 1088200.00 ns, 4.2508 us/op
    WorkloadPilot    6: 512 op, 2176000.00 ns, 4.2500 us/op
    WorkloadPilot    7: 1024 op, 4297700.00 ns, 4.1970 us/op
    WorkloadPilot    8: 2048 op, 8606400.00 ns, 4.2023 us/op
    WorkloadPilot    9: 4096 op, 17499700.00 ns, 4.2724 us/op
    WorkloadPilot   10: 8192 op, 34620400.00 ns, 4.2261 us/op
    WorkloadPilot   11: 16384 op, 73074100.00 ns, 4.4601 us/op
    WorkloadPilot   12: 32768 op, 137549400.00 ns, 4.1977 us/op
    WorkloadPilot   13: 65536 op, 277028700.00 ns, 4.2271 us/op
    WorkloadPilot   14: 131072 op, 553908800.00 ns, 4.2260 us/op
    
    OverheadWarmup   1: 131072 op, 335600.00 ns, 2.5604 ns/op
    OverheadWarmup   2: 131072 op, 3650600.00 ns, 27.8519 ns/op
    OverheadWarmup   3: 131072 op, 319700.00 ns, 2.4391 ns/op
    OverheadWarmup   4: 131072 op, 312900.00 ns, 2.3872 ns/op
    OverheadWarmup   5: 131072 op, 313300.00 ns, 2.3903 ns/op
    OverheadWarmup   6: 131072 op, 313500.00 ns, 2.3918 ns/op
    OverheadWarmup   7: 131072 op, 314400.00 ns, 2.3987 ns/op
    OverheadWarmup   8: 131072 op, 315500.00 ns, 2.4071 ns/op
    OverheadWarmup   9: 131072 op, 314600.00 ns, 2.4002 ns/op
    
    OverheadActual   1: 131072 op, 315200.00 ns, 2.4048 ns/op
    OverheadActual   2: 131072 op, 313700.00 ns, 2.3933 ns/op
    OverheadActual   3: 131072 op, 315300.00 ns, 2.4055 ns/op
    OverheadActual   4: 131072 op, 314400.00 ns, 2.3987 ns/op
    OverheadActual   5: 131072 op, 315600.00 ns, 2.4078 ns/op
    OverheadActual   6: 131072 op, 303100.00 ns, 2.3125 ns/op
    OverheadActual   7: 131072 op, 316000.00 ns, 2.4109 ns/op
    OverheadActual   8: 131072 op, 315500.00 ns, 2.4071 ns/op
    OverheadActual   9: 131072 op, 361900.00 ns, 2.7611 ns/op
    OverheadActual  10: 131072 op, 354000.00 ns, 2.7008 ns/op
    OverheadActual  11: 131072 op, 313500.00 ns, 2.3918 ns/op
    OverheadActual  12: 131072 op, 313000.00 ns, 2.3880 ns/op
    OverheadActual  13: 131072 op, 312900.00 ns, 2.3872 ns/op
    OverheadActual  14: 131072 op, 313300.00 ns, 2.3903 ns/op
    OverheadActual  15: 131072 op, 313300.00 ns, 2.3903 ns/op
    
    WorkloadWarmup   1: 131072 op, 560843700.00 ns, 4.2789 us/op
    WorkloadWarmup   2: 131072 op, 556686500.00 ns, 4.2472 us/op
    WorkloadWarmup   3: 131072 op, 562703000.00 ns, 4.2931 us/op
    
    // BeforeActualRun
    WorkloadActual   1: 131072 op, 563455500.00 ns, 4.2988 us/op
    WorkloadActual   2: 131072 op, 567828000.00 ns, 4.3322 us/op
    WorkloadActual   3: 131072 op, 566176000.00 ns, 4.3196 us/op
    
    // AfterActualRun
    WorkloadResult   1: 131072 op, 563141100.00 ns, 4.2964 us/op
    WorkloadResult   2: 131072 op, 567513600.00 ns, 4.3298 us/op
    WorkloadResult   3: 131072 op, 565861600.00 ns, 4.3172 us/op
    GC:  0 0 0 384 131072
    Threading:  0 0 131072
    
    // AfterAll
    // Benchmark Process 26088 has exited with code 0
    
    // Run, Diagnostic
    // Execute: dotnet "78fbaa54-bec0-4a0e-86b8-acd186604626.dll" --benchmarkName "Benchmark.IntroNativeMemory.AllocHGlobal" --job "ShortRun" --benchmarkId 0 in E:\Projects\BenchmarkIssue\Benchmark\bin\Release\net7.0\78fbaa54-bec0-4a0e-86b8-acd186604626\bin\Release\netcoreapp7.0
    Unhandled exception. System.Runtime.InteropServices.COMException (0x800700B7): Cannot create a file when that file already exists. (0x800700B7)
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
       at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableWindowsHeapProvider(String exeFileName)
       at BenchmarkDotNet.Diagnostics.Windows.HeapSession.EnableProviders()
       at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Start(DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Diagnostics.Windows.NativeMemoryProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
       at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
       at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
       at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
       at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
       at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
       at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
       at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
       at Benchmark.Program.Main(String[] args) in E:\Projects\BenchmarkIssue\Benchmark\Program.cs:line 11

**Comment by AndreyAkinshin** [comment]
@adamsitnik could you please take a look?

**Comment by WojciechNagorski** [comment]
It looks like there was a name collision. The exception contains: "Cannot create a file when that file already exists". 
Can you remove the artifact directory and try again?

**Comment by codingdave** [comment]
Hi,

I cannot reproduce the issue any longer.

Wojciech Nagórski ***@***.***> schrieb am Mo., 6. März 2023,
16:35:

**Comment by AndreyAkinshin** [comment]
Since there is no stable repro and we don't have enough information to investigate the problem, I am closing this issue. @codingdave let us know if you hit the problem again.
