### ISSUE TITLE
Antivirus-related warning

### ISSUE THREAD

**Issue by MaximSelivanoff** [dotnet/BenchmarkDotNet#2293]
When trying to start, the following message appears (I do not have Norton antivirus, defender is disabled. I don't have any antiviruses that work in the background at all)
While yesterday everything worked without such warnings!

// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 2 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet  restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70
// command took 1,29s and exited with 0
// start dotnet  build -c Release --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70
// command took 3,27s and exited with 0
// ***** Done, took 00:00:04 (4.68 sec)   *****
// Found 2 benchmarks:
//   AlgsTest.BubbleTest: DefaultJob [count=1000]
//   AlgsTest.QuickTest: DefaultJob [count=1000]

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// **************************
// Benchmark: AlgsTest.BubbleTest: DefaultJob [count=1000]
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet 70efa304-c6ea-46dd-94d4-247ea3e70f70.dll --anonymousPipes 1332 1296 --benchmarkName "AlgorithmsTest.AlgsTest.BubbleTest(count: 1000)" --job Default --benchmarkId 0 in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\bin\Release\net7.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Array.CopyTo(Array array, Int32 index)
   at AlgorithmsTest.AlgsTest..ctor() in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\AlgsTest.cs:line 19
   at BenchmarkDotNet.Autogenerated.Runnable_0..ctor() in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\70efa304-c6ea-46dd-94d4-247ea3e70f70.notcs:line 190
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\70efa304-c6ea-46dd-94d4-247ea3e70f70.notcs:line 138
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\70efa304-c6ea-46dd-94d4-247ea3e70f70.notcs:line 57
// AfterAll
No Workload Results were obtained from the run.
// Benchmark Process 15572 has exited with code -1.

// ** Remained 1 (50,0 %) benchmark(s) to run. Estimated finish 2023-04-09 21:51 (0h 0m from now) **
Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// **************************
// Benchmark: AlgsTest.QuickTest: DefaultJob [count=1000]
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet 70efa304-c6ea-46dd-94d4-247ea3e70f70.dll --anonymousPipes 1496 1484 --benchmarkName "AlgorithmsTest.AlgsTest.QuickTest(count: 1000)" --job Default --benchmarkId 1 in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\bin\Release\net7.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Array.CopyTo(Array array, Int32 index)
   at AlgorithmsTest.AlgsTest..ctor() in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\AlgsTest.cs:line 19
   at BenchmarkDotNet.Autogenerated.Runnable_1..ctor() in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\70efa304-c6ea-46dd-94d4-247ea3e70f70.notcs:line 390
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\70efa304-c6ea-46dd-94d4-247ea3e70f70.notcs:line 338
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\bin\Release\net7.0\70efa304-c6ea-46dd-94d4-247ea3e70f70\70efa304-c6ea-46dd-94d4-247ea3e70f70.notcs:line 57
// AfterAll
No Workload Results were obtained from the run.
// Benchmark Process 19420 has exited with code -1.

// ** Remained 0 (0,0 %) benchmark(s) to run. Estimated finish 2023-04-09 21:51 (0h 0m from now) **
Successfully reverted power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\AlgorithmsTest.AlgsTest-report.csv
  BenchmarkDotNet.Artifacts\results\AlgorithmsTest.AlgsTest-report-github.md
  BenchmarkDotNet.Artifacts\results\AlgorithmsTest.AlgsTest-report.html

// * Detailed results *
AlgsTest.BubbleTest: DefaultJob [count=1000]
Runtime = ; GC = 
There are not any results runs

AlgsTest.QuickTest: DefaultJob [count=1000]
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1413/22H2/2022Update/SunValley2)
Intel Core i5-9300H CPU 2.40GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.102
  [Host] : .NET 7.0.2 (7.0.222.60605), X64 RyuJIT AVX2

|     Method | count | Mean | Error |
|----------- |------ |-----:|------:|
| BubbleTest |  1000 |   NA |    NA |
|  QuickTest |  1000 |   NA |    NA |

Benchmarks with issues:
  AlgsTest.BubbleTest: DefaultJob [count=1000]
  AlgsTest.QuickTest: DefaultJob [count=1000]

// * Warnings *
Environment
  Summary -> Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:
        - Norton Security Ultra (C:\Program Files\Norton Security\Engine\22.20.1.69\WSCStub.exe)
        - Norton Security Ultra (C:\Program Files\Norton Security\Engine\22.19.8.65\WSCStub.exe)
        - Windows Defender (windowsdefender://)
Use InProcessEmitToolchain or InProcessNoEmitToolchain to avoid new process creation.

// * Legends *
  count : Value of the 'count' parameter
  Mean  : Arithmetic mean of all measurements
  Error : Half of 99.9% confidence interval
  1 ns  : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
Run time: 00:00:00 (0.56 sec), executed benchmarks: 2

Global total time: 00:00:05 (5.59 sec), executed benchmarks: 2
// * Artifacts cleanup *

**Comment by timcassell** [comment]
BDN says the antivirus might be the issue causing the benchmark to fail, because it does not know what the actual cause was. The real issue is in the logs:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentNullException: Value cannot be null. (Parameter 'destinationArray')
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
at System.Array.CopyTo(Array array, Int32 index)
at AlgorithmsTest.AlgsTest..ctor() in C:\Users\PC\source\repos\SortingAlgorithms\AlgorithmsTest\AlgsTest.cs:line 19
```

**Comment by adamsitnik** [comment]
@timcassell thank you!

**Comment by RealDotNetDave** [comment]
I'm getting this issue and only see this in the log:

```
No Workload Results were obtained from the run.
// Benchmark Process 4812 has exited with code -1073741571.
```
