### ISSUE TITLE
Can't use latest version of BenchmarkDotNet

### ISSUE THREAD

**Issue by radical** [dotnet/BenchmarkDotNet#2346]
I tried to use the latest bdn master (dotnet/BenchmarkDotNet@73f8fd1dc49f34b79afa4ef16e0204b1369fdd1a) here, but trying to run benchmarks fails with:

```
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.ValueTuple`3.CompareTo(ValueTuple`3 other)
   at System.ValueTuple`3.System.IComparable.CompareTo(Object other)
   at BenchmarkDotNet.Parameters.ParameterComparer.CompareValues(Object x, Object y)
   at BenchmarkDotNet.Parameters.ParameterComparer.Compare(ParameterInstances x, ParameterInstances y)
   at BenchmarkDotNet.Order.DefaultOrderer.BenchmarkComparer.Compare(BenchmarkCase x, BenchmarkCase y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1 keys, Comparison`1 comparer, Int32 i, Int32 j)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at BenchmarkDotNet.Order.DefaultOrderer.GetExecutionOrder(ImmutableArray`1 benchmarkCases, IEnumerable`1 order)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /Users/ankj/dev/performance/src/benchmarks/micro/Program.cs:line 43
```

This seems to be failing for
```
System.ValueTuple`3[System.Globalization.CultureInfo,System.Globalization.CompareOptions,System.Boolean], (en-US, Ordinal, False)
System.ValueTuple`3[System.Globalization.CultureInfo,System.Globalization.CompareOptions,System.Boolean], (pl-PL, None, False)`
```

.. , because `CultureInfo` does not implement `IComparable`.

IIUC, this is a new code path introduced as part of https://github.com/dotnet/BenchmarkDotNet/pull/2304 .

And it fails for https://github.com/dotnet/performance/blob/dd14c7d44444a0211035af8464b743a55b4dd55e/src/benchmarks/micro/libraries/System.Globalization/StringSearch.cs#L46 .

cc @mrahhal @adamsitnik @LoopedBard3

**Comment by mrahhal** [comment]
Working on this fix. Let me know which of the following two solutions I listed above do you prefer:

1. For `ValueTuple`s, check all inner types if they implement `IComparable` before considering it such
2. For `ValueTuple`s, just skip `IComparable` support and go straight to string comparison

**Comment by timcassell** [comment]
@mrahhal Maybe just catch any exception and fall back to string comparison?

**Comment by mrahhal** [comment]
Could do that, but that might hide other unrelated exceptions we didn't intend to hide. Might be better to properly handle this particular case in my opinion. `ValueTuple` seems to be a special case, `IComparable` doesn't usually throw.

**Comment by cincuranet** [comment]
@mrahhal How is the fix looking? Any ETA? Thanks.

**Comment by mrahhal** [comment]
Was waiting for a reply as I didn't want to work on something and then change it right after a review. And honestly forgot about it while waiting. Ready to roll out a fix when a maintainer confirms one of my two suggestions above..

Or I think I'll just go with whatever I think is better to start with. Will submit a PR soon.

**Comment by timcassell** [comment]
I think if you want to handle `ValueTuple` specially, it's fine. Just be aware that they can have variable number of fields and nested `ValueTuple`s.

**Comment by cincuranet** [comment]
> Just be aware that they can have variable number of types and nested ValueTuples.

Going through `ITuple` might make that easier.

**Comment by mrahhal** [comment]
> Going through `ITuple` might make that easier.

That's an internal interface (and it only has a Size prop, I don't think it helps much anyway).

> Just be aware that they can have variable number of types and nested `ValueTuple`s.

Yes. A simple recursive check will do for nesting. The problem is actually how to detect `ValueTuple`s, since it's a series of (unlimited number of?) structs depending on the number of items. And I don't feel either supporting up to some fixed number or doing something fancy with `Type.FullName` is a good idea.

Starting to think handling exceptions when calling the `IComparable` impl and falling back to `.ToString()` as @timcassell suggested is just the easiest as a start to get the old behavior back. Mayhe this can be handled better in the future, but let's just roll out a fix for now.

**Comment by cincuranet** [comment]
> That's an internal interface (and it only has a Size prop, I don't think it helps much anyway).

It's public interface. And has also indexer.

**Comment by mrahhal** [comment]
> It's public interface. And has also indexer.

I think it's internal in netstandard. But more importantly, isn't `ITuple` for `Tuple`? I don't think it's related to `ValueTuple`.

**Comment by cincuranet** [comment]
Yeah, you need at least `netstandard2.1`. :(

Both `Tuple` and `ValueTuple`.

**Comment by timcassell** [comment]
BDN has a transitive reference to the `System.ValueTuple` nuget package, so you can use the `ITuple` interface. In fact, you should use that interface to check for `Tuple` also, as it also has the same `IComparable` functionality.

```cs
public interface ITuple
{
    int Length { get; }
    object this[int index] { get; }
}
```

**Comment by mrahhal** [comment]
![image](https://github.com/dotnet/BenchmarkDotNet/assets/4404199/bbb42ca8-32bf-47bd-8b11-8795fedd4d59)

Doesn't seem usable in netstandard 2.0.

And yes, `Tuple` has the same problem.

**Comment by timcassell** [comment]
Oh weird, it's not public from the nuget package.

**Comment by mrahhal** [comment]
Would going this far really be worth it here? 😅

I think it's better to just solve it the reliable way for now. Catch the exception and fallback.
