### ISSUE TITLE
Cannot build NativeAOT 8.0 on Arch Linux

### ISSUE THREAD

**Issue by Jisu-Woniu** [dotnet/BenchmarkDotNet#2548]
I wrote a simple benchmark, with NativeAOT enabled:

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<MyBench>();


[SimpleJob(RuntimeMoniker.NativeAot80)]
public class MyBench
{
    [Benchmark]
    public void Bench() { }
}
```

But when I run `dotnet run -c Release`, it fails with:

```plaintext
...
// Build Error: Standard output: 
  
 Standard error: 
 MSBuild version 17.8.5+b5265ef37 for .NET
$HOME/.nuget/packages/microsoft.net.illink.tasks/8.0.3/build/Microsoft.NET.ILLink.targets(210,5): warning : Property 'TrimmerDefaultAction' is deprecated in .NET 7 and higher and will be ignored. Use TrimMode instead. [<PROJECT_DIR>/bin/Release/net8.0/136c2e4d-c592-4318-baf9-67ab64a593fc/BenchmarkDotNet.Autogenerated.csproj]
  Generating native code
EXEC : error : Unrecognized instruction set avx-512f [<PROJECT_DIR>/bin/Release/net8.0/136c2e4d-c592-4318-baf9-67ab64a593fc/BenchmarkDotNet.Autogenerated.csproj]
  System.CommandLine.CommandLineException: Unrecognized instruction set avx-512f
     at System.CommandLine.Helpers.ConfigureInstructionSetSupport(String, Int32, Boolean, TargetArchitecture, TargetOS, String, String, Logger, Boolean) + 0x9d5
     at ILCompiler.Program.Run() + 0x59b
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass227_0.<.ctor>b__0(ParseResult result) + 0x310
$HOME/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.3/build/Microsoft.NETCore.Native.targets(308,5): error MSB3073: The command ""$HOME/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.3/tools/ilc" @"obj/Release/net8.0/linux-x64/native/136c2e4d-c592-4318-baf9-67ab64a593fc.ilc.rsp"" exited with code 1. [<PROJECT_DIR>/bin/Release/net8.0/136c2e4d-c592-4318-baf9-67ab64a593fc/BenchmarkDotNet.Autogenerated.csproj]

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in <PROJECT_DIR>/bin/Release/net8.0/136c2e4d-c592-4318-baf9-67ab64a593fc
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
...
```

My `dotnet --info` output:

```plaintext
.NET SDK:
 Version:           8.0.103
 Commit:            6a90b4b4bc
 Workload version:  8.0.100-manifests.e99a2be4

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.103/

.NET workloads installed:
 Workload version: 8.0.100-manifests.e99a2be4
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  8.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

It was installed from Arch Linux repository.

And my `.csproj` file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>

</Project>
```

**Comment by Jisu-Woniu** [comment]
`avx512f` is supported on my CPU:

```shell
LANG=C lscpu | grep 512
Flags:   ... invpcid avx512f avx512dq rdseed adx smap avx512ifma ...
```

**Comment by adamsitnik** [comment]
Hello @Jisu-Woniu 

Could you please go to `<PROJECT_DIR>/bin/Release/net8.0/136c2e4d-c592-4318-baf9-67ab64a593fc/BenchmarkDotNet.Autogenerated.csproj` and share with us what value was used for the `<IlcInstructionSet>$this</IlcInstructionSet>` element?

It should be just `native` and in theory should just work (https://github.com/dotnet/BenchmarkDotNet/pull/2464). I just need to check if it's BenchmarkDotNet or NativeAOT bug.

**Comment by Jisu-Woniu** [comment]
I build it again and this is the content of `bin/Release/net8.0/f58553a8-0c73-499a-98cc-5ad358f5fe53/BenchmarkDotNet.Autogenerated.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <RuntimeFrameworkVersion></RuntimeFrameworkVersion>
    <AssemblyName>f58553a8-0c73-499a-98cc-5ad358f5fe53</AssemblyName>
    <AssemblyTitle>f58553a8-0c73-499a-98cc-5ad358f5fe53</AssemblyTitle>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugSymbols>false</DebugSymbols>
    <UseSharedCompilation>false</UseSharedCompilation>
    <Deterministic>true</Deterministic>
    <RunAnalyzers>false</RunAnalyzers>
    <PublishAot Condition=" '$(TargetFramework)' != 'net6.0' ">true</PublishAot>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <TrimMode>link</TrimMode><TrimmerDefaultAction>link</TrimmerDefaultAction>
    <IlcGenerateCompleteTypeMetadata>True</IlcGenerateCompleteTypeMetadata>
    <IlcGenerateStackTraceData>True</IlcGenerateStackTraceData>
    <EnsureNETCoreAppRuntime>false</EnsureNETCoreAppRuntime> <!-- workaround for 'This runtime may not be supported by.NET Core.' error -->
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles> <!-- workaround for 'Found multiple publish output files with the same relative path.' error -->
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    <IlcInstructionSet>base,sse,sse2,sse3,ssse3,sse4.1,sse4.2,avx,avx2,avx-512f,avx-512bw,avx-512cd,avx-512dq,avx-512vbmi,aes,bmi,bmi2,fma,lzcnt,pclmul,popcnt</IlcInstructionSet>
  </PropertyGroup>
  <PropertyGroup>
<ServerGarbageCollection>false</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
</PropertyGroup>

  <ItemGroup>
    <Compile Include="f58553a8-0c73-499a-98cc-5ad358f5fe53.notcs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="/home/jswn/DotnetProjects/Bench/Bench.csproj" />
  </ItemGroup>
  <ItemGroup>
    <RdXmlFile Include="bdn_generated.rd.xml" />
  </ItemGroup>
</Project>
```

**Comment by Jisu-Woniu** [comment]
I could set the `IlcInstructionSet` field to `native` using the following code:

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Toolchains.NativeAot;

ManualConfig config = DefaultConfig.Instance.AddJob(
    Job.Default.WithToolchain(
        NativeAotToolchain.CreateBuilder().UseNuGet().IlcInstructionSet("native").ToToolchain()
    )
);

BenchmarkRunner.Run<MyBench>(config);

// Use custom runtime instead of the built-in one:
// [SimpleJob(RuntimeMoniker.NativeAot80)]
public class MyBench
{
    [Benchmark]
    public void Bench() { }
}
```

Generated `.csproj` file:

```xml

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <RuntimeFrameworkVersion></RuntimeFrameworkVersion>
    <AssemblyName>6bb876b0-44dd-4195-9707-766e8b87018a</AssemblyName>
    <AssemblyTitle>6bb876b0-44dd-4195-9707-766e8b87018a</AssemblyTitle>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugSymbols>false</DebugSymbols>
    <UseSharedCompilation>false</UseSharedCompilation>
    <Deterministic>true</Deterministic>
    <RunAnalyzers>false</RunAnalyzers>
    <PublishAot Condition=" '$(TargetFramework)' != 'net6.0' ">true</PublishAot>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <TrimMode>link</TrimMode><TrimmerDefaultAction>link</TrimmerDefaultAction>
    <IlcGenerateCompleteTypeMetadata>True</IlcGenerateCompleteTypeMetadata>
    <IlcGenerateStackTraceData>True</IlcGenerateStackTraceData>
    <EnsureNETCoreAppRuntime>false</EnsureNETCoreAppRuntime> <!-- workaround for 'This runtime may not be supported by.NET Core.' error -->
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles> <!-- workaround for 'Found multiple publish output files with the same relative path.' error -->
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    <IlcInstructionSet>native</IlcInstructionSet>
  </PropertyGroup>
  <PropertyGroup>
<ServerGarbageCollection>false</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
</PropertyGroup>

  <ItemGroup>
    <Compile Include="6bb876b0-44dd-4195-9707-766e8b87018a.notcs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="<PROJECT_DIR>/DotnetProjects/Bench/Bench.csproj" />
  </ItemGroup>
  <ItemGroup>
    <RdXmlFile Include="bdn_generated.rd.xml" />
  </ItemGroup>
</Project>
```

**Comment by adamsitnik** [comment]
> It can compile and produce correct result.

Big thanks for letting me know!

There must be some kind of bug here:

https://github.com/dotnet/BenchmarkDotNet/blob/4ab69be430b74469359d70d4557d2ed039e661ce/src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs#L231-L234

I'll try to fix it after the weekend, I am glad you are unblocked for now.

**Comment by Jisu-Woniu** [comment]
And maybe these should be replaced with `avx512**` too.

https://github.com/dotnet/BenchmarkDotNet/blob/4ab69be430b74469359d70d4557d2ed039e661ce/src%2FBenchmarkDotNet%2FToolchains%2FNativeAot%2FGenerator.cs#L251-L255

**Comment by Treit** [comment]
I am seeing this issue on Windows as well, does not seem to be Linux-specific.

**Comment by eNeRGy164** [comment]
Same issue on my Windows PC after switching from a Intel Core I7 to an AMD Ryzen 5.

**Comment by adamsitnik** [comment]
> Same issue on my Windows PC after switching from a Intel Core I7 to an AMD Ryzen 5.

@eNeRGy164 could you please attach the debugger and see what is happening here:

https://github.com/dotnet/BenchmarkDotNet/blob/4ab69be430b74469359d70d4557d2ed039e661ce/src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs#L231-L234

**Comment by swtrse** [comment]
I have the same Problem on a minimal Project. Actually the GettingStarted Example.
This is whats happening in the GetCurrentProcessInstructionSets-method.
I did flag the Class with `[SimpleJob(RuntimeMoniker.NativeAot80)]`
Platform: X64 TargetFrameworkMoniker: "net8.0" runtimeMoniker: Net80
If I manually set runtimeMoiniker to NativeAot80 the test seams to work.
My guess is that TargetFrameworkMoniker is not set correctly.

**Comment by kg** [comment]
For anyone else hitting this, it seems to be fixed in 0.14

**Comment by Jisu-Woniu** [comment]
I would close this issue since I no longer see this error on v0.14

**Comment by MatthewChudleigh** [comment]
This issue is occurring with Net90, BenchmarkDotNet Version="0.14.0"
- Net90 works fine; NativeAot90 does not
- Running on Windows

> warning : Property 'TrimmerDefaultAction' is deprecated in .NET 7 and higher and will be ignored. Use TrimMode instead

    System.InvalidCastException: Specified cast is not valid.
    at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc) + 0x3eb
    at ILCompiler.CompilerTypeSystemContext.EnsureLoadableType(TypeDesc) + 0x5a
    at ILCompiler.LibraryRootProvider.CheckCanGenerateMethod(MethodDesc) + 0x4c
    at ILCompiler.DependencyAnalysis.TypeMetadataNode.GetStaticDependencies(NodeFactory) + 0x48a
    at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1) + 0x56
    at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1) + 0xc2
    at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() + 0xed
    at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() + 0x49
    at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() + 0x1b
    at ILCompiler.Program.<Run>g__RunScanner|4_0(Program.<>c__DisplayClass4_0&) + 0x1fa
    at ILCompiler.Program.Run() + 0x2906
    at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass240_0.<.ctor>b__0(ParseResult) + 0x321

Using just the code from the <https://benchmarkdotnet.org/articles/guides/getting-started.html>

    [SimpleJob(RuntimeMoniker.Net90)]
    [SimpleJob(RuntimeMoniker.NativeAot90)]
    [RPlotExporter]
    public class Md5VsSha256
    {
        private SHA256 sha256 = SHA256.Create();
        private MD5 md5 = MD5.Create();
        private byte[] data;

        [Params(1000, 10000)]
        public int N;

        [GlobalSetup]
        public void Setup()
        {
            data = new byte[N];
            new Random(42).NextBytes(data);
        }

        [Benchmark]
        public byte[] Sha256() => sha256.ComputeHash(data);

        [Benchmark]
        public byte[] Md5() => md5.ComputeHash(data);
    }

**Comment by eNeRGy164** [comment]
This Cast exception is fixed in the nightly builds, but not released yet.

**Comment by adamsitnik** [comment]
And you can use https://benchmarkdotnet.org/articles/guides/nuget.html?q=nuget#nightly to find out how to get the nightly builds.

**Comment by VAllens** [comment]
> This Cast exception is fixed in the nightly builds, but not released yet.

@eNeRGy164 , @adamsitnik 
I use the nightly build version: `0.14.1-nightly.20250107.205`.
The startup program immediately throws an exception:

```bash
Unhandled exception. System.ArgumentOutOfRangeException: Runtime Moniker not supported (Parameter 'runtimeMoniker')
Actual value was NativeAot90.
   at BenchmarkDotNet.Extensions.RuntimeMonikerExtensions.GetRuntime(RuntimeMoniker runtimeMoniker)
   at BenchmarkDotNet.Attributes.SimpleJobAttribute.CreateJob(String id, Int32 launchCount, Int32 warmupCount, Int32 iterationCount, Int32 invocationCount, Nullable`1 runStrategy, Boolean baseline, RuntimeMoniker runtimeMoniker)
   at BenchmarkDotNet.Attributes.SimpleJobAttribute..ctor(RuntimeMoniker runtimeMoniker, Int32 launchCount, Int32 warmupCount, Int32 iterationCount, Int32 invocationCount, String id, Boolean baseline)
   at System.Reflection.CustomAttribute.CreateCustomAttributeInstance(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetFullTypeConfig(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config, String[] args)
   at BenchmarkDotNet.Running.BenchmarkRunner.<>c__DisplayClass0_0`1.<Run>b__0()
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling(Func`1 run)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config, String[] args)
   at BenchmarksConsoleApp.Program.Main(String[] args) in D:\repo\BenchmarksConsoleApp\BenchmarksConsoleApp\Program.cs:line 12
```

**Comment by timcassell** [comment]
Looks like 9.0 was missed there. Please send a PR for fix.

https://github.com/dotnet/BenchmarkDotNet/blob/e7e758d3b3cb77d5eac1c049a57944198850c8fe/src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs#L58-L61

**Comment by VAllens** [comment]
> Looks like 9.0 was missed there. Please send a PR for fix.
> 
> [BenchmarkDotNet/src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs](https://github.com/dotnet/BenchmarkDotNet/blob/e7e758d3b3cb77d5eac1c049a57944198850c8fe/src/BenchmarkDotNet/Extensions/RuntimeMonikerExtensions.cs#L58-L61)
> 
> Lines 58 to 61 in [e7e758d](/dotnet/BenchmarkDotNet/commit/e7e758d3b3cb77d5eac1c049a57944198850c8fe)
> 
>  case RuntimeMoniker.NativeAot80: 
>      return NativeAotRuntime.Net80; 
>  case RuntimeMoniker.NativeAot10_0: 
>      return NativeAotRuntime.Net10_0;

@timcassell 
Your quick response is so cool, 
I've submitted my PR, thank you so much for your contribution.
