### ISSUE TITLE
[Bug] Weird parsing error when start an executable with System.Diagnostic.Process

### ISSUE THREAD

**Issue by EmyTheBlubery** [dotnet/BenchmarkDotNet#2668]
Hello, I have a really weird behaviour when start an executable located in AppDomain.CurrentDomain.BaseDirectory with System.Diagnostic.Process

Here a little snippet of my code:
```csharp
var process = new Process
{
    StartInfo = new ProcessStartInfo(ExecutableInBaseDirectory, "rhkgndfkhgnfdkj")
};

process .Start();
```

It produces this exception:
```
// BeforeAnythingElse
System.FormatException: The input string 'rhkgndfkhgnfdkj' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\Myuser\Documents\Dev\Libs\MyLib\Benchmark\bin\release\net8.0\c48cf43b-d86c-4c81-be98-0f95d9f48d2e\c48cf43b-d86c-4c81-be98-0f95d9f48d2e.notcs:line 45
```

Anyone has an Idea as to why it's doing that.
Could my .exe by overridden by Benchmarkdotnet?

**Comment by timcassell** [comment]
Looks the same as #2664

**Comment by EmyTheBlubery** [comment]
Yes absolutely thanks
