### ISSUE TITLE
dotnet restore fails on OSX Sierra (osx.10.12-x64) 

### ISSUE THREAD

**Issue by sleemer** [dotnet/BenchmarkDotNet#285]
My environment:
- dotnet core 1.0.0-preview2-003131 (for osx.10.11)
- osx.10.12-x64
- I use your sample app https://perfdotnet.github.io/BenchmarkDotNet/GettingStarted.htm

As far as I can see, Benchmark generates line `"runtimes": { "osx.10.12-x64": { } }` in project.json and uses the current machine's RID for that.
This line cause the error during `dotnet restore` because dotnet core sees unsupported runtime. If I remove this `"runtimes": { "osx.10.12-x64": { } }` line from project.json then I can run `dotnet restore` successfully. To solve this issue I can set DOTNET_RUNTIME_ID=osx.10.11-x64 environment variable, but it seems wired.
Here is a discussion on https://github.com/dotnet/cli/pull/4281 for more details.

**Comment by AndreyAkinshin** [comment]
@sleemer, thank you for the report.

@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment]
Sure! Very interesting bug! I have not foreseen it ;)

I will ask the dotnet cli team what do they recommend. Currently my only idea is to take something like Min(currentRuntimeId, latestSupportedOSVersionByDotNetCli)

**Comment by sleemer** [comment]
Hey guys! Any updates on this issue?

**Comment by adamsitnik** [comment]
Hello @sleemer 

Honestly I am a little bit confused. I [asked the dotnet cli guys](https://github.com/dotnet/cli/pull/4281#issuecomment-255361213) for recommendations but without luck. I am confused because I am not sure what to do now. This problem is rather rare (when  new OS version is shipped and dotnet cli does not handle it yet) and soon people will convert their's xprojs to csprojs again and most probably I will have to develop the Core toolchain once again.

So I am not sure if I should spend time on fixing it now or wait month or two and implement new toolchain :/

What do you think? Are there more people with this problem?

**Comment by AndreyAkinshin** [comment]
I suggest to wait for the new toolchains. It seems that we could drop xprojs soon.

**Comment by sleemer** [comment]
yeah.. @adamsitnik, probably you are right... dotnet is changing so rapidly and it's maybe better to wait for a new toolchain... as a temporary workaround I continue to export environment variable... but after upgrading to "BenchmarkDotNet": "0.10.0"  I started to get another error when benchmark trying to create a report... 

Unhandled Exception: System.PlatformNotSupportedException: Processor affinity for processes or threads is not supported.
   at System.Diagnostics.Process.get_ProcessorAffinityCore()
   at BenchmarkDotNet.Portability.RuntimeInformation.GetCurrentAffinity()
   at BenchmarkDotNet.Characteristics.Resolver.<>c__DisplayClass1_0`1.<Register>b__0()
   at BenchmarkDotNet.Characteristics.Resolver.Resolve(JobMode jobMode, Characteristic characteristic)
   at BenchmarkDotNet.Characteristics.CompositeResolver.Resolve(JobMode jobMode, Characteristic characteristic)
   at BenchmarkDotNet.Columns.CharacteristicColumn.GetValue(Summary summary, Benchmark benchmark)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig c
onfig, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, S
tring rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
   at ConsoleApplication.Md5VsSha256.Main(String[] args) in /Users/thesleemer/Projects/dotnet-benchmarks/src/Crypto/Program.c
s:line 26

**Comment by adamsitnik** [comment]
@sleemer Thanks for the understanding and the bug report! I have created and fixed separate issue for the new problem #298 

As soon as [this CI build](https://ci.appveyor.com/project/PerfDotNet/benchmarkdotnet/build/0.10.0.222) finishes you should be able to download our latest development package and try the improved 0.10.0 version. Address of nuget feed: `<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />`

**Comment by sleemer** [comment]
@adamsitnik Thank you man!

**Comment by adamsitnik** [comment]
@sleemer project.json which required the runtime settings are being abandoned. We are now supporting the new csproj files, which don't require that so I am closing this issue as it won't be a problem anymore
