### ISSUE TITLE
How to get mono working?

### ISSUE THREAD

**Issue by xoofx** [dotnet/BenchmarkDotNet#304]
While trying to run a benchmark with:
```C#
            var config = ManualConfig.Create(DefaultConfig.Instance);
            config.Add(Job.Mono);
            BenchmarkDotNet.Running.BenchmarkRunner.Run<Program>(config);
```
I'm getting the exception:
```
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, Benchmark benchmark, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, IDiagnoser compositeDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(Benchmark benchmark, ILogger logger, String exeName, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BuildResult buildResult, Benchmark benchmark, ILogger logger, IResolver resolver, IDiagnoser compositeDiagnoser)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
``` 
Mono executable is on the PATH.
What is missing?
(Platform: Windows 10 x64, mono x86)

**Comment by xoofx** [comment]
han, found the problem... I was setting the PATH from the command line which was surrounded by double-quotes `set PATH="C:\Program Files (x86)\Mono\bin";%PATH%` ... strange this is working if I run mono from the command line, but the `Process.StartWithCreateProcess` doesn't like it. Removing the double quotes `set PATH=C:\Program Files (x86)\Mono\bin;%PATH%` is working with BenchmarkDotNet.
