### ISSUE TITLE
BenchmarkRunner.RunUrl throws BenchmarkSystem.IO.FileNotFoundException

### ISSUE THREAD

**Issue by UncleFirefox** [dotnet/BenchmarkDotNet#321]
Hi,

I'm trying to run the web samples from the repo using the raw url like for example:

` var summaryFromUrl =
                BenchmarkRunner.RunUrl("https://raw.githubusercontent.com/dotnet/BenchmarkDotNet/master/samples/BenchmarkDotNet.Samples/Intro/IntroBasic.cs");`

But I always got this exception.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BenchmarkDotNet.Core, Version=0.10.1.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
```

It seems from what I see in the console while executing that the RunUrl method places the files in a temp folder where the other dlls are not present:

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   IntroBasic.Sleep: DefaultJob
//   IntroBasic.Thread.Sleep(100): DefaultJob

// Validating benchmarks:
// **************************
// Benchmark: IntroBasic.Sleep: DefaultJob
// *** Generate ***
// Result = Success
// BinariesDirectoryPath = C:\Users\alber\AppData\Local\Temp

// *** Build ***
BuildScript: C:\Users\alber\AppData\Local\Temp\BDN.Generated.bat
// Result = Success

// *** Execute ***
// Launch: 1 / 1
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BenchmarkDotNet.Core, Version=0.10.1.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

// Run, Diagnostic
// BeforeAnythingElse
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BenchmarkDotNet.Core, Version=0.10.1.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
```

Do you know if there's a way to force the benchmark file to be generated where the binaries reside?

Cheers

**Comment by adamsitnik** [comment]
Hi!

Thanks for the bug report! Currently I have no workaround. The solution would be to persist the dll created [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/ClassicBenchmarkConverter.cs#L45) in `typeof(Benchmark).Assembly.Location` folder. Once I get from holidays I will fix it (after 26th of December)
