### ISSUE TITLE
Error when run from ReSharper unit test session

### ISSUE THREAD

**Issue by JamesNK** [dotnet/BenchmarkDotNet#367]
```
[Test]
public void RunBenchmarks()
{
    new BenchmarkSwitcher(typeof(Runner).GetTypeInfo().Assembly).Run(new []{ "*" });
}
```

Output when run:

```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver, GcStats& gcStats)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunBenchmarks(String[] args)

Target type: JTokenBenchmarks
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   JTokenBenchmarks.TokenWriteTo: DefaultJob

// Validating benchmarks:
// **************************
// Benchmark: JTokenBenchmarks.TokenWriteTo: DefaultJob
// *** Generate *** 
// Result = Success
// BinariesDirectoryPath = C:\Users\jamesn\AppData\Local\Temp\vng5e4dc.3il\ti2lap2e.aez\Newtonsoft.Json.Tests\assembly\dl3\d92bb459\0553274d_4b8ed201

// *** Build ***
BuildScript: C:\Users\jamesn\AppData\Local\Temp\vng5e4dc.3il\ti2lap2e.aez\Newtonsoft.Json.Tests\assembly\dl3\d92bb459\0553274d_4b8ed201\BDN.Generated.bat
// Result = Success

// *** Execute ***
// Launch: 1 / 1
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BenchmarkDotNet.Core, Version=0.10.1.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

// Run, Diagnostic
// BeforeAnythingElse
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BenchmarkDotNet.Core, Version=0.10.1.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
```

**Comment by adamsitnik** [comment]
Hi @JamesNK ! You need to disable shadow copy. We are currently not supporting it and not planning to change it (due to many consequences, not because we don't like it)

**Comment by JamesNK** [comment]
okie dokie. Thanks
