### ISSUE TITLE
Troubles with ClrJob from CoreCLR project

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#372]
Repro:
1. Create a new .NET Core console application in VS2017 RC4.
2. Add the following lines in `csproj` file:
```xml
    <TargetFrameworks>netcoreapp1.1;net45</TargetFrameworks>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net45' ">win7-x86</RuntimeIdentifier>
```
3. Run the following benchmark:
```cs
    [ClrJob]
    public class Test
    {
        [Benchmark]
        public void Sleep() => Thread.Sleep(1000);
    }

    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<Test>();
        }
    }
```
4. Get the following error:
```
System.BadImageFormatException: Could not load file or assembly 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by adamsitnik** [comment]
@AndreyAkinshin you need to add `<PlatformTarget>AnyCPU</PlatformTarget>` to your csproj. This is unfortunately not a default setting for the new csprojs.

**Comment by AndreyAkinshin** [comment]
Could we detect such situation somehow? It's not obious what is going on in this case. It would be nice to print a warning.

**Comment by adamsitnik** [comment]
@AndreyAkinshin good idea! I added the warning
