### ISSUE TITLE
Could not load file or assembly 'System.Reflection.Metadata'

### ISSUE THREAD

**Issue by niemyjski** [dotnet/BenchmarkDotNet#395]
I just am upgrading from old project.json to new csproj and updated all my dependencies and now my benchmarks won't run for the following project: https://github.com/exceptionless/Exceptionless.Net/tree/ba740c9867c48131ae4a057692af2c451eda2cd7

I see that my main project references System.Diagnostics.StackTrace (4.3.0) which references 1.4.1 of the MetaData assembly but BenchmarkDotNet 0.10.3 references 1.3.0. I think this is the issue (and so much for semver) :)

```
System.IO.FileLoadException
Could not load file or assembly 'System.Reflection.Metadata, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.Build(GenerateResult generateResult, ILogger logger, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Build(ILogger logger, IToolchain toolchain, GenerateResult generateResult, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
   at Exceptionless.Tests.Plugins.PluginTests.RunBenchmark() in C:\Code\Exceptionless.Net\test\Exceptionless.Tests\Plugins\PluginTests.cs:line 885
```

**Comment by adamsitnik** [comment]
Fixed, wasn't really our fault (VS did not generate the right assembly bindings). [PR](https://github.com/exceptionless/Exceptionless.Net/pull/146)
