### ISSUE TITLE
Troubles with Classic applications on nightly BenchmarkDotNet

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#410]
I created new ConsoleApplication, set .NETFramework4.6, installed BenchmarkDotNet `0.10.3.82`, wrote simple benchmark:
```cs
    public class Test
    {
        [Benchmark]
        public void Sleep() => Thread.Sleep(10);
    }
```
and tried to run it. The result:
```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   Test.Sleep: DefaultJob

// Validating benchmarks:
// **************************
// Benchmark: Test.Sleep: DefaultJob
// *** Generate ***
// Result = Success
// BinariesDirectoryPath = W:\Sandbox\ConsoleApplication\ConsoleApplication\bin\Release

// *** Build ***
BuildScript: W:\Sandbox\ConsoleApplication\ConsoleApplication\bin\Release\BDN.Generated.bat
// Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.AssemblyMetadata.CreateFromFile(String path)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.GetFrameworkAssembliesMetadata()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.Build(GenerateResult generateResult, ILogger logger, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Build(ILogger logger, IToolchain toolchain, GenerateResult generateResult, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\Test-report.csv
  BenchmarkDotNet.Artifacts\results\Test-report-github.md
  BenchmarkDotNet.Artifacts\results\Test-report.html

// * Detailed results *
Test.Sleep: DefaultJob
Runtime = ; GC =
There are no any results runs

Total time: 00:00:00 (0.63 sec)

// * Summary *

BenchmarkDotNet=v0.10.3.82-nightly, OS=Windows 10.0.14393
Processor=Intel(R) Core(TM) i7-6700HQ CPU 2.60GHz, ProcessorCount=8
Frequency=2531253 Hz, Resolution=395.0613 ns, Timer=TSC
  [Host] : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0


 Method | Mean |
------- |----- |
  Sleep |   NA |

Benchmarks with issues:
  Test.Sleep: DefaultJob
```
Probably related to https://github.com/dotnet/BenchmarkDotNet/issues/401
@adamsitnik, could you take a look?

**Comment by AndreyAkinshin** [comment]
[Repro.zip](https://github.com/dotnet/BenchmarkDotNet/files/895232/Repro.zip)

**Comment by adamsitnik** [comment]
That's interesting. When I create a new project in VS 2015/2017 and install latest BDN I can not reproduce it. However with your repo I can.

The difference is that my VS generates following `App.config` with assembly binding redirects:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Xml.XPath.XDocument" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.FileVersionInfo" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

I will need to dig in more into that because it seems to be common problem. We have at least 3 or 4 bugs reported with various assembly loading exceptions

**Comment by adamsitnik** [comment]
Fixed, wasn't really our fault. VS did not generate the right assembly bindings. I have no idea why, but now we try to help .NET framework when it fails to resolve an assembly.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, awesome thanks. But now I have another issue: https://github.com/dotnet/BenchmarkDotNet/issues/419, it can be related. Could you take a look?
