### ISSUE TITLE
NullReferenceException in DefaultOrderProvider

### ISSUE THREAD

**Issue by DixonDs** [dotnet/BenchmarkDotNet#449]
See the stacktrace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Order.DefaultOrderProvider.<>c__DisplayClass7_0.<GetSummaryOrder>b__0(Benchmark b)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
```

`SummaryOrderPolicy.FastestToSlowest` is used.

**Comment by pgsin** [comment]
@DixonDs It would be useful to provide some code that is producing such error.

As result I cannot say for sure, but [BenchmarkReport.ResultStatistics](https://github.com/dotnet/BenchmarkDotNet/blob/0dafac43cb2553f075592128a54fa1cdbd0cf8ba/src/BenchmarkDotNet.Core/Reports/BenchmarkReport.cs#L24) can be null by definition but just in the case then there is no ResultRuns. I'm lost in guessing how this could happen.

There is no single unit-test that covers SummaryOrderPolicy.FastestToSlowest/.SlowestToFastest options in [GetSummaryOrder](https://github.com/dotnet/BenchmarkDotNet/blob/24e944ae06101a8051955fcfb0ae6c4413950fdc/src/BenchmarkDotNet.Core/Order/DefaultOrderProvider.cs#L35).

**Comment by adamsitnik** [comment]
Unable to reproduce by @pgsin , no response for a long time from @DixonDs 

I am closing as it's unable to reproduce

**Comment by Kimosabe** [comment]
It happens when you are trying to sort NaN (NA) values.
Simple example:

```
    [OrderProvider(BenchmarkDotNet.Order.SummaryOrderPolicy.SlowestToFastest)]
    public class Repro
    {
        [Params("", null)]
        public object Param;

        [Benchmark]
        public object Func()
        {
            return Param.GetType();
        }
    }
```

**Comment by AndreyAkinshin** [comment]
@Kimosabe could you please create a separate issue for this problem?
