### ISSUE TITLE
TypeLoadException trying to run benchmark on Clr

### ISSUE THREAD

**Issue by CheloXL** [dotnet/BenchmarkDotNet#485]
I created a very simple benchmark over one of my libraries to try to optimize it a bit and BDN is throwing the following ex while trying to run under Clr

```
Exception: System.TypeLoadException: Method 'get_Language' in type 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.Build(GenerateResult generateResult, ILogger logger, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Build(ILogger logger, IToolchain toolchain, GenerateResult generateResult, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
```

Under Core everything runs fine. I have only one [Benchmark] entry. This is my project definition:

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>netcoreapp1.1;net46</TargetFrameworks>
		<RuntimeIdentifiers>win7-x64;win7-x86;</RuntimeIdentifiers>
		<RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net46' ">win7-x64</RuntimeIdentifier>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.10.8" />
		<PackageReference Include="BenchmarkDotNet.Core" Version="0.10.8" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Memoizer\Memoizer.csproj" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net46'">
		<PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.10.8" />
		<Reference Include="System.Reflection" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">
		<PackageReference Include="System.ComponentModel.EventBasedAsync" Version="4.0.11" />
	</ItemGroup>
</Project>
```

**Comment by adamsitnik** [comment]
Hello @CheloXL !

Thanks for using BenchmarkDotNet. The exception you are getting is really strange. Could you tell me which Visual Studio and NuGet client version are you using?

**Comment by CheloXL** [comment]
Vs 2017 (latest service pack), BDN 0.10.8

**Comment by CheloXL** [comment]
Closing this issue. With the latest version this doesn't happens.
