### ISSUE TITLE
Cannot run in LINQPad; gives "TypeLoadException: Method 'GetImports' does not have an implementation"

### ISSUE THREAD

**Issue by jnm2** [dotnet/BenchmarkDotNet#486]
I'm running into something I can't find guidance on. I'm trying to running benchmarks in LINQPad. No benchmarks are running and I'm getting this error output:

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   Test.Foo: DefaultJob

// Validating benchmarks:
Assembly query_wktdkn which defines benchmarks references non-optimized LINQPad
// **************************
// Benchmark: Test.Foo: DefaultJob
// *** Generate *** 
// Result = Success
// BinariesDirectoryPath = C:\Users\jmusser\AppData\Local\Temp\LINQPad5\_tqffugaq

// *** Build ***
// Exception: System.TypeLoadException: Method 'GetImports' in type 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at BenchmarkDotNet.Toolchains.Roslyn.Builder.Build(GenerateResult generateResult, ILogger logger, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Build(ILogger logger, IToolchain toolchain, GenerateResult generateResult, Benchmark benchmark, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
```

### Repro steps

 * Open LINQPad (I'm running 5.22.02 on .NET Framework 4.7.02046 and Windows 10 v1703 build 15063.413)
 * Add NuGet reference to BenckmarkDotNet (or manually reference all the DLLs)
 * Run this as a C# program:

   ```c#
   void Main()
   {    
       Environment.CurrentDirectory = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);
       BenchmarkDotNet.Running.BenchmarkRunner.Run<Test>();
   }
   
   public class Test
   {
       [BenchmarkDotNet.Attributes.Benchmark]
       public void Foo()
       {
       }
   }
   ```

**Comment by AndreyAkinshin** [comment]
@jnm2, the latest BenchmarkDotNet is supported only in 5.22.05+, you should manually download the latest beta from the LINQPad official site. More info here: http://aakinshin.net/blog/post/bdn-v0_10_7/#linqpad-support

**Comment by jnm2** [comment]
Awesome, thanks!
