### ISSUE TITLE
UnauthorizedAccessException preventing report to be written

### ISSUE THREAD

**Issue by Rattenkrieg** [dotnet/BenchmarkDotNet#491]
This is super annoying especially after big long harness runs.

<details><summary>stacktrace</summary><p>

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\sergey\fscheckbenchmarks\src\ParallelBenchmarks\bin\Release\BDN.Generated.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at BenchmarkDotNet.Toolchains.Roslyn.Generator.ArtifactCleanup(Benchmark benchmark, ArtifactsPaths artifactsPaths)
   at BenchmarkDotNet.Toolchains.GeneratorBase.<>c__DisplayClass8_0.<GetArtifactsPaths>b__0(ArtifactsPaths artifactsPaths)
   at BenchmarkDotNet.Toolchains.ArtifactsPaths.RemoveBenchmarkFiles()
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunBenchmarks(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at Program.Main(String[] args) in C:\sergey\fscheckbenchmarks\src\ParallelBenchmarks\Program.fs:line 201

```

</p></details>

I think we should put defensive catch around [this invocation](https://github.com/dotnet/BenchmarkDotNet/blob/6fc2456ceec071bfc2e3432c3b800ae905c90c6a/src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs#L212) so further log flushing routine can proceed no matter how hard executable is "inacessible". Another option is to place cleanup closer to the end of runner lifecycle.

/realted #377

**Comment by adamsitnik** [comment]
hi @Rattenkrieg 

Thanks for a bug report with high quality description!

I have just changed the default behavior, the default folder/program name is new guid and we remove all artifacts after printing the results.

**Comment by Rattenkrieg** [comment]
Also this happens on random basis so I'm afraid this behavior is barely reproducible. My thoughs that this may happen when BDN.Generated.exe process haven't exited yet while runner tries to delete its file. I'm not familiar with architecture though. So don't treat this as good directions. Btw all my scenarios are involving ThreadPool work and lots of concurrent-foo (if this may sound useful).

**Comment by adamsitnik** [comment]
Thanks for  the extra info. I believe that the new solution should prevent from any problems.

You can check it now by downloading `0.10.8.242` package from our CI NuGet feed:
```
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by Rattenkrieg** [comment]
Just realized that this issue was already reported, sorry for duplicating. :see_no_evil:
