### ISSUE TITLE
Problems with Disassembler + Job.Dry

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#542]
Consider the following benchmark:
```cs
    [DisassemblyDiagnoser(printAsm: true, printSource: true)] 
    [Config(typeof(Config))]
    public class Simple
    {
        private class Config : ManualConfig
        {
            public Config()
            {
                Add(Job.Dry.With(Runtime.Clr));
            }
        }
        int[] field = Enumerable.Range(0, 100).ToArray();

        [Benchmark]
        public int SumLocal()
        {
            var local = field; // we use local variable that points to the field

            int sum = 0;
            for (int i = 0; i < local.Length; i++)
                sum += local[i];

            return sum;
        }

        [Benchmark]
        public int SumField()
        {
            int sum = 0;
            for (int i = 0; i < field.Length; i++)
                sum += field[i];

            return sum;
        }
    }
```
I get this error all the time:
```
// Run, Diagnostic
// Execute: W:\Work\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\net46\win7-x86\5b42fd7a-e60e-477b-bb0a-c7289417f2ec.exe diagnoserAttached
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2102.0
// GC=Concurrent Workstation
// Job: Job-DVDVQO(Runtime=Clr, LaunchCount=1, RunStrategy=ColdStart, TargetCount=1, UnrollFactor=1, WarmupCount=1)

// AfterGlobalSetup
// Exception: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDisassemblyResult.Read9_DisassemblyResult()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at BenchmarkDotNet.Diagnosers.WindowsDisassembler.Dissasemble(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.DisassemblyDiagnoser.AfterGlobalSetup(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Extensions.CommonExtensions.ForEach[T](IList`1 source, Action`1 command)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, Benchmark benchmark, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(Benchmark benchmark, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver, IConfig config)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver, GcStats& gcStats)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver, List`1 artifactsToCleanup)
```
Artifacts:
[BenchmarkDotNet.Artifacts.zip](https://github.com/dotnet/BenchmarkDotNet/files/1285003/BenchmarkDotNet.Artifacts.zip)

**Comment by adamsitnik** [comment]
@AndreyAkinshin most probably, for Job.Dry the benchmark ends before we even attach with ClrMD to the benchmarked process. It works fine with `Job.ShortRun`. I am not sure what could be done about that except of a warning

**Comment by AndreyAkinshin** [comment]
@adamsitnik, yes, you are right, `ShortRun` works perfectly. And I understand it as a BenchmarkDotNet developer. But it still looks very strange from the user point of view. In fact, we don't need dozens of iterations to get the assembly code. If I don't want to actually benchmark my methods and I want only to get the assembly code, why do I need many iterations? `Job.Dry` looks like a good choice.

I think we have to find a workaround somehow: the runner process should wait for the disasm process.
it's probably not an easy task, so I guess it will be enouth to show a warning for `v0.10.10`. The `System.InvalidOperationException: There is an error in XML document (0, 0)` looks too confusing.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I will add warning for 0.10.10 and try to play with process syncrhonization for 10.11

**Comment by AndreyAkinshin** [comment]
Great, thanks!

**Comment by adamsitnik** [comment]
Done, I opened #543 for the synchronization

**Comment by adamsitnik** [comment]
Update: it now works. See #543 for more details
