### ISSUE TITLE
[Bug] Benchmarking a method doesn't run global setup

### ISSUE THREAD

**Issue by atifaziz** [dotnet/BenchmarkDotNet#564]
## Steps to Reproduce

1. Clone the repo and checkout 9c194c663a2c8971763d0f81a7d5361c00f07792
2. `cd` into the clone directory
3. Build the project by running `build.bat`
4. Run benchmarks in class `IL_Loops` by executing: `dotnet run -c Release -f netcoreapp2.0 --project samples\BenchmarkDotNet.Samples -- class=IL_Loops`
5. Run a benchmark for the method `ForEachArray` in class `IL_Loops` by executing: `dotnet run -c Release -f netcoreapp2.0 --project samples\BenchmarkDotNet.Samples -- method=ForEachArray`

## Expected Result

Expected all requested benchmarks in steps 4 and 5 to run to completion.

## Actual Result

Benchmarks in step 4 run fine but the benchmark for the single method `ForEachArray` in step 5 fails with a `NullReferenceException`:

```
Target type: IL_Loops
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   IL_Loops.ForEachArray: DefaultJob

// Validating benchmarks:
// **************************
// Benchmark: IL_Loops.ForEachArray: DefaultJob
// *** Generate *** 
// Result = Success
// BinariesDirectoryPath = A:\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\netcoreapp2.0\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa\bin\Release\netcoreapp2.0

// *** Build ***
// dotnet restore took 5.54s
// dotnet build took 11.31s
// Result = Success

// *** Execute ***
// Launch: 1 / 1

// Benchmark Process Environment Information:
// Runtime=.NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
// GC=Concurrent Workstation
// Job: DefaultJob

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Samples.IL.IL_Loops.ForEachArray() in A:\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\IL\IL_Loops.cs:line 33
   at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount) in A:\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\netcoreapp2.0\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa.notcs:line 400
   at BenchmarkDotNet.Engines.Engine.Jitting() in A:\BenchmarkDotNet\src\BenchmarkDotNet.Core\Engines\Engine.cs:line 93
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host) in A:\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\netcoreapp2.0\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa.notcs:line 122
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at BenchmarkDotNet.Autogenerated.Program.AfterAssemblyLoadingAttached(String[] args) in A:\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\netcoreapp2.0\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa\ac9c1caf-53d4-4b45-8b62-7bfbd28528fa.notcs:line 56
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\BenchmarkDotNet.Samples.IL.IL_Loops-report.csv
  BenchmarkDotNet.Artifacts\results\BenchmarkDotNet.Samples.IL.IL_Loops-report-github.md
  BenchmarkDotNet.Artifacts\results\BenchmarkDotNet.Samples.IL.IL_Loops-report.html

// * Detailed results *
IL_Loops.ForEachArray: DefaultJob
Runtime = ; GC = 
There are no any results runs

Total time: 00:00:17 (17.72 sec)

// * Summary *

BenchmarkDotNet=v0.10.9.20171006-develop, OS=Windows 10 Threshold 2 [1511, November Update] (10.0.10586)
Processor=Intel Core i7-6600U CPU 2.60GHz (Skylake), ProcessorCount=4
Frequency=2742187 Hz, Resolution=364.6724 ns, Timer=TSC
.NET Core SDK=2.0.0
  [Host] : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT


       Method | Mean | Error |
------------- |-----:|------:|
 ForEachArray |   NA |    NA |

Benchmarks with issues:
  IL_Loops.ForEachArray: DefaultJob

// * Legends *
  Mean  : Arithmetic mean of all measurements
  Error : Half of 99.9% confidence interval
  1 ns  : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
// * Artifacts cleanup *

Global total time: 00:00:19 (19.79 sec)
```

This happens because [`initialValuesArray` is uninitialzed](https://github.com/dotnet/BenchmarkDotNet/blob/9c194c663a2c8971763d0f81a7d5361c00f07792/samples/BenchmarkDotNet.Samples/IL/IL_Loops.cs#L33) in the benchmark has not been initialized:

```c#
        [Benchmark]
        public int ForEachArray()
        {
            var counter = 0;
            foreach (var i in initialValuesArray)
                counter += i;
            return counter;
        }
```

This is in turn due to the [global setup in `GlobalSetupData`](https://github.com/dotnet/BenchmarkDotNet/blob/9c194c663a2c8971763d0f81a7d5361c00f07792/samples/BenchmarkDotNet.Samples/IL/IL_Loops.cs#L12-L18) of that class never getting called. This can be verified by looking at the generated code for the benchmark.

## Additional Information

The tip of `master` (9076a69f4e4e471d7820e12aef9b736c6d64a60f) was [broken](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.9.316) at the time of reporting so its parent 9c194c663a2c8971763d0f81a7d5361c00f07792 was used instead.

The same problem can be reproduced against the last released version of [0.10.9](https://github.com/dotnet/BenchmarkDotNet/releases/tag/v0.10.9).

While steps 4 & 5 specify `netcoreapp2.0` as the framework, the bug can be observed for any of the targets supported by `BenchmarkDotNet.Samples.csproj`.

**Comment by adamsitnik** [comment]
@atifaziz thanks a lot for a great bug report! fixed ;)
