### ISSUE TITLE
Bug: Statistics.DivMean - NullReferenceException 

### ISSUE THREAD

**Issue by nietras** [dotnet/BenchmarkDotNet#630]
I am apparently good at constantly running into cases where BDN fails. Version 0.10.12.

https://github.com/DotNetCross/Sorting/tree/fc60378eee0cb9cafed9f35d596b42aaaca8269e

Simply run the `DotNetCross.Sorting.Benchmarks` in `Release` from VS2017 for example. During these benchmarks I get the following:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Mathematics.Statistics.DivMean(Statistics x, Statistics y)
   at BenchmarkDotNet.Columns.BaselineScaledColumn.<>c__DisplayClass13_0.<IsNonBaselinesPrecise>b__2(Benchmark x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Columns.BaselineScaledColumn.GetValue(Summary summary, Benchmark benchmark)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, ILogger logger, String title, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver, List`1 artifactsToCleanup)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, Func`2 toolchainProvider)
   at DotNetCross.Sorting.Benchmarks.Program.Main(String[] args)
```

**Comment by AndreyAkinshin** [comment]
@nietras, thanks for the report. Will fix it soon.

**Comment by redknightlois** [comment]
@nietras you are not the only one, I just came here to report the same :D

**Comment by jnm2** [comment]
Just hit this.

**Comment by jnm2** [comment]
Is there anything I can even do to work around this? Looks like I'm totally blocked at this point.

**Comment by AndreyAkinshin** [comment]
I didn't reproduce the issue locally, but I hope the I have fixed it. Please, try 0.10.12.444 from our nightly feed.
