### ISSUE TITLE
 BenchmarkDotNet.Mathematics.RankHelper again. 

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/BenchmarkDotNet#644]
There is VS 2017 core project (BenchmarkDotNet 0.10.12 used)

Configured as:

 ```
 <PropertyGroup>
    <OutputType>Exe</OutputType>
     <TargetFrameworks>netcoreapp2.0;net47</TargetFrameworks>
	 <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

Benchmark class configured as:

```
    [ClrJob(isBaseline: true), CoreJob]
    [HtmlExporter, MarkdownExporter]
    [RankColumn]
    public class BenchmarkAdminkaRoutine
    {
             // ....
    }

```

run as 

`& dotnet run -c Release -f netcoreapp2.0 -p "$BenchmarkProjectPath"`

And got error at the end:

 ```
// AfterAll

Mean = 7.1830 ms, StdErr = 0.0726 ms (1.01%); N = 88, StdDev = 0.6807 ms
Min = 6.2958 ms, Q1 = 6.6285 ms, Median = 7.0723 ms, Q3 = 7.5386 ms, Max = 9.4801 ms
IQR = 0.9101 ms, LowerFence = 5.2634 ms, UpperFence = 8.9037 ms
ConfidenceInterval = [6.9359 ms; 7.4301 ms] (CI 99.9%), Margin = 0.2471 ms (3.44% of Mean)
Skewness = 1.11, Kurtosis = 4.18

System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Mathematics.RankHelper.<>c.<GetRanks>b__0_1(<>f__AnonymousType2`2 pair)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Mathematics.RankHelper.GetRanks(Statistics[] stats)
   at BenchmarkDotNet.Columns.RankColumn.GetValue(Summary summary, Benchmark benchmark)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, ILogger logger, String title, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver, List`1 
artifactsToCleanup)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, Func`2 toolchainProvider)
   at BenchmarkAdminka.Program.Main(String[] args) in D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\Program.cs:line 12
```

What is wrong?
Please create a more usefull message.

**Comment by AndreyAkinshin** [comment]
I didn't reproduce the issue locally, but I hope the I have fixed it. Please, try 0.10.12.445 from our nightly feed.

**Comment by rpokrovskij** [comment]
It works right now (place "?" mark instead of throwing exception - and I'm become motivated to show deeper to the logs).
