### ISSUE TITLE
Does BenchMarkDotnet supports 4.7.1 Dotnet framework

### ISSUE THREAD

**Issue by srikanthkadem** [dotnet/BenchmarkDotNet#667]
Hi , 
Could you please confirm if the BenchMarkDotnet package support the latest dotnet framework i.e 4.7.1 . I was facing below runtime issue while trying to use this for projects targetted for 4.7.1

error 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Running.BenchmarkConverter.GetParameterDefinitions(Type type)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ReadOnlyConfig fullConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)

**Comment by adamsitnik** [comment]
Hi @srikanthkadem 

which version of BenchmarkDotNet are you using? #621 was supposed to fix such problems, it was part of `0.10.12`

If you are already using  `0.10.12` then please provide me your `.csproj` file and sample benchmark (I need to be able to reproduce the problem)

**Comment by kevin-montrose** [comment]
I've been updating my [LinqAF project to target 4.7.1](https://github.com/kevin-montrose/LinqAF), and am now experiencing something quite similar though with System.Runtime.

My solution is gigantic, so I cut it down to  a smaller [Reproduction Solution](https://www.dropbox.com/s/n5qx7in0bs4aaub/BenchMarkDotnet-Repro.7z?dl=0); the relevant project is LinqAF.Benchmark.  I apologize for the benchmarked project (LinqAF.Generated) still being quite large, but it's pretty hard to cut down.  You'll need to restore NuGet packages.

Running the LinqAF.Benchmark will crash with a null ref 'cause nothing was actually benchmarked.

![image](https://user-images.githubusercontent.com/1219467/37248696-cb263dc6-24a6-11e8-8b0b-7ec4bd2a7ffc.png)
^ is the relevant output

**Comment by adamsitnik** [comment]
Hi @kevin-montrose 

Big thanks for the repro case.

I was able to reproduce your problem.

It looks that your assembly binding redirects are wrong. I am not sure if VS generated wrong ones for you during the target framework update or BDN installation. My VS complained about them:

![image](https://user-images.githubusercontent.com/6011991/37282800-09111f02-25f6-11e8-9e32-a7015c96e3f2.png)

Solution: remove all the assembly binding redirects.
If you need them please remove them, uninstall BDN and install it once again. I hope that VS will generate the right ones.

**Comment by adamsitnik** [comment]
@kevin-montrose please let me know if it works after applying the "fix"

**Comment by kevin-montrose** [comment]
Yep, that looks to have been it.  Have tested with my original solution, and the problem is fixed there as well.  A little odd that my VS (2017 Professional, 4.7.02558 in case anyone else sees this) wasn't warning on that... but I doubt that's anything to do with BenchmarkDotNet.

Sorry for the delay in testing, my last two days have been jam packed.

Thanks a bunch!

**Comment by adamsitnik** [comment]
@kevin-montrose thanks for the confirmation! I am happy it's not our fault ;)

@srikanthkadem has never responded so I am closing the issue.

**Comment by adamsitnik** [comment]
This was one big PITA, fixed by using some ugly workarounds in #1032
