### ISSUE TITLE
Copy custom setting from app.config in multitarget projects

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/BenchmarkDotNet#697]
I have multitarget Benchmark project defined as: 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;net47</TargetFrameworks>
  </PropertyGroup>
  ...
  <ItemGroup>
    <None Update="app.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

if it is compiled as .NET Framework and launched as exe file it works fine (can access the app.config), but
when it is started with dotnet 

```
$dotnetPath = 'C:\Program Files\dotnet\dotnet.exe'
... 
# this recompiles all target versions. dotnet run is not enough for it. but I'm not sure that this is obligated.
& $dotnetPath build $BenchmarkProjectPath -c Release

$snapshotBefore = Get-ChildItem *.html -path "$BenchmarkReportPath"

& dotnet run -c Release -f netcoreapp2.0 -p "$BenchmarkProjectPath"
```

Then I get the output that contains my custom thrown excpetion

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for
 'BenchmarkAdminka.ZoningSharedSourceProjectManager' threw an exception. ---> System.Exception: Section 'routinesConfiguration' is not found
   at DashboardCode.Routines.Configuration.NETFramework.ConfigurationManagerLoader..ctor(String sectionName) in D:\cot\DashboardCode\Routines\Routines.Configuration.NET
Framework\ConfigurationManagerLoader.cs:line 17

Custom code:
            var section = ConfigurationManager.GetSection(sectionName);
            if (section == null)
                throw new System.Exception($"Configuration section '{sectionName}' was not found");

```

That means that BDN compiled project folder doesn't contain app.config .
**Expected behavior:** app.config file copied (as it is described there https://github.com/dotnet/BenchmarkDotNet/issues/108 ).

Test configuration (use **ClrJob**):

```
    [ClrJob(isBaseline: true)]
    [HtmlExporter, MarkdownExporter]
    public class BenchmarkAdminkaRoutine
    {
```

Full output:

```
PS D:\cot\DashboardCode\Routines> D:\cot\DashboardCode\Routines\BenchmarkAdminka.ps1
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 56.03 ms for D:\cot\DashboardCode\Routines\AdminkaV1\Abstractions\AdminkaV1.csproj.
  Restore completed in 60.98 ms for D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore.InMemory\AdminkaV1.DataAccessEfCore.InMemory.csproj.
  Restore completed in 54.9 ms for D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore\AdminkaV1.DataAccessEfCore.csproj.
  Restore completed in 61.01 ms for D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore.SqlServer\AdminkaV1.DataAccessEfCore.SqlServer.csproj.
  Restore completed in 1.53 ms for D:\cot\DashboardCode\Routines\AdminkaV1\LoggingDom.WcfClient\AdminkaV1.LoggingDom.WcfClient.csproj.
  Restore completed in 22.81 ms for D:\cot\DashboardCode\Routines\Routines.Configuration.NETStandard\Routines.Configuration.NETStandard.csproj.
  Restore completed in 1.2 ms for D:\cot\DashboardCode\Routines\Routines.Serialization.NETStandard\Routines.Serialization.NETStandard.csproj.
  Restore completed in 0.85 ms for D:\cot\DashboardCode\Routines\Routines.Storage.EfCore\Routines.Storage.EfCore.csproj.
  Restore completed in 1.33 ms for D:\cot\DashboardCode\Routines\Routines.Storage.SqlServer\Routines.Storage.SqlServer.csproj.
  Restore completed in 10.77 ms for D:\cot\DashboardCode\Routines\Routines\Routines.csproj.
  Restore completed in 14.98 ms for D:\cot\DashboardCode\Routines\NLogExtensibles\NLogExtensibles.csproj.
  Restore completed in 14.92 ms for D:\cot\DashboardCode\Routines\AdminkaV1\Injected.NETStandard\AdminkaV1.Injected.NETStandard.csproj.
  Restore completed in 14.25 ms for D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\BenchmarkAdminka.csproj.
  Routines -> D:\cot\DashboardCode\Routines\Routines\bin\Release\netstandard2.0\DashboardCode.Routines.dll
  NLogExtensibles -> D:\cot\DashboardCode\Routines\NLogExtensibles\bin\Release\netstandard2.0\DashboardCode.NLogExtensibles.dll
  Routines.Storage.SqlServer -> D:\cot\DashboardCode\Routines\Routines.Storage.SqlServer\bin\Release\netstandard2.0\DashboardCode.Routines.Storage.SqlServer.dll
  AdminkaV1 -> D:\cot\DashboardCode\Routines\AdminkaV1\Abstractions\bin\Release\netstandard2.0\DashboardCode.AdminkaV1.dll
  Routines.Storage.EfCore -> D:\cot\DashboardCode\Routines\Routines.Storage.EfCore\bin\Release\netstandard2.0\DashboardCode.Routines.Storage.EfCore.dll
  AdminkaV1.LoggingDom.WcfClient -> D:\cot\DashboardCode\Routines\AdminkaV1\LoggingDom.WcfClient\bin\Release\netstandard2.0\DashboardCode.AdminkaV1.LoggingDom.WcfClient
.dll
  Routines.ActiveDirectory.NETFramework -> D:\cot\DashboardCode\Routines\Routines.ActiveDirectory.NETFramework\bin\Release\DashboardCode.Routines.ActiveDirectory.NETFra
mework.dll
  Routines.Configuration.NETFramework -> D:\cot\DashboardCode\Routines\Routines.Configuration.NETFramework\bin\Release\DashboardCode.Routines.Configuration.NETFramework
.dll
  Routines.Serialization.NETStandard -> D:\cot\DashboardCode\Routines\Routines.Serialization.NETStandard\bin\Release\netstandard2.0\DashboardCode.Routines.Serialization
.NETStandard.dll
  Routines.Serialization.NETFramework -> D:\cot\DashboardCode\Routines\Routines.Serialization.NETFramework\bin\Release\DashboardCode.Routines.Serialization.NETFramework
.dll
  Routines.Configuration.NETStandard -> D:\cot\DashboardCode\Routines\Routines.Configuration.NETStandard\bin\Release\netstandard2.0\DashboardCode.Routines.Configuration
.NETStandard.dll
  AdminkaV1.DataAccessEfCore.SqlServer -> D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore.SqlServer\bin\Release\netstandard2.0\DashboardCode.AdminkaV1.DataAcce
ssEfCore.SqlServer.dll
  AdminkaV1.DataAccessEfCore.InMemory -> D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore.InMemory\bin\Release\netstandard2.0\DashboardCode.AdminkaV1.DataAccess
EfCore.InMemory.dll
  AdminkaV1.DataAccessEfCore -> D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore\bin\Release\netstandard2.0\DashboardCode.AdminkaV1.DataAccessEfCore.dll
  AdminkaV1.Injected.NETStandard -> D:\cot\DashboardCode\Routines\AdminkaV1\Injected.NETStandard\bin\Release\netstandard2.0\DashboardCode.AdminkaV1.Injected.NETStandard
.dll
  AdminkaV1.Injected.NETFramework -> D:\cot\DashboardCode\Routines\AdminkaV1\Injected.NETFramework\bin\Release\DashboardCode.AdminkaV1.Injected.NETFramework.dll
  BenchmarkAdminka -> D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\bin\Release\net47\BenchmarkAdminka.exe
  BenchmarkAdminka -> D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\bin\Release\netcoreapp2.0\BenchmarkAdminka.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:16.56
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 51.35 ms for D:\cot\DashboardCode\Routines\AdminkaV1\Abstractions\AdminkaV1.csproj.
  Restore completed in 55.56 ms for D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore.InMemory\AdminkaV1.DataAccessEfCore.InMemory.csproj.
  Restore completed in 1.45 ms for D:\cot\DashboardCode\Routines\AdminkaV1\LoggingDom.WcfClient\AdminkaV1.LoggingDom.WcfClient.csproj.
  Restore completed in 3.95 ms for D:\cot\DashboardCode\Routines\NLogExtensibles\NLogExtensibles.csproj.
  Restore completed in 7.17 ms for D:\cot\DashboardCode\Routines\AdminkaV1\Injected.NETStandard\AdminkaV1.Injected.NETStandard.csproj.
  Restore completed in 1.52 ms for D:\cot\DashboardCode\Routines\Routines.Configuration.NETStandard\Routines.Configuration.NETStandard.csproj.
  Restore completed in 0.83 ms for D:\cot\DashboardCode\Routines\Routines.Serialization.NETStandard\Routines.Serialization.NETStandard.csproj.
  Restore completed in 0.96 ms for D:\cot\DashboardCode\Routines\Routines.Storage.EfCore\Routines.Storage.EfCore.csproj.
  Restore completed in 1.5 ms for D:\cot\DashboardCode\Routines\Routines.Storage.SqlServer\Routines.Storage.SqlServer.csproj.
  Restore completed in 0.42 ms for D:\cot\DashboardCode\Routines\Routines\Routines.csproj.
  Restore completed in 1.64 ms for D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore.SqlServer\AdminkaV1.DataAccessEfCore.SqlServer.csproj.
  Restore completed in 2.21 ms for D:\cot\DashboardCode\Routines\AdminkaV1\DataAccessEfCore\AdminkaV1.DataAccessEfCore.csproj.
  Restore completed in 13.1 ms for D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\BenchmarkAdminka.csproj.
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   BenchmarkAdminkaRoutine.MeasureRoutineLogList: Job-FFXTHL(Runtime=Clr, IsBaseline=True)

// Validating benchmarks:
// ***** Building 1 benchmark(s) in Parallel: Start   *****
// ***** Done, took 00:00:15 (15.21 sec)   *****
// **************************
// Benchmark: BenchmarkAdminkaRoutine.MeasureRoutineLogList: Job-FFXTHL(Runtime=Clr, IsBaseline=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\bin\Release\netcoreapp2.0\6ea91ccb-7548-40cc-ac72-79983771eb66\bin\Release\net47\6ea91ccb-7548-40cc-ac7
2-79983771eb66.exe 
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2633.0
// GC=Concurrent Workstation
// Job: Job-TOQMCM(Runtime=Clr, IsBaseline=True)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for
 'BenchmarkAdminka.ZoningSharedSourceProjectManager' threw an exception. ---> System.Exception: Section 'routinesConfiguration' is not found
   at DashboardCode.Routines.Configuration.NETFramework.ConfigurationManagerLoader..ctor(String sectionName) in D:\cot\DashboardCode\Routines\Routines.Configuration.NET
Framework\ConfigurationManagerLoader.cs:line 17
   at BenchmarkAdminka.ZoningSharedSourceProjectManager..cctor()
   --- End of inner exception stack trace ---
   at BenchmarkAdminka.ZoningSharedSourceProjectManager.GetConfiguration()
   at BenchmarkAdminka.BenchmarkAdminkaRoutine.MeasureRoutineLogList()
   at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount) in D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\bin\Release\netcoreapp2.0\6ea91c
cb-7548-40cc-ac72-79983771eb66\6ea91ccb-7548-40cc-ac72-79983771eb66.notcs:line 601
   at BenchmarkDotNet.Engines.Engine.Jitting()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host) in D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\bin\Release\netcoreapp2.0\6ea91ccb-7548-40cc-ac72-7
9983771eb66\6ea91ccb-7548-40cc-ac72-79983771eb66.notcs:line 128
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.AfterAssemblyLoadingAttached(String[] args) in D:\cot\DashboardCode\Routines\Tests\BenchmarkAdminka\bin\Release\netcoreapp2.
0\6ea91ccb-7548-40cc-ac72-79983771eb66\6ea91ccb-7548-40cc-ac72-79983771eb66.notcs:line 55
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\BenchmarkAdminkaRoutine-report.csv
  BenchmarkDotNet.Artifacts\results\BenchmarkAdminkaRoutine-report-github.md
  BenchmarkDotNet.Artifacts\results\BenchmarkAdminkaRoutine-report.html
  BenchmarkDotNet.Artifacts\results\BenchmarkAdminkaRoutine-report-default.md

// * Detailed results *
BenchmarkAdminkaRoutine.MeasureRoutineLogList: Job-FFXTHL(Runtime=Clr, IsBaseline=True)
Runtime = ; GC = 
There are not any results runs

Total time: 00:00:16 (16.53 sec)

// * Summary *

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.309)
Intel Core i5-2500K CPU 3.30GHz (Sandy Bridge), 1 CPU, 4 logical cores and 4 physical cores
Frequency=3233540 Hz, Resolution=309.2586 ns, Timer=TSC
.NET Core SDK=2.1.100
  [Host] : .NET Core 2.0.5 (CoreCLR 4.6.26020.03, CoreFX 4.6.26018.01), 64bit RyuJIT

Runtime=Clr  IsBaseline=True  

                Method | Mean | Error | StdDev | Min | Max | Median | Scaled | ScaledSD | Rank |
---------------------- |-----:|------:|-------:|----:|----:|-------:|-------:|---------:|-----:|
 MeasureRoutineLogList |   NA |    NA |     NA |  NA |  NA |     NA |      ? |        ? |    ? |

Benchmarks with issues:
  BenchmarkAdminkaRoutine.MeasureRoutineLogList: Job-FFXTHL(Runtime=Clr, IsBaseline=True)

// * Legends *
  Mean     : Arithmetic mean of all measurements
  Error    : Half of 99.9% confidence interval
  StdDev   : Standard deviation of all measurements
  Min      : Minimum
  Max      : Maximum
  Median   : Value separating the higher half of all measurements (50th percentile)
  Scaled   : Mean(CurrentBenchmark) / Mean(BaselineBenchmark)
  ScaledSD : Standard deviation of ratio of distibution of [CurrentBenchmark] and [BaselineBenchmark]
  Rank     : Relative position of current benchmark mean among all benchmarks (Arabic style)
  1 ns     : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
// * Artifacts cleanup *

PS D:\cot\DashboardCode\Routines> 
```

**Comment by rpokrovskij** [comment]
It is interesting that in this case:

& dotnet run -c Release -f net47 -p "$BenchmarkProjectPath"

app.confg is copied

and in this case is not:

& dotnet run -c Release -f netcoreapp2.0 -p "$BenchmarkProjectPath"


P.S. Test configured to use [ClrJob(isBaseline: true)]

**Comment by rpokrovskij** [comment]
And if we configure test with custom BDN config:

```
    public class MultipleRuntimes : ManualConfig
    {
        public MultipleRuntimes()
        {
            Add(Job.Default.With(CsProjClassicNetToolchain.Net47));
        }
    }

 
    [Config(typeof(MultipleRuntimes))]
    [RankColumn, MinColumn, MaxColumn, StdDevColumn, MedianColumn]
    [HtmlExporter, MarkdownExporter]
    public class BenchmarkAdminkaRoutine
    {
```

and start it 

& dotnet run -c Release -f net47 -p "$BenchmarkProjectPath"

it stops working!

**Remember if it configured with  [ClrJob(isBaseline: true)] it works**

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you please take a look?

**Comment by rpokrovskij** [comment]
```
    public class MultipleRuntimes : ManualConfig
    {
        public MultipleRuntimes()
        {
            Add(Job.Core.With(CsProjCoreToolchain.NetCoreApp20));
            Add(Job.Clr);
        }
    }
```

This combination works (if I understand it right that there both targets Net470 and core where tested)
```

                Method |     Job | Runtime |     Toolchain |     Mean |     Error |    StdDev |      Min |      Max |   Median | Rank |
---------------------- |-------- |-------- |-------------- |---------:|----------:|----------:|---------:|---------:|---------:|-----:|
 MeasureRoutineLogList | Default |    Core | .NET Core 2.0 | 5.505 ms | 0.0725 ms | 0.0678 ms | 5.380 ms | 5.590 ms | 5.512 ms |    1 |
 MeasureRoutineLogList |     Clr |     Clr |       Default | 5.750 ms | 0.1107 ms | 0.1087 ms | 5.525 ms | 5.936 ms | 5.767 ms |    2 |
```

**Comment by adamsitnik** [comment]
@rpokrovskij thanks for the bug report and sorry for the inconvenience! the fix is available in our 
 `0.10.13.482` CI NuGet package

**Comment by rpokrovskij** [comment]
Thank you. Great work.
