### ISSUE TITLE
Error of DisassemblyDiagnoser(printAsm: true, printSource: true) in MultiTarget project

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/BenchmarkDotNet#708]
I have a multitarget project with windows diagnoser enabler for NET47:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;net47</TargetFrameworks>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.10.13" />
    
    <PackageReference Include="DynamicExpresso.Core" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
  
    <ItemGroup Condition="'$(TargetFramework)' == 'net47'">
		<PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.10.13" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Routines\Routines.csproj" />
  </ItemGroup>
</Project>
```

Disassembler configuration enabled on conditional compiling:

```
#if !NETCOREAPP2_0
    [DisassemblyDiagnoser(printAsm: true, printSource: true)]
#endif
    public class BenchmarkConverAll
    { 

```
Inlining diagnoser enabled that way works, when dissasembly diagnoser returns an error:

Test executed as 
& dotnet run -c Release -f net47 -p "$BenchmarkProjectPath"

```
PS D:\cot\DashboardCode\Routines> D:\cot\DashboardCode\Routines\BenchmarkWindows.ps1
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 64.03 ms for D:\cot\DashboardCode\Routines\Routines\Routines.csproj.
  Restore completed in 64.46 ms for D:\cot\DashboardCode\Routines\Tests\Benchmark\Benchmark.csproj.
  Routines -> D:\cot\DashboardCode\Routines\Routines\bin\Release\netstandard2.0\DashboardCode.Routines.dll
  Benchmark -> D:\cot\DashboardCode\Routines\Tests\Benchmark\bin\Release\netcoreapp2.0\Benchmark.dll
  Benchmark -> D:\cot\DashboardCode\Routines\Tests\Benchmark\bin\Release\net47\Benchmark.exe

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.85
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 104.64 ms for D:\cot\DashboardCode\Routines\Routines\Routines.csproj.
  Restore completed in 121.11 ms for D:\cot\DashboardCode\Routines\Tests\Benchmark\Benchmark.csproj.
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   BenchmarkConverAll.TestConverAll: RyuJitX64(Jit=RyuJit, Platform=X64)

// Validating benchmarks:
// ***** Building 1 benchmark(s) in Parallel: Start   *****
// ***** Done, took 00:00:05 (5.29 sec)   *****
// **************************
// Benchmark: BenchmarkConverAll.TestConverAll: RyuJitX64(Jit=RyuJit, Platform=X64)
// *** Execute ***
// Launch: 1 / 1
// Execute: D:\cot\DashboardCode\Routines\Tests\Benchmark\bin\Release\net47\74d4fd8a-270d-46ab-bde8-907d0dfaa814.exe diagnoserAttached
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2633.0
// GC=Concurrent Workstation
// Job: RyuJitX64(Jit=RyuJit, Platform=X64)

Pilot  1: 16 op, 3459366.51 ns, 216.2104 us/op

..............................

// AfterAll
\ ---------------------------
Failed to read source code location!
Please make sure that the project, which defines benchmarks contains following settings:
	 <DebugType>pdbonly</DebugType>
	 <DebugSymbols>true</DebugSymbols>
\ ---------------------------
dotnet.exe : 
At D:\cot\DashboardCode\Routines\BenchmarkWindows.ps1:17 char:1
+ & dotnet run -c Release -f net47 -p "$BenchmarkProjectPath"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Unhandled Exception: 
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDisassemblyResult.Read9_DisassemblyResult()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at BenchmarkDotNet.Diagnosers.WindowsDisassembler.Dissasemble(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.DisassemblyDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Extensions.CommonExtensions.ForEach[T](IList`1 source, Action`1 command)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, Benchmark benchmark, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(Benchmark benchmark, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver 
resolver, IConfig config)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver 
resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.RunCore(Benchmark benchmark, ILogger logger, ReadOnlyConfig config, String rootArtifactsFolderPath, Func`2 
toolchainProvider, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, ILogger logger, String title, String rootArtifactsFolderPath, Func`2 
toolchainProvider, IResolver resolver, List`1 artifactsToCleanup)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, Func`2 toolchainProvider)
   at Benchmark.Program.Main(String[] args)
```

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment]
Hi @rpokrovskij 

The answer is in the output you provided:

```
Failed to read source code location!
Please make sure that the project, which defines benchmarks contains following settings:
	 <DebugType>pdbonly</DebugType>
	 <DebugSymbols>true</DebugSymbols>
```

Please feel free to reopen if it does not help.
