### ISSUE TITLE
IOException when running in OneDrive Folder

### ISSUE THREAD

**Issue by Zhentar** [dotnet/BenchmarkDotNet#733]
When BenchmarkDotNet tries to clean up after itself at the end of a test run, it fails and crashes:
```
Unhandled Exception: System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Cleanup(List`1 artifactsToCleanup)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, Func`2 toolchainProvider)
   at FastRNG.Program.Main() in c:\users\zhent\onedrive\documents\visual studio 2017\Projects\FastRNG\FastRNG\Program.cs:line 10
```

I would guess that this happens because OneDrive has handles open to these brand new files that it's trying to upload. It would be nice if these files were generated in a temp folder and not generating busywork for OneDrive. It would also be nice if the cleanup code tried a bit harder or at least didn't crash.

**Comment by adamsitnik** [comment]
> It would be nice if these files were generated in a temp folder

some of our users use `CopyToOutputDirectory` for native dependencies and this is why we generate the files in the same folder as `.exe` with benchmarks 

I have changed the  behavior, now the errors are going to be ignored.
