### ISSUE TITLE
"Operation could destabilize the runtime" when running benchmarks from full framework

### ISSUE THREAD

**Issue by jskeet** [dotnet/BenchmarkDotNet#772]
I hope to provide more information in later updates, but I wanted to file an issue before I forgot to do so - partly in case anyone else had seen anything similar.

To reproduce (on a Windows box, from a command prompt or bash):

```text
> git clone https://github.com/nodatime/nodatime.git
> cd nodatime/src/NodaTime.Benchmarks
> dotnet run -c Release -f net461 -- --exporter=briefjson --class=NodaTime.Benchmarks.NodaTimeTests.PeriodBenchmarks
```

Note that:

- NodaTime.Benchmarks depends on BenchmarkDotNet version 0.10.14
- NodaTime.Benchmarks targets `netcoreapp2.0`, `netcoreapp2.1`, `net461`. The netcoreapp targets work.
- NodaTime.Benchmarks has a project reference to NodaTime, which only targets netstandard2.0

On my machine, the `Between_LocalTime` method works, but all the others thrown an exception like this:

```text
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at NodaTime.LocalDateTime.get_Calendar()
   at NodaTime.Period.Between(LocalDateTime start, LocalDateTime end, PeriodUnits units)
   at NodaTime.Benchmarks.NodaTimeTests.PeriodBenchmarks.Between_LocalDateTime_Ticks()
   at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount)
   at BenchmarkDotNet.Engines.Engine.Jitting()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
```

Previous versions of NodaTime targeted net45 and netstandard1.3, and I didn't observe this problem - I wonder whether this is a ".NET framework depending on netstandard assembly" issue. I've seen the same problem when trying to update my snippets framework, but I suspect the details of that would distract more than help.

Will try to remove Noda Time from the equation to provide a short but complete example, and will also try to reproduce without Benchmark.NET.

**Comment by jskeet** [comment]
Okay, this has nothing to do with Benchmark.NET - a tiny console app demonstrates it too:

```csharp
using NodaTime;
using System;

namespace Unstable
{
    class Program
    {
        static void Main(string[] args)
        {
            LocalDateTime start = new LocalDateTime(1976, 6, 19, 8, 40, 0);
            LocalDateTime end = new LocalDateTime(2018, 6, 2, 11, 0, 0);
            Period period = Period.Between(start, end);
            Console.WriteLine(period);
        }
    }
}
```

Now I've got work out why...
