### ISSUE TITLE
AdaptiveHistogramBuilder.BuildWithFixedBinSize error when running benchmarks

### ISSUE THREAD

**Issue by ddobric** [dotnet/BenchmarkDotNet#802]
Getting following issue when executing some tests benchmark tests:

```
Unhandled Exception: System.InvalidOperationException: Failed to run AdaptiveHistogramBuilder.BuildWithFixedBinSize
BinSize: 0.000100000000
Values:
  0.005203099569
  0.005206927083
  0.005208544515
  0.005213252157
  0.005220535482
  0.005223894246
  0.005225830282
  0.005232740072
  0.005235999349
  0.005237509969
  0.005241159871
  0.005241720174
  0.005243189901
  0.005251286214
  0.005253464559

   at BenchmarkDotNet.Mathematics.Histograms.AdaptiveHistogramBuilder.BuildWithFixedBinSize(IEnumerable`1 values, Double binSize)
   at BenchmarkDotNet.Extensions.StatisticsExtensions.ToTimeStr(Statistics s, TimeUnit unit, Boolean calcHistogram)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, ILogger logger, String title, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver, List`1 artifactsToCleanup)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkRunInfo benchmarkRunInfo, Func`2 toolchainProvider)
   at Benchmarking.Program.Main(String[] args) in C:\dev\git..Benchmarking\Program.cs:line 15
// * Artifacts cleanup *
```

**Comment by AndreyAkinshin** [comment]
@ddobric, do you have logs from this benchmark run? (by default, you should have `.log` file in `BenchmarkDotNet.Artifacts`)

**Comment by AndreyAkinshin** [comment]
Reproduced.
