### ISSUE TITLE
Error after adding OperationsPerInvoke

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#870]
My benchmarks were running fine until I started adding OperationsPerInvoke like this to a method:

[Benchmark(OperationsPerInvoke = 1000, Description = "Test")]

The error seems to happen after this call completes:

var summary1 = BenchmarkRunner.Run<PerfTestRunner>(config);

Error is below:

System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to run AdaptiveHistogramBuilder.BuildWithFixedBinSize
BinSize: 0.000100000000
Values: 
  0.003599657069
  0.003634646485
  0.003697427313
  0.003699466536
  0.003708548049
  0.003713960151
  0.003734243611
  0.003739674340
  0.003744175980
  0.003800773571
  0.003830879132
  0.003877980957
  0.003890512834
  0.003932129542
  0.003952739338

  Source=BenchmarkDotNet
  StackTrace:
   at BenchmarkDotNet.Mathematics.Histograms.AdaptiveHistogramBuilder.BuildWithFixedBinSize(IEnumerable`1 values, Double binSize)
   at BenchmarkDotNet.Extensions.StatisticsExtensions.ToTimeStr(Statistics s, Encoding encoding, TimeUnit unit, Boolean calcHistogram)
   at BenchmarkDotNet.Exporters.BenchmarkReportExporter.ExportToLog(Summary summary, ILogger logger)
   at BenchmarkDotNet.Running.BenchmarkRunner.PrintSummary(ILogger logger, IConfig config, Summary summary)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at dotNetTips.CodePerf.Example.App.Program.Main() in S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\dotNetTips.CodePerf.Example.App\Program.cs:line 33

**Comment by DylanFPS** [comment]
Same issue.

**Comment by adamsitnik** [comment]
@AndreyAkinshin could you take a look? looks like something that we should solve for 0.11.3
