### ISSUE TITLE
Benchmark attributed with "HardwareCounters" throws an exception

### ISSUE THREAD

**Issue by usarskyy** [dotnet/BenchmarkDotNet#879]
Hi!

I have the following code:
```
[MemoryDiagnoser]
  [HardwareCounters(HardwareCounter.LlcMisses)]
  [DisassemblyDiagnoser(printAsm:true, printIL:true)]
  public class CpuCacheFails
  {
    public const int ARRAY_SIZE = 5096;

    public int[] UnsortedArray = new int[ARRAY_SIZE];
    
    [GlobalSetup]
    public void Setup()
    {
      var rng = RandomNumberGenerator.Create();

      for (int i = 0; i < ARRAY_SIZE; i++)
      {
        var bts = new byte[4];

        rng.GetBytes(bts);

        UnsortedArray[i] = BitConverter.ToInt32(bts, 0);
      }
    }

    [Benchmark]
    public int Unsorted()
    {
      int sum = 0;
      for (int i = 0; i < UnsortedArray.Length; ++i)
        if (UnsortedArray[i] >= 128)
          sum += UnsortedArray[i];
      return sum;
    }
  }

  class Program
  {
    static void Main(string[] args)
    {
      var summary = BenchmarkRunner.Run<CpuCacheFails>();

      Console.ReadLine();
    }
  }
```

Whenever I try to run the benchmarks I get the following exception:
```
Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at BenchmarkDotNet.Diagnostics.Windows.EtwDiagnoser`1.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Extensions.CommonExtensions.ForEach[T](IList`1 source, Action`1 command)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, BenchmarkCase benchmarkCase, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver, IConfig config)
   at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunner.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ReadOnlyConfig config, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at DD0918.BenchmarkDotNetCpuCacheLab.Program.Main(String[] args) in C:\Users\XXX\Documents\Visual Studio 2017\Projects\XXX\XXX\Program.cs:line 53
```

Here is some environment info:

> // BeforeAnythingElse
> // Benchmark Process Environment Information:
> // Runtime=.NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3160.0
> // GC=Concurrent Workstation
> // Job: DefaultJob

I use VS 2017 on x64 Win10, executed with admin privileges.

**Comment by usarskyy** [comment]
Forgot to mention that app's platform target is set to x64, an app is built in Release mode and debugger was not attached.

**Comment by adamsitnik** [comment]
Hi @usarskyy 

It's a know bug from TraceEvent library https://github.com/Microsoft/perfview/issues/735, which I have already fixed https://github.com/Microsoft/perfview/pull/737

You can wait until #878 gets merged or simply install the latest `Microsoft.Diagnostics.Tracing.TraceEvent` in your project with benchmarks.
