### ISSUE TITLE
Run benchmark with DisasemblyDiagnoser with `--disasam` option from console

### ISSUE THREAD

**Issue by wojtpl2** [dotnet/BenchmarkDotNet#938]
When you run benchmark with `DisasemblyDiagnoser` from console with parameter `--disasm` e.g.:
`dotnet BenchmarkDotNet.Samples.dll --filter *IntroDisassembly* --disasm`
or
`dotnet BenchmarkDotNet.Samples.dll --filter *IntroDisassemblyAllJits* --disasm`

then you will get unhandled exception:

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Configs.ManualConfig.GetExporters()+MoveNext() in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Configs\ManualConfig.cs:line 114
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at BenchmarkDotNet.Configs.ManualConfig.Add(IConfig config) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Configs\ManualConfig.cs:line 72
   at BenchmarkDotNet.Configs.ManualConfig.Union(IConfig globalConfig, IConfig localConfig) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Configs\ManualConfig.cs:line 156
   at BenchmarkDotNet.Running.BenchmarkConverter.GetFullConfig(Type type, IConfig config) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkConverter.cs:line 93
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkConverter.cs:line 24
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Running\TypeFilter.cs:line 42
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Running\TypeFilter.cs:line 41
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config) in C:\Work\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkSwitcher.cs:line 93
   at BenchmarkDotNet.Samples.Program.Main(String[] args) in C:\Work\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\Program.cs:line 7
```

**Comment by adamsitnik** [comment]
Hi @wojtpl2 

thanks for reporting this bug! I am aware of it, it's being solved in #912 where I change the way and moment when we build the final config.
