### ISSUE TITLE
Unhandled exception System.IndexOutOfRangeException when running 3 benchmarks

### ISSUE THREAD

**Issue by inkel** [dotnet/BenchmarkDotNet#950]
Hi, everyone.

I've a simple benchmarks suite, where I'm trying to compare the speed of JSON serialization using three different providers (Newtonsoft.Json, Jil and ServiceStack.Text) and I consistently get the following exception when trying to run the whole suite:

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BenchmarkDotNet.Mathematics.StatisticalTesting.MannWhitneyTest.PValueForSmallN(Int32 n, Int32 m, Double u)
   at BenchmarkDotNet.Mathematics.StatisticalTesting.MannWhitneyTest.IsGreater(Double[] x, Double[] y, Threshold threshold)
   at BenchmarkDotNet.Mathematics.StatisticalTesting.StatisticalTestHelper.CalculateTost[T](IOneSidedTest`1 test, Double[] baseline, Double[] candidate, Threshold threshold)
   at BenchmarkDotNet.Mathematics.RankHelper.AreSame(Statistics x, Statistics y)
   at BenchmarkDotNet.Mathematics.RankHelper.GetRanks(Statistics[] stats)
   at BenchmarkDotNet.Columns.RankColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at Benchmarks.Program.Main(String[] args) in C:\Users\inkel\source\repos\Foo\test\Benchmarks\Program.cs:line 19
```

Funny thing is that if I comment out **any** benchmark, leaving only two of them, I don't get the error anymore. Any ideas?

**Comment by wojtpl2** [comment]
It is the same problem like in #948 
In version 0.11.2, MannWhitneyTest class has been added. 
in the previous version 0.11.1 everything worked fine.

**Comment by inkel** [comment]
@wojtpl2 thanks. I'll try downgrading my installation and re-running the suite.

**Comment by inkel** [comment]
So far I can tell that running the suite is significantly faster and I haven't seen the same error. I'll run it a few more times so I can confirm things are fixed.

**Comment by wojtpl2** [comment]
I've created PR #951 with failing test.

**Comment by inkel** [comment]
Thanks. I'll subscribe to notifications in that one.
-- 
Leandro
(inkel)

**Comment by AndreyAkinshin** [comment]
Should be fixed now.

**Comment by inkel** [comment]
@AndreyAkinshin any ideas when a new version will be released?

**Comment by AndreyAkinshin** [comment]
@inkel v0.11.3 is already on nuget.org

**Comment by inkel** [comment]
@AndreyAkinshin awesome! I saw your announcement on Twitter today, that's great! Thanks 😸
