### ISSUE TITLE
Exception after upgrading from 0.11.2 to 0.11.3

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/BenchmarkDotNet#970]
I had this exception after upgrading to 0.11.3: 
```
Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at BenchmarkDotNet.Mathematics.Statistics.Divide(Statistics x, Statistics y)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.GetRatioStatistics(Statistics
current, Statistics baseline)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.<>c__DisplayClass12_0.<IsNonBa
selinesPrecise>b__0(BenchmarkCase x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate
)
   at BenchmarkDotNet.Columns.BaselineRatioColumn.GetValue(Summary summary, Benc
hmarkCase benchmarkCase, Statistics baseline, Statistics current, Boolean isBase
line)
   at BenchmarkDotNet.Columns.BaselineCustomColumn.GetValue(Summary summary, Ben
chmarkCase benchmarkCase)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle
style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostE
nvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath,
 TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunI
nfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artif
actsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRu
nInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig confi
g)
   at JsonWebToken.Performance.Program.Main(String[] args) in C:\dev\git\Jwt\tes
t\Benchmarks\Program.cs:line 11
```

**Comment by ycrumeyrolle** [comment]
I write a bit too fast... 
The benchmark causing the exception was not launch since the version 0.10.
