### ISSUE TITLE
NRE in `Summary` ctor

### ISSUE THREAD

**Issue by qbit86** [dotnet/BenchmarkDotNet#986]
I've got NRE at `BenchmarkDotNet.Columns.MetricColumn.<IsAvailable>b__19_0(BenchmarkReport report)` running this benchmark: [https://goo.gl/4RGThA](https://github.com/qbit86/spontaneous-benchmark/blob/8b780ebbd3398e80edef918d4a09c6f376874a86/benchmarks/Spontaneous.LanguageBenchmarks/ComparingToNullBenchmark.cs)
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Columns.MetricColumn.<IsAvailable>b__19_0(BenchmarkReport report)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChro
nometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at Spontaneous.Program.Main() in C:\Users\Viktor\Documents\GitHub\spontaneous-benchmark\benchmarks\Spontaneous.LanguageBenchmarks\Program.cs:line 10
```

Running on version 0.11.3 with following config:
```csharp
Summary _ = BenchmarkRunner.Run<ComparingToNullBenchmark>(ComparingToNullBenchmark.CreateDefaultConfig());
```

**Comment by qbit86** [comment]
Naïve fix leads to another NRE:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Columns.MetricColumn.GetValue(Summary summary, BenchmarkCase benchmarkCase, ISummaryStyle style)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary, ISummaryStyle style)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, HostEnvironmentInfo hostEnvironmentInfo, IConfig config, String resultsDirectoryPath, TimeSpan totalTime, ValidationError[] validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChro
nometer)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
   at Spontaneous.Program.Main() in C:\Users\Viktor\Documents\GitHub\spontaneous-benchmark\benchmarks\Spontaneous.LanguageBenchmarks\Program.cs:line 10
```

**Comment by qbit86** [comment]
One of the tests is failing with `PathTooLongException`: “The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.”

This [line](https://github.com/dotnet/BenchmarkDotNet/blob/89255c9fceb1b27c475a93d08c152349be4199e9/src/BenchmarkDotNet/Running/BenchmarkRunner.cs#L77) is in the stack trace starting from `AllSetupAndCleanupTargetSpecificBenchmarkTest.AllSetupAndCleanupMethodRunsForSpecificBenchmarkTest`:
```csharp
using (var logStreamWriter = StreamWriter.FromPath(Path.Combine(rootArtifactsFolderPath, title + ".log")))
```
In my case `rootArtifactsFolderPath` is "C:\Users\Viktor\Documents\GitHub\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\bin\Debug\net46\BenchmarkDotNet.Artifacts".
And `title` is "BenchmarkDotNet.IntegrationTests.AllSetupAndCleanupTargetSpecificBenchmarkTest.AllSetupAndCleanupAttributeSpecificTargetsBenchmarks".
Together they combine to 261 character.

**Comment by AndreyAkinshin** [comment]
> One of the tests is failing with PathTooLongException

I think it makes sense to upgrade `BenchmarkDotNet.Validators.ConfigValidator.ValidateArtifactsPath` and add the corresponding checks.

@qbit86 do you want to make another PR for this problem?

**Comment by qbit86** [comment]
> do you want to make another PR for this problem?

I'm not that deep into the internals of BDN, but yes, I can try to investigate the logic of validating during weekend or upcoming holidays.
